// Kernel Function: consume_step
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"



using namespace pto;


// --- ptoas-generated code ---

template <typename Tensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(Tensor &tensor)
    -> decltype(tensor.data()) {
  return tensor.data();
}


enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void consume_step(__gm__ int8_t* v1, __gm__ int32_t* v2, __gm__ int8_t* v3, __gm__ int32_t* v4, __gm__ int64_t* v5, __gm__ int64_t* v6) {
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  // pto: %c0_i64
  const int64_t v7 = 0;
  // pto: %c4160_index
  const int64_t v8 = 4160;
  // pto: %c1_index
  const int64_t v9 = 1;
  // pto: %c4_index
  const int64_t v10 = 4;
  // pto: %c0_index
  const int64_t v11 = 0;
  // pto: %c253_index
  const int64_t v12 = 253;
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
  for (int64_t v13 = v11; v13 < v10; v13 += v9) {
    // pto: %n_rows_i32__tile
    ;
    int32_t v14 = (v2)[v13];
    (v4)[v13] = v14;
    // pto: %2
    ;
    int64_t v15 = (int64_t) v14;
    // pto: %3
    ;
    int64_t v16 = (int64_t) ((uint64_t) v13 * (uint64_t) v12);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    for (int64_t v17 = v11; v17 < v15; v17 += v9) {
      // pto: %4
      ;
      int64_t v18 = (int64_t) ((uint64_t) v16 + (uint64_t) v17);
      // pto: %chunk__ssa_v0
      ;
      Tile<TileType::Vec, int8_t, 1, 4160, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v19 = Tile<TileType::Vec, int8_t, 1, 4160, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v9, v8);
      // pto: %chunk__ssa_v0
      ;
      uint64_t v20 = (uint64_t) v7;
      TASSIGN(v19, v20);
      // pto: %5
      ;
      int64_t v21 = v18 < v11 ? v11 : v18;
      // pto: %data__ssa_v0_pview
      ;
      const int64_t v22 = 0;
      // pto: %data__ssa_v0_pview
      ;
      const int64_t v23 = 4160;
      // pto: %data__ssa_v0_pview
      ;
      pto::Shape<1, 1, 1, 1, 4160> v24 = pto::Shape<1, 1, 1, 1, 4160>();
      // pto: %data__ssa_v0_pview
      ;
      pto::Stride<4160, 4160, 4160, 4160, 1> v25 = pto::Stride<4160, 4160, 4160, 4160, 1>();
      // pto: %data__ssa_v0_pview
      ;
      GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, 4160>, pto::Stride<4160, 4160, 4160, 4160, 1>, pto::Layout::ND> v26 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, 4160>, pto::Stride<4160, 4160, 4160, 4160, 1>, pto::Layout::ND>((__gm__ int8_t*) v1 + (v22 + v21 * v23), v24, v25);
      wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
      TLOAD(v19, v26);
      set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
      // pto: %out__iter_v3_pview
      ;
      const int64_t v27 = 0;
      // pto: %out__iter_v3_pview
      ;
      const int64_t v28 = 4160;
      // pto: %out__iter_v3_pview
      ;
      pto::Shape<1, 1, 1, 1, 4160> v29 = pto::Shape<1, 1, 1, 1, 4160>();
      // pto: %out__iter_v3_pview
      ;
      pto::Stride<4160, 4160, 4160, 4160, 1> v30 = pto::Stride<4160, 4160, 4160, 4160, 1>();
      // pto: %out__iter_v3_pview
      ;
      GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, 4160>, pto::Stride<4160, 4160, 4160, 4160, 1>, pto::Layout::ND> v31 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, 4160>, pto::Stride<4160, 4160, 4160, 4160, 1>, pto::Layout::ND>((__gm__ int8_t*) v3 + (v27 + v21 * v28), v29, v30);
      wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
      TSTORE(v31, v19);
      set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    };
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
    for (int64_t v32 = v15; v32 < v12; v32 += v9) {
      // pto: %8
      ;
      int64_t v33 = (int64_t) ((uint64_t) v16 + (uint64_t) v32);
      // pto: %chunk__ssa_v1
      ;
      Tile<TileType::Vec, int8_t, 1, 4160, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v34 = Tile<TileType::Vec, int8_t, 1, 4160, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v9, v8);
      // pto: %chunk__ssa_v1
      ;
      uint64_t v35 = (uint64_t) v7;
      TASSIGN(v34, v35);
      // pto: %9
      ;
      int64_t v36 = v33 < v11 ? v11 : v33;
      // pto: %10
      ;
      const int64_t v37 = 0;
      // pto: %10
      ;
      const int64_t v38 = 4160;
      // pto: %10
      ;
      pto::Shape<1, 1, 1, 1, 4160> v39 = pto::Shape<1, 1, 1, 1, 4160>();
      // pto: %10
      ;
      pto::Stride<4160, 4160, 4160, 4160, 1> v40 = pto::Stride<4160, 4160, 4160, 4160, 1>();
      // pto: %10
      ;
      GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, 4160>, pto::Stride<4160, 4160, 4160, 4160, 1>, pto::Layout::ND> v41 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, 4160>, pto::Stride<4160, 4160, 4160, 4160, 1>, pto::Layout::ND>((__gm__ int8_t*) v1 + (v37 + v36 * v38), v39, v40);
      wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
      TLOAD(v34, v41);
      set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID1);
      // pto: %out__iter_v6_pview
      ;
      const int64_t v42 = 0;
      // pto: %out__iter_v6_pview
      ;
      const int64_t v43 = 4160;
      // pto: %out__iter_v6_pview
      ;
      pto::Shape<1, 1, 1, 1, 4160> v44 = pto::Shape<1, 1, 1, 1, 4160>();
      // pto: %out__iter_v6_pview
      ;
      pto::Stride<4160, 4160, 4160, 4160, 1> v45 = pto::Stride<4160, 4160, 4160, 4160, 1>();
      // pto: %out__iter_v6_pview
      ;
      GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, 4160>, pto::Stride<4160, 4160, 4160, 4160, 1>, pto::Layout::ND> v46 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, 4160>, pto::Stride<4160, 4160, 4160, 4160, 1>, pto::Layout::ND>((__gm__ int8_t*) v3 + (v42 + v36 * v43), v44, v45);
      wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID1);
      TSTORE(v46, v34);
      set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
    };
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  }
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
  pipe_barrier(PIPE_ALL);
  dcci((__gm__ void*)0, cache_line_t::ENTIRE_DATA_CACHE);
  dsb((mem_dsb_t)0);
  #endif // __DAV_VEC__

  pipe_barrier(PIPE_ALL);
  dcci((__gm__ void*)0, cache_line_t::ENTIRE_DATA_CACHE);
  dsb((mem_dsb_t)0);
  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM) && !defined(__COSTMODEL)
    // Reset AI Core atomic mode inherited from a prior kernel.
    set_atomic_none();
#endif

    // Unpack tensor: data__ssa_v0
    __gm__ Tensor* data__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ int8_t* data__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(data__ssa_v0_tensor->buffer.addr) + data__ssa_v0_tensor->start_offset;

    // Unpack tensor: recv_counts__ssa_v0
    __gm__ Tensor* recv_counts__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int32_t* recv_counts__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(recv_counts__ssa_v0_tensor->buffer.addr) + recv_counts__ssa_v0_tensor->start_offset;

    // Unpack tensor: out__ssa_v0
    __gm__ Tensor* out__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ int8_t* out__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(out__ssa_v0_tensor->buffer.addr) + out__ssa_v0_tensor->start_offset;

    // Unpack tensor: recv_out__ssa_v0
    __gm__ Tensor* recv_out__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ int32_t* recv_out__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(recv_out__ssa_v0_tensor->buffer.addr) + recv_out__ssa_v0_tensor->start_offset;

    // Unpack CommContext: data_ctx
    __gm__ int64_t* data_ctx = reinterpret_cast<__gm__ int64_t*>(args[4]);

    // Unpack CommContext: recv_counts_ctx
    __gm__ int64_t* recv_counts_ctx = reinterpret_cast<__gm__ int64_t*>(args[5]);

    // Forward to ptoas-generated function
    consume_step(data__ssa_v0, recv_counts__ssa_v0, out__ssa_v0, recv_out__ssa_v0, data_ctx, recv_counts_ctx);
}
