// Kernel Function: stage_step
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"



using namespace pto;


// --- ptoas-generated code ---

template <typename Tensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(Tensor &tensor)
    -> decltype(tensor.data()) {
  return tensor.data();
}


enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void stage_step(__gm__ int8_t* v1, __gm__ int8_t* v2, __gm__ int64_t* v3) {
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  // pto: %c0_i64
  const int64_t v4 = 0;
  // pto: %c506_index
  const int64_t v5 = 506;
  // pto: %c4160_index
  const int64_t v6 = 4160;
  // pto: %c1_index
  const int64_t v7 = 1;
  // pto: %c0_index
  const int64_t v8 = 0;
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  for (int64_t v9 = v8; v9 < v5; v9 += v7) {
    // pto: %chunk__ssa_v0
    ;
    Tile<TileType::Vec, int8_t, 1, 4160, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v10 = Tile<TileType::Vec, int8_t, 1, 4160, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v6);
    // pto: %chunk__ssa_v0
    ;
    uint64_t v11 = (uint64_t) v4;
    TASSIGN(v10, v11);
    // pto: %0
    ;
    int64_t v12 = v9 < v8 ? v8 : v9;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v13 = 0;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v14 = 4160;
    // pto: %inp__ssa_v0_pview
    ;
    pto::Shape<1, 1, 1, 1, 4160> v15 = pto::Shape<1, 1, 1, 1, 4160>();
    // pto: %inp__ssa_v0_pview
    ;
    pto::Stride<4160, 4160, 4160, 4160, 1> v16 = pto::Stride<4160, 4160, 4160, 4160, 1>();
    // pto: %inp__ssa_v0_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, 4160>, pto::Stride<4160, 4160, 4160, 4160, 1>, pto::Layout::ND> v17 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, 4160>, pto::Stride<4160, 4160, 4160, 4160, 1>, pto::Layout::ND>((__gm__ int8_t*) v1 + (v13 + v12 * v14), v15, v16);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    TLOAD(v10, v17);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v18 = 0;
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v19 = 4160;
    // pto: %stage__iter_v1_pview
    ;
    pto::Shape<1, 1, 1, 1, 4160> v20 = pto::Shape<1, 1, 1, 1, 4160>();
    // pto: %stage__iter_v1_pview
    ;
    pto::Stride<4160, 4160, 4160, 4160, 1> v21 = pto::Stride<4160, 4160, 4160, 4160, 1>();
    // pto: %stage__iter_v1_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, 4160>, pto::Stride<4160, 4160, 4160, 4160, 1>, pto::Layout::ND> v22 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, 4160>, pto::Stride<4160, 4160, 4160, 4160, 1>, pto::Layout::ND>((__gm__ int8_t*) v2 + (v18 + v12 * v19), v20, v21);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v22, v10);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    // pto: %2
    ;
    pto::Shape<1, 1, 1, 506, 4160> v23 = pto::Shape<1, 1, 1, 506, 4160>();
    // pto: %2
    ;
    pto::Stride<2104960, 2104960, 2104960, 4160, 1> v24 = pto::Stride<2104960, 2104960, 2104960, 4160, 1>();
    // pto: %2
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 506, 4160>, pto::Stride<2104960, 2104960, 2104960, 4160, 1>, pto::Layout::ND> v25 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 506, 4160>, pto::Stride<2104960, 2104960, 2104960, 4160, 1>, pto::Layout::ND>((__gm__ int8_t*) v2, v23, v24);
    __gm__ int8_t* v26 = PTOAS__GLOBAL_TENSOR_DATA(v25);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v26);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
  }
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM) && !defined(__COSTMODEL)
    // Reset AI Core atomic mode inherited from a prior kernel.
    set_atomic_none();
#endif

    // Unpack tensor: inp__ssa_v0
    __gm__ Tensor* inp__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ int8_t* inp__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(inp__ssa_v0_tensor->buffer.addr) + inp__ssa_v0_tensor->start_offset;

    // Unpack tensor: stage__ssa_v0
    __gm__ Tensor* stage__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int8_t* stage__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(stage__ssa_v0_tensor->buffer.addr) + stage__ssa_v0_tensor->start_offset;

    // Unpack CommContext: stage_ctx
    __gm__ int64_t* stage_ctx = reinterpret_cast<__gm__ int64_t*>(args[2]);

    // Forward to ptoas-generated function
    stage_step(inp__ssa_v0, stage__ssa_v0, stage_ctx);
}
