// Orchestration Function: consume_orch
// Generated by PyPTO IR Compiler

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "orchestration_api.h"
#include "tensor.h"

extern "C" {

__attribute__((visibility("default")))
OrchestrationConfig aicpu_orchestration_config(const ChipTaskArgs& orch_args) {
    (void)orch_args;
    return OrchestrationConfig{
        .expected_arg_count = 6,
    };
}

__attribute__((visibility("default")))
void aicpu_orchestration_entry(const ChipTaskArgs& orch_args) {
    // External tensors
    const Tensor& ext_data = orch_args.tensor(0).ref();
    const Tensor& ext_recv_counts = orch_args.tensor(1).ref();
    const Tensor& ext_out = orch_args.tensor(2).ref();
    const Tensor& ext_recv_out = orch_args.tensor(3).ref();

    // Scalar params
    uint64_t data_ctx = orch_args.scalar(0);
    uint64_t recv_counts_ctx = orch_args.scalar(1);

    SIMPLER_SCOPE() {

        // Task 0: consume_step
        CoreTaskArgs params_t0;
        params_t0.add_input(ext_data);
        params_t0.add_input(ext_recv_counts);
        params_t0.add_output(ext_out);
        params_t0.add_output(ext_recv_out);
        params_t0.add_scalar(data_ctx);
        params_t0.add_scalar(recv_counts_ctx);
        rt_submit_aiv_task(0, params_t0);
    }
}

}  // extern "C"
