// Kernel Function: stage_step
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"



using namespace pto;


// --- ptoas-generated code ---

template <typename Tensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(Tensor &tensor)
    -> decltype(tensor.data()) {
  return tensor.data();
}


enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void stage_step(__gm__ int8_t* v1, __gm__ int32_t* v2, __gm__ int8_t* v3, __gm__ int32_t* v4, __gm__ int64_t* v5, __gm__ int64_t* v6) {
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  // pto: %c0_i64
  const int64_t v7 = 0;
  // pto: %c2_index
  const int64_t v8 = 2;
  // pto: %c131072_index
  const int64_t v9 = 131072;
  // pto: %c1_index
  const int64_t v10 = 1;
  // pto: %c0_index
  const int64_t v11 = 0;
  // pto: %c16384_index
  const int64_t v12 = 16384;
  // pto: %c32768_index
  const int64_t v13 = 32768;
  // pto: %c49152_index
  const int64_t v14 = 49152;
  // pto: %c65536_index
  const int64_t v15 = 65536;
  // pto: %c81920_index
  const int64_t v16 = 81920;
  // pto: %c98304_index
  const int64_t v17 = 98304;
  // pto: %c114688_index
  const int64_t v18 = 114688;
  // pto: %inp__ssa_v0_view
  const int64_t v19 = 1;
  // pto: %inp__ssa_v0_view
  const int64_t v20 = 1;
  // pto: %inp__ssa_v0_view
  const int64_t v21 = 1;
  // pto: %inp__ssa_v0_view
  int64_t v22 = v8 * v9;
  // pto: %inp__ssa_v0_view
  int64_t v23 = v21 * v22;
  // pto: %inp__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v24 = pto::Shape<1, 1, 1, -1, -1>(v19, v20, v21, v8, v9);
  // pto: %inp__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v25 = pto::Stride<-1, -1, -1, -1, -1>(v20 * v23, v23, v22, v9, v10);
  // pto: %inp__ssa_v0_view
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v26 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v1, v24, v25);
  // pto: %stage__ssa_v0_view
  const int64_t v27 = 1;
  // pto: %stage__ssa_v0_view
  const int64_t v28 = 1;
  // pto: %stage__ssa_v0_view
  const int64_t v29 = 1;
  // pto: %stage__ssa_v0_view
  int64_t v30 = v8 * v9;
  // pto: %stage__ssa_v0_view
  int64_t v31 = v29 * v30;
  // pto: %stage__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v32 = pto::Shape<1, 1, 1, -1, -1>(v27, v28, v29, v8, v9);
  // pto: %stage__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v33 = pto::Stride<-1, -1, -1, -1, -1>(v28 * v31, v31, v30, v9, v10);
  // pto: %stage__ssa_v0_view
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v34 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v3, v32, v33);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  for (int64_t v35 = v11; v35 < v8; v35 += v10) {
    // pto: %tile__ssa_v0
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v36 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v0
    ;
    uint64_t v37 = (uint64_t) v7;
    TASSIGN(v36, v37);
    // pto: %0
    ;
    int64_t v38 = v35 < v11 ? v11 : v35;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v39 = 0;
    // pto: %inp__ssa_v0_pview
    ;
    __gm__ int8_t* v40 = PTOAS__GLOBAL_TENSOR_DATA(v26);
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v41 = 1;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v42 = 1;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v43 = 1;
    // pto: %inp__ssa_v0_pview
    ;
    int64_t v44 = v10 * v9;
    // pto: %inp__ssa_v0_pview
    ;
    int64_t v45 = v43 * v44;
    // pto: %inp__ssa_v0_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v46 = pto::Shape<1, 1, 1, 1, -1>(v41, v42, v43, v10, v12);
    // pto: %inp__ssa_v0_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v47 = pto::Stride<-1, -1, -1, -1, -1>(v42 * v45, v45, v44, v9, v10);
    // pto: %inp__ssa_v0_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v48 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v40 + (v39 + v38 * v9 + v11 * v10), v46, v47);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    TLOAD(v36, v48);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v49 = 0;
    // pto: %stage__iter_v1_pview
    ;
    __gm__ int8_t* v50 = PTOAS__GLOBAL_TENSOR_DATA(v34);
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v51 = 1;
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v52 = 1;
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v53 = 1;
    // pto: %stage__iter_v1_pview
    ;
    int64_t v54 = v10 * v9;
    // pto: %stage__iter_v1_pview
    ;
    int64_t v55 = v53 * v54;
    // pto: %stage__iter_v1_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v56 = pto::Shape<1, 1, 1, 1, -1>(v51, v52, v53, v10, v12);
    // pto: %stage__iter_v1_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v57 = pto::Stride<-1, -1, -1, -1, -1>(v52 * v55, v55, v54, v9, v10);
    // pto: %stage__iter_v1_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v58 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v50 + (v49 + v38 * v9 + v11 * v10), v56, v57);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v58, v36);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    // pto: %2
    ;
    pto::Shape<1, 1, 1, 2, 131072> v59 = pto::Shape<1, 1, 1, 2, 131072>();
    // pto: %2
    ;
    pto::Stride<262144, 262144, 262144, 131072, 1> v60 = pto::Stride<262144, 262144, 262144, 131072, 1>();
    // pto: %2
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 2, 131072>, pto::Stride<262144, 262144, 262144, 131072, 1>, pto::Layout::ND> v61 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 2, 131072>, pto::Stride<262144, 262144, 262144, 131072, 1>, pto::Layout::ND>((__gm__ int8_t*) v3, v59, v60);
    __gm__ int8_t* v62 = PTOAS__GLOBAL_TENSOR_DATA(v61);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v62);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v1
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v63 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v1
    ;
    uint64_t v64 = (uint64_t) v7;
    TASSIGN(v63, v64);
    // pto: %4
    ;
    const int64_t v65 = 0;
    // pto: %4
    ;
    __gm__ int8_t* v66 = PTOAS__GLOBAL_TENSOR_DATA(v26);
    // pto: %4
    ;
    const int64_t v67 = 1;
    // pto: %4
    ;
    const int64_t v68 = 1;
    // pto: %4
    ;
    const int64_t v69 = 1;
    // pto: %4
    ;
    int64_t v70 = v10 * v9;
    // pto: %4
    ;
    int64_t v71 = v69 * v70;
    // pto: %4
    ;
    pto::Shape<1, 1, 1, 1, -1> v72 = pto::Shape<1, 1, 1, 1, -1>(v67, v68, v69, v10, v12);
    // pto: %4
    ;
    pto::Stride<-1, -1, -1, -1, -1> v73 = pto::Stride<-1, -1, -1, -1, -1>(v68 * v71, v71, v70, v9, v10);
    // pto: %4
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v74 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v66 + (v65 + v38 * v9 + v12 * v10), v72, v73);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v63, v74);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID1);
    // pto: %stage__ssa_v3_pview
    ;
    const int64_t v75 = 0;
    // pto: %stage__ssa_v3_pview
    ;
    __gm__ int8_t* v76 = PTOAS__GLOBAL_TENSOR_DATA(v34);
    // pto: %stage__ssa_v3_pview
    ;
    const int64_t v77 = 1;
    // pto: %stage__ssa_v3_pview
    ;
    const int64_t v78 = 1;
    // pto: %stage__ssa_v3_pview
    ;
    const int64_t v79 = 1;
    // pto: %stage__ssa_v3_pview
    ;
    int64_t v80 = v10 * v9;
    // pto: %stage__ssa_v3_pview
    ;
    int64_t v81 = v79 * v80;
    // pto: %stage__ssa_v3_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v82 = pto::Shape<1, 1, 1, 1, -1>(v77, v78, v79, v10, v12);
    // pto: %stage__ssa_v3_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v83 = pto::Stride<-1, -1, -1, -1, -1>(v78 * v81, v81, v80, v9, v10);
    // pto: %stage__ssa_v3_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v84 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v76 + (v75 + v38 * v9 + v12 * v10), v82, v83);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID1);
    TSTORE(v84, v63);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
    __gm__ int8_t* v85 = PTOAS__GLOBAL_TENSOR_DATA(v61);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v85);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v2
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v86 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v2
    ;
    uint64_t v87 = (uint64_t) v7;
    TASSIGN(v86, v87);
    // pto: %8
    ;
    const int64_t v88 = 0;
    // pto: %8
    ;
    __gm__ int8_t* v89 = PTOAS__GLOBAL_TENSOR_DATA(v26);
    // pto: %8
    ;
    const int64_t v90 = 1;
    // pto: %8
    ;
    const int64_t v91 = 1;
    // pto: %8
    ;
    const int64_t v92 = 1;
    // pto: %8
    ;
    int64_t v93 = v10 * v9;
    // pto: %8
    ;
    int64_t v94 = v92 * v93;
    // pto: %8
    ;
    pto::Shape<1, 1, 1, 1, -1> v95 = pto::Shape<1, 1, 1, 1, -1>(v90, v91, v92, v10, v12);
    // pto: %8
    ;
    pto::Stride<-1, -1, -1, -1, -1> v96 = pto::Stride<-1, -1, -1, -1, -1>(v91 * v94, v94, v93, v9, v10);
    // pto: %8
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v97 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v89 + (v88 + v38 * v9 + v13 * v10), v95, v96);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
    TLOAD(v86, v97);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID2);
    // pto: %stage__ssa_v4_pview
    ;
    const int64_t v98 = 0;
    // pto: %stage__ssa_v4_pview
    ;
    __gm__ int8_t* v99 = PTOAS__GLOBAL_TENSOR_DATA(v34);
    // pto: %stage__ssa_v4_pview
    ;
    const int64_t v100 = 1;
    // pto: %stage__ssa_v4_pview
    ;
    const int64_t v101 = 1;
    // pto: %stage__ssa_v4_pview
    ;
    const int64_t v102 = 1;
    // pto: %stage__ssa_v4_pview
    ;
    int64_t v103 = v10 * v9;
    // pto: %stage__ssa_v4_pview
    ;
    int64_t v104 = v102 * v103;
    // pto: %stage__ssa_v4_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v105 = pto::Shape<1, 1, 1, 1, -1>(v100, v101, v102, v10, v12);
    // pto: %stage__ssa_v4_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v106 = pto::Stride<-1, -1, -1, -1, -1>(v101 * v104, v104, v103, v9, v10);
    // pto: %stage__ssa_v4_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v107 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v99 + (v98 + v38 * v9 + v13 * v10), v105, v106);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID2);
    TSTORE(v107, v86);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
    __gm__ int8_t* v108 = PTOAS__GLOBAL_TENSOR_DATA(v61);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v108);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v3
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v109 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v3
    ;
    uint64_t v110 = (uint64_t) v7;
    TASSIGN(v109, v110);
    // pto: %12
    ;
    const int64_t v111 = 0;
    // pto: %12
    ;
    __gm__ int8_t* v112 = PTOAS__GLOBAL_TENSOR_DATA(v26);
    // pto: %12
    ;
    const int64_t v113 = 1;
    // pto: %12
    ;
    const int64_t v114 = 1;
    // pto: %12
    ;
    const int64_t v115 = 1;
    // pto: %12
    ;
    int64_t v116 = v10 * v9;
    // pto: %12
    ;
    int64_t v117 = v115 * v116;
    // pto: %12
    ;
    pto::Shape<1, 1, 1, 1, -1> v118 = pto::Shape<1, 1, 1, 1, -1>(v113, v114, v115, v10, v12);
    // pto: %12
    ;
    pto::Stride<-1, -1, -1, -1, -1> v119 = pto::Stride<-1, -1, -1, -1, -1>(v114 * v117, v117, v116, v9, v10);
    // pto: %12
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v120 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v112 + (v111 + v38 * v9 + v14 * v10), v118, v119);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
    TLOAD(v109, v120);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID3);
    // pto: %stage__ssa_v5_pview
    ;
    const int64_t v121 = 0;
    // pto: %stage__ssa_v5_pview
    ;
    __gm__ int8_t* v122 = PTOAS__GLOBAL_TENSOR_DATA(v34);
    // pto: %stage__ssa_v5_pview
    ;
    const int64_t v123 = 1;
    // pto: %stage__ssa_v5_pview
    ;
    const int64_t v124 = 1;
    // pto: %stage__ssa_v5_pview
    ;
    const int64_t v125 = 1;
    // pto: %stage__ssa_v5_pview
    ;
    int64_t v126 = v10 * v9;
    // pto: %stage__ssa_v5_pview
    ;
    int64_t v127 = v125 * v126;
    // pto: %stage__ssa_v5_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v128 = pto::Shape<1, 1, 1, 1, -1>(v123, v124, v125, v10, v12);
    // pto: %stage__ssa_v5_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v129 = pto::Stride<-1, -1, -1, -1, -1>(v124 * v127, v127, v126, v9, v10);
    // pto: %stage__ssa_v5_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v130 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v122 + (v121 + v38 * v9 + v14 * v10), v128, v129);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID3);
    TSTORE(v130, v109);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID4);
    __gm__ int8_t* v131 = PTOAS__GLOBAL_TENSOR_DATA(v61);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v131);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v4
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v132 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v4
    ;
    uint64_t v133 = (uint64_t) v7;
    TASSIGN(v132, v133);
    // pto: %16
    ;
    const int64_t v134 = 0;
    // pto: %16
    ;
    __gm__ int8_t* v135 = PTOAS__GLOBAL_TENSOR_DATA(v26);
    // pto: %16
    ;
    const int64_t v136 = 1;
    // pto: %16
    ;
    const int64_t v137 = 1;
    // pto: %16
    ;
    const int64_t v138 = 1;
    // pto: %16
    ;
    int64_t v139 = v10 * v9;
    // pto: %16
    ;
    int64_t v140 = v138 * v139;
    // pto: %16
    ;
    pto::Shape<1, 1, 1, 1, -1> v141 = pto::Shape<1, 1, 1, 1, -1>(v136, v137, v138, v10, v12);
    // pto: %16
    ;
    pto::Stride<-1, -1, -1, -1, -1> v142 = pto::Stride<-1, -1, -1, -1, -1>(v137 * v140, v140, v139, v9, v10);
    // pto: %16
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v143 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v135 + (v134 + v38 * v9 + v15 * v10), v141, v142);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID4);
    TLOAD(v132, v143);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID4);
    // pto: %stage__ssa_v6_pview
    ;
    const int64_t v144 = 0;
    // pto: %stage__ssa_v6_pview
    ;
    __gm__ int8_t* v145 = PTOAS__GLOBAL_TENSOR_DATA(v34);
    // pto: %stage__ssa_v6_pview
    ;
    const int64_t v146 = 1;
    // pto: %stage__ssa_v6_pview
    ;
    const int64_t v147 = 1;
    // pto: %stage__ssa_v6_pview
    ;
    const int64_t v148 = 1;
    // pto: %stage__ssa_v6_pview
    ;
    int64_t v149 = v10 * v9;
    // pto: %stage__ssa_v6_pview
    ;
    int64_t v150 = v148 * v149;
    // pto: %stage__ssa_v6_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v151 = pto::Shape<1, 1, 1, 1, -1>(v146, v147, v148, v10, v12);
    // pto: %stage__ssa_v6_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v152 = pto::Stride<-1, -1, -1, -1, -1>(v147 * v150, v150, v149, v9, v10);
    // pto: %stage__ssa_v6_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v153 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v145 + (v144 + v38 * v9 + v15 * v10), v151, v152);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID4);
    TSTORE(v153, v132);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID5);
    __gm__ int8_t* v154 = PTOAS__GLOBAL_TENSOR_DATA(v61);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v154);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v5
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v155 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v5
    ;
    uint64_t v156 = (uint64_t) v7;
    TASSIGN(v155, v156);
    // pto: %20
    ;
    const int64_t v157 = 0;
    // pto: %20
    ;
    __gm__ int8_t* v158 = PTOAS__GLOBAL_TENSOR_DATA(v26);
    // pto: %20
    ;
    const int64_t v159 = 1;
    // pto: %20
    ;
    const int64_t v160 = 1;
    // pto: %20
    ;
    const int64_t v161 = 1;
    // pto: %20
    ;
    int64_t v162 = v10 * v9;
    // pto: %20
    ;
    int64_t v163 = v161 * v162;
    // pto: %20
    ;
    pto::Shape<1, 1, 1, 1, -1> v164 = pto::Shape<1, 1, 1, 1, -1>(v159, v160, v161, v10, v12);
    // pto: %20
    ;
    pto::Stride<-1, -1, -1, -1, -1> v165 = pto::Stride<-1, -1, -1, -1, -1>(v160 * v163, v163, v162, v9, v10);
    // pto: %20
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v166 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v158 + (v157 + v38 * v9 + v16 * v10), v164, v165);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID5);
    TLOAD(v155, v166);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID5);
    // pto: %stage__ssa_v7_pview
    ;
    const int64_t v167 = 0;
    // pto: %stage__ssa_v7_pview
    ;
    __gm__ int8_t* v168 = PTOAS__GLOBAL_TENSOR_DATA(v34);
    // pto: %stage__ssa_v7_pview
    ;
    const int64_t v169 = 1;
    // pto: %stage__ssa_v7_pview
    ;
    const int64_t v170 = 1;
    // pto: %stage__ssa_v7_pview
    ;
    const int64_t v171 = 1;
    // pto: %stage__ssa_v7_pview
    ;
    int64_t v172 = v10 * v9;
    // pto: %stage__ssa_v7_pview
    ;
    int64_t v173 = v171 * v172;
    // pto: %stage__ssa_v7_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v174 = pto::Shape<1, 1, 1, 1, -1>(v169, v170, v171, v10, v12);
    // pto: %stage__ssa_v7_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v175 = pto::Stride<-1, -1, -1, -1, -1>(v170 * v173, v173, v172, v9, v10);
    // pto: %stage__ssa_v7_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v176 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v168 + (v167 + v38 * v9 + v16 * v10), v174, v175);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID5);
    TSTORE(v176, v155);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID6);
    __gm__ int8_t* v177 = PTOAS__GLOBAL_TENSOR_DATA(v61);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v177);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v6
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v178 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v6
    ;
    uint64_t v179 = (uint64_t) v7;
    TASSIGN(v178, v179);
    // pto: %24
    ;
    const int64_t v180 = 0;
    // pto: %24
    ;
    __gm__ int8_t* v181 = PTOAS__GLOBAL_TENSOR_DATA(v26);
    // pto: %24
    ;
    const int64_t v182 = 1;
    // pto: %24
    ;
    const int64_t v183 = 1;
    // pto: %24
    ;
    const int64_t v184 = 1;
    // pto: %24
    ;
    int64_t v185 = v10 * v9;
    // pto: %24
    ;
    int64_t v186 = v184 * v185;
    // pto: %24
    ;
    pto::Shape<1, 1, 1, 1, -1> v187 = pto::Shape<1, 1, 1, 1, -1>(v182, v183, v184, v10, v12);
    // pto: %24
    ;
    pto::Stride<-1, -1, -1, -1, -1> v188 = pto::Stride<-1, -1, -1, -1, -1>(v183 * v186, v186, v185, v9, v10);
    // pto: %24
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v189 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v181 + (v180 + v38 * v9 + v17 * v10), v187, v188);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID6);
    TLOAD(v178, v189);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID6);
    // pto: %stage__ssa_v8_pview
    ;
    const int64_t v190 = 0;
    // pto: %stage__ssa_v8_pview
    ;
    __gm__ int8_t* v191 = PTOAS__GLOBAL_TENSOR_DATA(v34);
    // pto: %stage__ssa_v8_pview
    ;
    const int64_t v192 = 1;
    // pto: %stage__ssa_v8_pview
    ;
    const int64_t v193 = 1;
    // pto: %stage__ssa_v8_pview
    ;
    const int64_t v194 = 1;
    // pto: %stage__ssa_v8_pview
    ;
    int64_t v195 = v10 * v9;
    // pto: %stage__ssa_v8_pview
    ;
    int64_t v196 = v194 * v195;
    // pto: %stage__ssa_v8_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v197 = pto::Shape<1, 1, 1, 1, -1>(v192, v193, v194, v10, v12);
    // pto: %stage__ssa_v8_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v198 = pto::Stride<-1, -1, -1, -1, -1>(v193 * v196, v196, v195, v9, v10);
    // pto: %stage__ssa_v8_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v199 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v191 + (v190 + v38 * v9 + v17 * v10), v197, v198);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID6);
    TSTORE(v199, v178);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID7);
    __gm__ int8_t* v200 = PTOAS__GLOBAL_TENSOR_DATA(v61);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v200);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v7
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v201 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v7
    ;
    uint64_t v202 = (uint64_t) v7;
    TASSIGN(v201, v202);
    // pto: %28
    ;
    const int64_t v203 = 0;
    // pto: %28
    ;
    __gm__ int8_t* v204 = PTOAS__GLOBAL_TENSOR_DATA(v26);
    // pto: %28
    ;
    const int64_t v205 = 1;
    // pto: %28
    ;
    const int64_t v206 = 1;
    // pto: %28
    ;
    const int64_t v207 = 1;
    // pto: %28
    ;
    int64_t v208 = v10 * v9;
    // pto: %28
    ;
    int64_t v209 = v207 * v208;
    // pto: %28
    ;
    pto::Shape<1, 1, 1, 1, -1> v210 = pto::Shape<1, 1, 1, 1, -1>(v205, v206, v207, v10, v12);
    // pto: %28
    ;
    pto::Stride<-1, -1, -1, -1, -1> v211 = pto::Stride<-1, -1, -1, -1, -1>(v206 * v209, v209, v208, v9, v10);
    // pto: %28
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v212 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v204 + (v203 + v38 * v9 + v18 * v10), v210, v211);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID7);
    TLOAD(v201, v212);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID7);
    // pto: %stage__ssa_v9_pview
    ;
    const int64_t v213 = 0;
    // pto: %stage__ssa_v9_pview
    ;
    __gm__ int8_t* v214 = PTOAS__GLOBAL_TENSOR_DATA(v34);
    // pto: %stage__ssa_v9_pview
    ;
    const int64_t v215 = 1;
    // pto: %stage__ssa_v9_pview
    ;
    const int64_t v216 = 1;
    // pto: %stage__ssa_v9_pview
    ;
    const int64_t v217 = 1;
    // pto: %stage__ssa_v9_pview
    ;
    int64_t v218 = v10 * v9;
    // pto: %stage__ssa_v9_pview
    ;
    int64_t v219 = v217 * v218;
    // pto: %stage__ssa_v9_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v220 = pto::Shape<1, 1, 1, 1, -1>(v215, v216, v217, v10, v12);
    // pto: %stage__ssa_v9_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v221 = pto::Stride<-1, -1, -1, -1, -1>(v216 * v219, v219, v218, v9, v10);
    // pto: %stage__ssa_v9_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v222 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v214 + (v213 + v38 * v9 + v18 * v10), v220, v221);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID7);
    TSTORE(v222, v201);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    __gm__ int8_t* v223 = PTOAS__GLOBAL_TENSOR_DATA(v61);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v223);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
  }
  for (int64_t v224 = v11; v224 < v8; v224 += v10) {
    // pto: %v__tile
    ;
    int32_t v225 = (v2)[v224];
    (v4)[v224] = v225;
    // pto: %counts__ssa_v0_pview
    ;
    pto::Shape<1, 1, 1, 2, 1> v226 = pto::Shape<1, 1, 1, 2, 1>();
    // pto: %counts__ssa_v0_pview
    ;
    pto::Stride<2, 2, 2, 1, 2> v227 = pto::Stride<2, 2, 2, 1, 2>();
    // pto: %counts__ssa_v0_pview
    ;
    GlobalTensor<int32_t, pto::Shape<1, 1, 1, 2, 1>, pto::Stride<2, 2, 2, 1, 2>, pto::Layout::DN> v228 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 2, 1>, pto::Stride<2, 2, 2, 1, 2>, pto::Layout::DN>((__gm__ int32_t*) v4, v226, v227);
    __gm__ int32_t* v229 = PTOAS__GLOBAL_TENSOR_DATA(v228);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v229);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
  }
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  pipe_barrier(PIPE_ALL);
  dcci((__gm__ void*)0, cache_line_t::ENTIRE_DATA_CACHE);
  dsb((mem_dsb_t)0);
  #endif // __DAV_VEC__

  pipe_barrier(PIPE_ALL);
  dcci((__gm__ void*)0, cache_line_t::ENTIRE_DATA_CACHE);
  dsb((mem_dsb_t)0);
  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM) && !defined(__COSTMODEL)
    // Reset AI Core atomic mode inherited from a prior kernel.
    set_atomic_none();
#endif

    // Unpack tensor: inp__ssa_v0
    __gm__ Tensor* inp__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ int8_t* inp__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(inp__ssa_v0_tensor->buffer.addr) + inp__ssa_v0_tensor->start_offset;

    // Unpack tensor: counts_row__ssa_v0
    __gm__ Tensor* counts_row__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int32_t* counts_row__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(counts_row__ssa_v0_tensor->buffer.addr) + counts_row__ssa_v0_tensor->start_offset;

    // Unpack tensor: stage__ssa_v0
    __gm__ Tensor* stage__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ int8_t* stage__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(stage__ssa_v0_tensor->buffer.addr) + stage__ssa_v0_tensor->start_offset;

    // Unpack tensor: counts__ssa_v0
    __gm__ Tensor* counts__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ int32_t* counts__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(counts__ssa_v0_tensor->buffer.addr) + counts__ssa_v0_tensor->start_offset;

    // Unpack CommContext: stage_ctx
    __gm__ int64_t* stage_ctx = reinterpret_cast<__gm__ int64_t*>(args[4]);

    // Unpack CommContext: counts_ctx
    __gm__ int64_t* counts_ctx = reinterpret_cast<__gm__ int64_t*>(args[5]);

    // Forward to ptoas-generated function
    stage_step(inp__ssa_v0, counts_row__ssa_v0, stage__ssa_v0, counts__ssa_v0, stage_ctx, counts_ctx);
}
