// Orchestration Function: stage_orch
// Generated by PyPTO IR Compiler

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "orchestration_api.h"
#include "tensor.h"

extern "C" {

__attribute__((visibility("default")))
OrchestrationConfig aicpu_orchestration_config(const ChipTaskArgs& orch_args) {
    (void)orch_args;
    return OrchestrationConfig{
        .expected_arg_count = 3,
    };
}

__attribute__((visibility("default")))
void aicpu_orchestration_entry(const ChipTaskArgs& orch_args) {
    // External tensors
    const Tensor& ext_inp = orch_args.tensor(0).ref();
    const Tensor& ext_stage = orch_args.tensor(1).ref();

    // Scalar params
    uint64_t stage_ctx = orch_args.scalar(0);

    SIMPLER_SCOPE() {

        // Task 0: stage_step
        CoreTaskArgs params_t0;
        params_t0.add_input(ext_inp);
        params_t0.add_output(ext_stage);
        params_t0.add_scalar(stage_ctx);
        rt_submit_aiv_task(0, params_t0);
    }
}

}  // extern "C"
