// Kernel Function: reduce_step
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"



using namespace pto;


// --- ptoas-generated code ---

template <typename TaskTensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(TaskTensor &tensor)
    -> decltype(tensor.data()) {
  return tensor.data();
}


enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void reduce_step(__gm__ float* v1, __gm__ float* v2, __gm__ float* v3, __gm__ int32_t* v4, __gm__ int64_t* v5, __gm__ int64_t* v6) {
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  const int32_t v7 = -17;
  // pto: %c0_i64
  const int64_t v8 = 0;
  // pto: %c32768_i64
  const int64_t v9 = 32768;
  // pto: %c1_index
  const int64_t v10 = 1;
  // pto: %c65536_index
  const int64_t v11 = 65536;
  // pto: %c2_index
  const int64_t v12 = 2;
  // pto: %c0_index
  const int64_t v13 = 0;
  // pto: %c8192_index
  const int64_t v14 = 8192;
  // pto: %c32_i64
  const int64_t v15 = 32;
  // pto: %c4_index
  const int64_t v16 = 4;
  // pto: %c4_i64
  const int64_t v17 = 4;
  // pto: %c1_i32
  const int32_t v18 = 1;
  // pto: %c4096_index
  const int64_t v19 = 4096;
  // pto: %inp__ssa_v0_view
  const int64_t v20 = 1;
  // pto: %inp__ssa_v0_view
  const int64_t v21 = 1;
  // pto: %inp__ssa_v0_view
  const int64_t v22 = 1;
  // pto: %inp__ssa_v0_view
  int64_t v23 = v10 * v11;
  // pto: %inp__ssa_v0_view
  int64_t v24 = v22 * v23;
  // pto: %inp__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v25 = pto::Shape<1, 1, 1, -1, -1>(v20, v21, v22, v10, v11);
  // pto: %inp__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v26 = pto::Stride<-1, -1, -1, -1, -1>(v21 * v24, v24, v23, v11, v10);
  // pto: %inp__ssa_v0_view
  GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v27 = GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v1, v25, v26);
  // pto: %out__ssa_v0_view
  const int64_t v28 = 1;
  // pto: %out__ssa_v0_view
  const int64_t v29 = 1;
  // pto: %out__ssa_v0_view
  const int64_t v30 = 1;
  // pto: %out__ssa_v0_view
  int64_t v31 = v10 * v11;
  // pto: %out__ssa_v0_view
  int64_t v32 = v30 * v31;
  // pto: %out__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v33 = pto::Shape<1, 1, 1, -1, -1>(v28, v29, v30, v10, v11);
  // pto: %out__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v34 = pto::Stride<-1, -1, -1, -1, -1>(v29 * v32, v32, v31, v11, v10);
  // pto: %out__ssa_v0_view
  GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v35 = GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v2, v33, v34);
  // pto: %data__ssa_v0_view
  const int64_t v36 = 1;
  // pto: %data__ssa_v0_view
  const int64_t v37 = 1;
  // pto: %data__ssa_v0_view
  const int64_t v38 = 1;
  // pto: %data__ssa_v0_view
  int64_t v39 = v10 * v11;
  // pto: %data__ssa_v0_view
  int64_t v40 = v38 * v39;
  // pto: %data__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v41 = pto::Shape<1, 1, 1, -1, -1>(v36, v37, v38, v10, v11);
  // pto: %data__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v42 = pto::Stride<-1, -1, -1, -1, -1>(v37 * v40, v40, v39, v11, v10);
  // pto: %data__ssa_v0_view
  GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v43 = GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v3, v41, v42);
  // pto: %data_v1__if_res_tmp_v17
  Tile<TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null> v44 = Tile<TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null>(v10, v19);
  // pto: %data_v1__if_res_tmp_v17
  uint64_t v45 = (uint64_t) v8;
  TASSIGN(v44, v45);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID4);
  for (int64_t v46 = v13; v46 < v11; v46 += v14) {
    // pto: %0
    ;
    int64_t v47 = (int64_t) ((uint64_t) v11 - (uint64_t) v46);
    // pto: %1
    ;
    int64_t v48 = v47 < v14 ? v47 : v14;
    // pto: %local__ssa_v0
    ;
    Tile<TileType::Vec, float, 1, 8192, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v49 = Tile<TileType::Vec, float, 1, 8192, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v48);
    // pto: %local__ssa_v0
    ;
    uint64_t v50 = (uint64_t) v8;
    TASSIGN(v49, v50);
    // pto: %2
    ;
    int64_t v51 = v46 < v13 ? v13 : v46;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v52 = 0;
    // pto: %inp__ssa_v0_pview
    ;
    __gm__ float* v53 = PTOAS__GLOBAL_TENSOR_DATA(v27);
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v54 = 1;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v55 = 1;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v56 = 1;
    // pto: %inp__ssa_v0_pview
    ;
    int64_t v57 = v10 * v11;
    // pto: %inp__ssa_v0_pview
    ;
    int64_t v58 = v56 * v57;
    // pto: %inp__ssa_v0_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v59 = pto::Shape<1, 1, 1, 1, -1>(v54, v55, v56, v10, v48);
    // pto: %inp__ssa_v0_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v60 = pto::Stride<-1, -1, -1, -1, -1>(v55 * v58, v58, v57, v11, v10);
    // pto: %inp__ssa_v0_pview
    ;
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v61 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v53 + (v52 + v13 * v11 + v51 * v10), v59, v60);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    TLOAD(v49, v61);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %data_iter_pview
    ;
    const int64_t v62 = 0;
    // pto: %data_iter_pview
    ;
    __gm__ float* v63 = PTOAS__GLOBAL_TENSOR_DATA(v43);
    // pto: %data_iter_pview
    ;
    const int64_t v64 = 1;
    // pto: %data_iter_pview
    ;
    const int64_t v65 = 1;
    // pto: %data_iter_pview
    ;
    const int64_t v66 = 1;
    // pto: %data_iter_pview
    ;
    int64_t v67 = v10 * v11;
    // pto: %data_iter_pview
    ;
    int64_t v68 = v66 * v67;
    // pto: %data_iter_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v69 = pto::Shape<1, 1, 1, 1, -1>(v64, v65, v66, v10, v48);
    // pto: %data_iter_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v70 = pto::Stride<-1, -1, -1, -1, -1>(v65 * v68, v68, v67, v11, v10);
    // pto: %data_iter_pview
    ;
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v71 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v63 + (v62 + v13 * v11 + v51 * v10), v69, v70);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v71, v49);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    // pto: %4
    ;
    pto::Shape<1, 1, 1, 1, 65536> v72 = pto::Shape<1, 1, 1, 1, 65536>();
    // pto: %4
    ;
    pto::Stride<65536, 65536, 65536, 65536, 1> v73 = pto::Stride<65536, 65536, 65536, 65536, 1>();
    // pto: %4
    ;
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 65536>, pto::Stride<65536, 65536, 65536, 65536, 1>, pto::Layout::ND> v74 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 65536>, pto::Stride<65536, 65536, 65536, 65536, 1>, pto::Layout::ND>((__gm__ float*) v3, v72, v73);
    __gm__ float* v75 = PTOAS__GLOBAL_TENSOR_DATA(v74);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v75);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
  }
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
  // pto: %5
  int64_t v76 = (v5)[v12];
  // pto: %6, %data_v1__nranks_tmp_v1, %7
  int64_t v77 = (int64_t) ((int32_t) (int64_t) ((uint64_t) v76 >> (uint64_t) v15));
  // pto: %data_v1__my_rank_tmp_v3
  int32_t v78 = (int32_t) v76;
  for (int64_t v79 = v13; v79 < v77; v79 += v10) {
    // pto: %9
    ;
    int64_t v80 = (int64_t) v78;
    // pto: %10
    ;
    if (v79 != v80) {
      // pto: %11
      ;
      int64_t v81 = (v6)[v12];
      // pto: %12, %13, %14, %15
      ;
      int64_t v82 = (v6)[(int64_t) ((uint64_t) ((int64_t) (int32_t) v81) + (uint64_t) v16)];
      // pto: %16, %17
      ;
      int64_t v83 = (v6)[(int64_t) ((uint64_t) v79 + (uint64_t) v16)];
      // pto: %23
      ;
      int64_t v84 = v80 < v13 ? v13 : v80;
      // pto: %signal__ssa_v0_peer_pview
      ;
      const int64_t v85 = 0;
      // pto: %signal__ssa_v0_peer_pview
      ;
      pto::Shape<1, 1, 1, 1, 1> v86 = pto::Shape<1, 1, 1, 1, 1>();
      // pto: %signal__ssa_v0_peer_pview
      ;
      pto::Stride<1, 1, 1, 1, 2> v87 = pto::Stride<1, 1, 1, 1, 2>();
      // pto: %18, %19, %21, %signal__ssa_v0_peer_pview
      ;
      GlobalTensor<int32_t, pto::Shape<1, 1, 1, 1, 1>, pto::Stride<1, 1, 1, 1, 2>, pto::Layout::DN> v88 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 1, 1>, pto::Stride<1, 1, 1, 1, 2>, pto::Layout::DN>((v4 + (int64_t) ((uint64_t) v83 - (uint64_t) v82) / v17) + (v85 + v84), v86, v87);
      pipe_barrier(PIPE_V);
      pto::comm::NotifyOp v89 = pto::comm::NotifyOp::AtomicAdd;
      pto::comm::TNOTIFY(v88, v18, v89);
    };
  }
  for (int64_t v90 = v13; v90 < v77; v90 += v10) {
    // pto: %24, %25
    ;
    if (v90 != (int64_t) v78) {
      // pto: %26
      ;
      int64_t v91 = v90 < v13 ? v13 : v90;
      // pto: %signal__ssa_v0_local_pview
      ;
      const int64_t v92 = 0;
      // pto: %signal__ssa_v0_local_pview
      ;
      pto::Shape<1, 1, 1, 1, 1> v93 = pto::Shape<1, 1, 1, 1, 1>();
      // pto: %signal__ssa_v0_local_pview
      ;
      pto::Stride<1, 1, 1, 1, 2> v94 = pto::Stride<1, 1, 1, 1, 2>();
      // pto: %signal__ssa_v0_local_pview
      ;
      GlobalTensor<int32_t, pto::Shape<1, 1, 1, 1, 1>, pto::Stride<1, 1, 1, 1, 2>, pto::Layout::DN> v95 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 1, 1>, pto::Stride<1, 1, 1, 1, 2>, pto::Layout::DN>((__gm__ int32_t*) v4 + (v92 + v91), v93, v94);
      pto::comm::WaitCmp v96 = pto::comm::WaitCmp::GE;
      pto::comm::TWAIT(v95, v18, v96);
    };
  }
  dcci((__gm__ void*)0, cache_line_t::ENTIRE_DATA_CACHE);
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
  for (int64_t v97 = v13; v97 < v11; v97 += v19) {
    // pto: %27
    ;
    int64_t v98 = (int64_t) ((uint64_t) v11 - (uint64_t) v97);
    // pto: %28
    ;
    int64_t v99 = v98 < v19 ? v98 : v19;
    // pto: %data_v1__acc_loaded_tmp_v10
    ;
    Tile<TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v100 = Tile<TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v99);
    // pto: %data_v1__acc_loaded_tmp_v10
    ;
    uint64_t v101 = (uint64_t) v8;
    TASSIGN(v100, v101);
    // pto: %29
    ;
    int64_t v102 = v97 < v13 ? v13 : v97;
    // pto: %data_v1__target_2d_tmp_v4_pview
    ;
    const int64_t v103 = 0;
    // pto: %data_v1__target_2d_tmp_v4_pview
    ;
    __gm__ float* v104 = PTOAS__GLOBAL_TENSOR_DATA(v43);
    // pto: %data_v1__target_2d_tmp_v4_pview
    ;
    const int64_t v105 = 1;
    // pto: %data_v1__target_2d_tmp_v4_pview
    ;
    const int64_t v106 = 1;
    // pto: %data_v1__target_2d_tmp_v4_pview
    ;
    const int64_t v107 = 1;
    // pto: %data_v1__target_2d_tmp_v4_pview
    ;
    int64_t v108 = v10 * v11;
    // pto: %data_v1__target_2d_tmp_v4_pview
    ;
    int64_t v109 = v107 * v108;
    // pto: %data_v1__target_2d_tmp_v4_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v110 = pto::Shape<1, 1, 1, 1, -1>(v105, v106, v107, v10, v99);
    // pto: %data_v1__target_2d_tmp_v4_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v111 = pto::Stride<-1, -1, -1, -1, -1>(v106 * v109, v109, v108, v11, v10);
    // pto: %data_v1__target_2d_tmp_v4_pview
    ;
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v112 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v104 + (v103 + v13 * v11 + v102 * v10), v110, v111);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
    TLOAD(v100, v112);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    // pto: %data_v1__acc_initial_tmp_v11
    ;
    Tile<TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null> v113 = Tile<TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null>(v10, v19);
    // pto: %data_v1__acc_initial_tmp_v11
    ;
    uint64_t v114 = (uint64_t) v8;
    TASSIGN(v113, v114);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    TFILLPAD<pto::TFillPadMode::InPlace>(v113, v100);
    for (int64_t v115 = v13; v115 < v77; v115 += v10) {
      // pto: %32, %33
      ;
      if (v115 != (int64_t) v78) {
        // pto: %data_v1__recv_loaded_tmp_v14
        ;
        Tile<TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v116 = Tile<TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v99);
        // pto: %data_v1__recv_loaded_tmp_v14
        ;
        uint64_t v117 = (uint64_t) v9;
        TASSIGN(v116, v117);
        // pto: %36
        ;
        int64_t v118 = (v5)[v12];
        // pto: %37, %38, %39, %40
        ;
        int64_t v119 = (v5)[(int64_t) ((uint64_t) ((int64_t) (int32_t) v118) + (uint64_t) v16)];
        // pto: %41, %42
        ;
        int64_t v120 = (v5)[(int64_t) ((uint64_t) v115 + (uint64_t) v16)];
        // pto: %47
        ;
        const int64_t v121 = 1;
        // pto: %47
        ;
        const int64_t v122 = 1;
        // pto: %47
        ;
        const int64_t v123 = 1;
        // pto: %47
        ;
        int64_t v124 = v10 * v11;
        // pto: %47
        ;
        int64_t v125 = v123 * v124;
        // pto: %47
        ;
        pto::Shape<1, 1, 1, -1, -1> v126 = pto::Shape<1, 1, 1, -1, -1>(v121, v122, v123, v10, v11);
        // pto: %47
        ;
        pto::Stride<-1, -1, -1, -1, -1> v127 = pto::Stride<-1, -1, -1, -1, -1>(v122 * v125, v125, v124, v11, v10);
        // pto: %43, %44, %46, %47
        ;
        GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v128 = GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v3 + (int64_t) ((uint64_t) v120 - (uint64_t) v119) / v17, v126, v127);
        // pto: %data_v1__target_2d_tmp_v4_peer_pview
        ;
        const int64_t v129 = 0;
        // pto: %data_v1__target_2d_tmp_v4_peer_pview
        ;
        __gm__ float* v130 = PTOAS__GLOBAL_TENSOR_DATA(v128);
        // pto: %data_v1__target_2d_tmp_v4_peer_pview
        ;
        const int64_t v131 = 1;
        // pto: %data_v1__target_2d_tmp_v4_peer_pview
        ;
        const int64_t v132 = 1;
        // pto: %data_v1__target_2d_tmp_v4_peer_pview
        ;
        const int64_t v133 = 1;
        // pto: %data_v1__target_2d_tmp_v4_peer_pview
        ;
        int64_t v134 = v10 * v11;
        // pto: %data_v1__target_2d_tmp_v4_peer_pview
        ;
        int64_t v135 = v133 * v134;
        // pto: %data_v1__target_2d_tmp_v4_peer_pview
        ;
        pto::Shape<1, 1, 1, 1, -1> v136 = pto::Shape<1, 1, 1, 1, -1>(v131, v132, v133, v10, v99);
        // pto: %data_v1__target_2d_tmp_v4_peer_pview
        ;
        pto::Stride<-1, -1, -1, -1, -1> v137 = pto::Stride<-1, -1, -1, -1, -1>(v132 * v135, v135, v134, v11, v10);
        // pto: %data_v1__target_2d_tmp_v4_peer_pview
        ;
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v138 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v130 + (v129 + v13 * v11 + v102 * v10), v136, v137);
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        TLOAD(v116, v138);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        // pto: %data_v1__recv_tmp_v15
        ;
        Tile<TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null> v139 = Tile<TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null>(v10, v19);
        // pto: %data_v1__recv_tmp_v15
        ;
        uint64_t v140 = (uint64_t) v9;
        TASSIGN(v139, v140);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        TFILLPAD<pto::TFillPadMode::InPlace>(v139, v116);
        // pto: %data_v1__acc_next_tmp_v16
        ;
        Tile<TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null> v141 = Tile<TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null>(v10, v19);
        // pto: %data_v1__acc_next_tmp_v16
        ;
        uint64_t v142 = (uint64_t) v8;
        TASSIGN(v141, v142);
        pipe_barrier(PIPE_V);
        TADD(v141, v113, v139);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
      };
    };
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    // pto: %51, %52, %53
    ;
    int32_t v143 = (int32_t) ((int64_t) (uint64_t) (v97 / v19) + (uint64_t) v12);
    for (int64_t v144 = v13; v144 < v77; v144 += v10) {
      // pto: %54
      ;
      int64_t v145 = (int64_t) v78;
      // pto: %55
      ;
      if (v144 != v145) {
        // pto: %56
        ;
        int64_t v146 = (v6)[v12];
        // pto: %57, %58, %59, %60
        ;
        int64_t v147 = (v6)[(int64_t) ((uint64_t) ((int64_t) (int32_t) v146) + (uint64_t) v16)];
        // pto: %61, %62
        ;
        int64_t v148 = (v6)[(int64_t) ((uint64_t) v144 + (uint64_t) v16)];
        // pto: %69
        ;
        int64_t v149 = v145 < v13 ? v13 : v145;
        // pto: %70
        ;
        const int64_t v150 = 0;
        // pto: %70
        ;
        pto::Shape<1, 1, 1, 1, 1> v151 = pto::Shape<1, 1, 1, 1, 1>();
        // pto: %70
        ;
        pto::Stride<1, 1, 1, 1, 2> v152 = pto::Stride<1, 1, 1, 1, 2>();
        // pto: %63, %64, %66, %70
        ;
        GlobalTensor<int32_t, pto::Shape<1, 1, 1, 1, 1>, pto::Stride<1, 1, 1, 1, 2>, pto::Layout::DN> v153 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 1, 1>, pto::Stride<1, 1, 1, 1, 2>, pto::Layout::DN>((v4 + (int64_t) ((uint64_t) v148 - (uint64_t) v147) / v17) + (v150 + v149), v151, v152);
        pipe_barrier(PIPE_V);
        pto::comm::NotifyOp v154 = pto::comm::NotifyOp::AtomicAdd;
        pto::comm::TNOTIFY(v153, v18, v154);
      };
    };
    for (int64_t v155 = v13; v155 < v77; v155 += v10) {
      // pto: %71, %72
      ;
      if (v155 != (int64_t) v78) {
        // pto: %73
        ;
        int64_t v156 = v155 < v13 ? v13 : v155;
        // pto: %74
        ;
        const int64_t v157 = 0;
        // pto: %74
        ;
        pto::Shape<1, 1, 1, 1, 1> v158 = pto::Shape<1, 1, 1, 1, 1>();
        // pto: %74
        ;
        pto::Stride<1, 1, 1, 1, 2> v159 = pto::Stride<1, 1, 1, 1, 2>();
        // pto: %74
        ;
        GlobalTensor<int32_t, pto::Shape<1, 1, 1, 1, 1>, pto::Stride<1, 1, 1, 1, 2>, pto::Layout::DN> v160 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 1, 1>, pto::Stride<1, 1, 1, 1, 2>, pto::Layout::DN>((__gm__ int32_t*) v4 + (v157 + v156), v158, v159);
        pto::comm::WaitCmp v161 = pto::comm::WaitCmp::GE;
        pto::comm::TWAIT(v160, v143, v161);
      };
    };
    dcci((__gm__ void*)0, cache_line_t::ENTIRE_DATA_CACHE);
    v113.SetValidShape(v10, v99);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    TSTORE(v112, v113);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
    // pto: %81
    ;
    pto::Shape<1, 1, 1, 1, 65536> v162 = pto::Shape<1, 1, 1, 1, 65536>();
    // pto: %81
    ;
    pto::Stride<65536, 65536, 65536, 65536, 1> v163 = pto::Stride<65536, 65536, 65536, 65536, 1>();
    // pto: %81
    ;
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 65536>, pto::Stride<65536, 65536, 65536, 65536, 1>, pto::Layout::ND> v164 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 65536>, pto::Stride<65536, 65536, 65536, 65536, 1>, pto::Layout::ND>((__gm__ float*) v3, v162, v163);
    __gm__ float* v165 = PTOAS__GLOBAL_TENSOR_DATA(v164);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v165);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
  }
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
  for (int64_t v166 = v13; v166 < v77; v166 += v10) {
    // pto: %83
    ;
    int64_t v167 = (int64_t) v78;
    // pto: %84
    ;
    if (v166 != v167) {
      // pto: %86
      ;
      int64_t v168 = (v6)[v12];
      // pto: %87, %88, %89, %90
      ;
      int64_t v169 = (v6)[(int64_t) ((uint64_t) ((int64_t) (int32_t) v168) + (uint64_t) v16)];
      // pto: %91, %92
      ;
      int64_t v170 = (v6)[(int64_t) ((uint64_t) v167 + (uint64_t) v16)];
      // pto: %98
      ;
      int64_t v171 = v166 < v13 ? v13 : v166;
      // pto: %99
      ;
      const int64_t v172 = 0;
      // pto: %99
      ;
      pto::Shape<1, 1, 1, 1, 1> v173 = pto::Shape<1, 1, 1, 1, 1>();
      // pto: %99
      ;
      pto::Stride<1, 1, 1, 1, 2> v174 = pto::Stride<1, 1, 1, 1, 2>();
      // pto: %93, %94, %96, %99
      ;
      GlobalTensor<int32_t, pto::Shape<1, 1, 1, 1, 1>, pto::Stride<1, 1, 1, 1, 2>, pto::Layout::DN> v175 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 1, 1>, pto::Stride<1, 1, 1, 1, 2>, pto::Layout::DN>((v4 + (int64_t) ((uint64_t) v170 - (uint64_t) v169) / v17) + (v172 + v171), v173, v174);
      pipe_barrier(PIPE_V);
      pto::comm::NotifyOp v176 = pto::comm::NotifyOp::AtomicAdd;
      pto::comm::TNOTIFY(v175, v7, v176);
    };
  }
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
  for (int64_t v177 = v13; v177 < v11; v177 += v14) {
    // pto: %103
    ;
    int64_t v178 = (int64_t) ((uint64_t) v11 - (uint64_t) v177);
    // pto: %104
    ;
    int64_t v179 = v178 < v14 ? v178 : v14;
    // pto: %acc__ssa_v0
    ;
    Tile<TileType::Vec, float, 1, 8192, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v180 = Tile<TileType::Vec, float, 1, 8192, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v179);
    // pto: %acc__ssa_v0
    ;
    uint64_t v181 = (uint64_t) v8;
    TASSIGN(v180, v181);
    // pto: %105
    ;
    int64_t v182 = v177 < v13 ? v13 : v177;
    // pto: %data_v1__ssa_v0_pview
    ;
    const int64_t v183 = 0;
    // pto: %data_v1__ssa_v0_pview
    ;
    __gm__ float* v184 = PTOAS__GLOBAL_TENSOR_DATA(v43);
    // pto: %data_v1__ssa_v0_pview
    ;
    const int64_t v185 = 1;
    // pto: %data_v1__ssa_v0_pview
    ;
    const int64_t v186 = 1;
    // pto: %data_v1__ssa_v0_pview
    ;
    const int64_t v187 = 1;
    // pto: %data_v1__ssa_v0_pview
    ;
    int64_t v188 = v10 * v11;
    // pto: %data_v1__ssa_v0_pview
    ;
    int64_t v189 = v187 * v188;
    // pto: %data_v1__ssa_v0_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v190 = pto::Shape<1, 1, 1, 1, -1>(v185, v186, v187, v10, v179);
    // pto: %data_v1__ssa_v0_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v191 = pto::Stride<-1, -1, -1, -1, -1>(v186 * v189, v189, v188, v11, v10);
    // pto: %data_v1__ssa_v0_pview
    ;
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v192 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v184 + (v183 + v13 * v11 + v182 * v10), v190, v191);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID4);
    TLOAD(v180, v192);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID1);
    // pto: %out_iter_pview
    ;
    const int64_t v193 = 0;
    // pto: %out_iter_pview
    ;
    __gm__ float* v194 = PTOAS__GLOBAL_TENSOR_DATA(v35);
    // pto: %out_iter_pview
    ;
    const int64_t v195 = 1;
    // pto: %out_iter_pview
    ;
    const int64_t v196 = 1;
    // pto: %out_iter_pview
    ;
    const int64_t v197 = 1;
    // pto: %out_iter_pview
    ;
    int64_t v198 = v10 * v11;
    // pto: %out_iter_pview
    ;
    int64_t v199 = v197 * v198;
    // pto: %out_iter_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v200 = pto::Shape<1, 1, 1, 1, -1>(v195, v196, v197, v10, v179);
    // pto: %out_iter_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v201 = pto::Stride<-1, -1, -1, -1, -1>(v196 * v199, v199, v198, v11, v10);
    // pto: %out_iter_pview
    ;
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v202 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v194 + (v193 + v13 * v11 + v182 * v10), v200, v201);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID1);
    TSTORE(v202, v180);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID4);
  }
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID4);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM) && !defined(__COSTMODEL)
    // Reset AI Core atomic mode inherited from a prior kernel.
    set_atomic_none();
#endif

    // Unpack tensor: inp__ssa_v0
    __gm__ TaskTensor* inp__ssa_v0_tensor = reinterpret_cast<__gm__ TaskTensor*>(args[0]);
    __gm__ float* inp__ssa_v0 = reinterpret_cast<__gm__ float*>(inp__ssa_v0_tensor->buffer.addr) + inp__ssa_v0_tensor->start_offset;

    // Unpack tensor: out__ssa_v0
    __gm__ TaskTensor* out__ssa_v0_tensor = reinterpret_cast<__gm__ TaskTensor*>(args[1]);
    __gm__ float* out__ssa_v0 = reinterpret_cast<__gm__ float*>(out__ssa_v0_tensor->buffer.addr) + out__ssa_v0_tensor->start_offset;

    // Unpack tensor: data__ssa_v0
    __gm__ TaskTensor* data__ssa_v0_tensor = reinterpret_cast<__gm__ TaskTensor*>(args[2]);
    __gm__ float* data__ssa_v0 = reinterpret_cast<__gm__ float*>(data__ssa_v0_tensor->buffer.addr) + data__ssa_v0_tensor->start_offset;

    // Unpack tensor: signal__ssa_v0
    __gm__ TaskTensor* signal__ssa_v0_tensor = reinterpret_cast<__gm__ TaskTensor*>(args[3]);
    __gm__ int32_t* signal__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(signal__ssa_v0_tensor->buffer.addr) + signal__ssa_v0_tensor->start_offset;

    // Unpack CommContext: data_ctx
    __gm__ int64_t* data_ctx = reinterpret_cast<__gm__ int64_t*>(args[4]);

    // Unpack CommContext: signal_ctx
    __gm__ int64_t* signal_ctx = reinterpret_cast<__gm__ int64_t*>(args[5]);

    // Forward to ptoas-generated function
    reduce_step(inp__ssa_v0, out__ssa_v0, data__ssa_v0, signal__ssa_v0, data_ctx, signal_ctx);
}
