// Kernel Function: stage_step
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"



using namespace pto;


// --- ptoas-generated code ---

template <typename Tensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(Tensor &tensor)
    -> decltype(tensor.data()) {
  return tensor.data();
}


enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void stage_step(__gm__ int8_t* v1, __gm__ int32_t* v2, __gm__ int8_t* v3, __gm__ int32_t* v4, __gm__ int64_t* v5, __gm__ int64_t* v6) {
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  // pto: %c0_i64
  const int64_t v7 = 0;
  // pto: %c4_index
  const int64_t v8 = 4;
  // pto: %c524288_index
  const int64_t v9 = 524288;
  // pto: %c1_index
  const int64_t v10 = 1;
  // pto: %c0_index
  const int64_t v11 = 0;
  // pto: %c16384_index
  const int64_t v12 = 16384;
  // pto: %c32768_index
  const int64_t v13 = 32768;
  // pto: %c49152_index
  const int64_t v14 = 49152;
  // pto: %c65536_index
  const int64_t v15 = 65536;
  // pto: %c81920_index
  const int64_t v16 = 81920;
  // pto: %c98304_index
  const int64_t v17 = 98304;
  // pto: %c114688_index
  const int64_t v18 = 114688;
  // pto: %c131072_index
  const int64_t v19 = 131072;
  // pto: %c147456_index
  const int64_t v20 = 147456;
  // pto: %c163840_index
  const int64_t v21 = 163840;
  // pto: %c180224_index
  const int64_t v22 = 180224;
  // pto: %c196608_index
  const int64_t v23 = 196608;
  // pto: %c212992_index
  const int64_t v24 = 212992;
  // pto: %c229376_index
  const int64_t v25 = 229376;
  // pto: %c245760_index
  const int64_t v26 = 245760;
  // pto: %c262144_index
  const int64_t v27 = 262144;
  // pto: %c278528_index
  const int64_t v28 = 278528;
  // pto: %c294912_index
  const int64_t v29 = 294912;
  // pto: %c311296_index
  const int64_t v30 = 311296;
  // pto: %c327680_index
  const int64_t v31 = 327680;
  // pto: %c344064_index
  const int64_t v32 = 344064;
  // pto: %c360448_index
  const int64_t v33 = 360448;
  // pto: %c376832_index
  const int64_t v34 = 376832;
  // pto: %c393216_index
  const int64_t v35 = 393216;
  // pto: %c409600_index
  const int64_t v36 = 409600;
  // pto: %c425984_index
  const int64_t v37 = 425984;
  // pto: %c442368_index
  const int64_t v38 = 442368;
  // pto: %c458752_index
  const int64_t v39 = 458752;
  // pto: %c475136_index
  const int64_t v40 = 475136;
  // pto: %c491520_index
  const int64_t v41 = 491520;
  // pto: %c507904_index
  const int64_t v42 = 507904;
  // pto: %inp__ssa_v0_view
  const int64_t v43 = 1;
  // pto: %inp__ssa_v0_view
  const int64_t v44 = 1;
  // pto: %inp__ssa_v0_view
  const int64_t v45 = 1;
  // pto: %inp__ssa_v0_view
  int64_t v46 = v8 * v9;
  // pto: %inp__ssa_v0_view
  int64_t v47 = v45 * v46;
  // pto: %inp__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v48 = pto::Shape<1, 1, 1, -1, -1>(v43, v44, v45, v8, v9);
  // pto: %inp__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v49 = pto::Stride<-1, -1, -1, -1, -1>(v44 * v47, v47, v46, v9, v10);
  // pto: %inp__ssa_v0_view
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v50 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v1, v48, v49);
  // pto: %stage__ssa_v0_view
  const int64_t v51 = 1;
  // pto: %stage__ssa_v0_view
  const int64_t v52 = 1;
  // pto: %stage__ssa_v0_view
  const int64_t v53 = 1;
  // pto: %stage__ssa_v0_view
  int64_t v54 = v8 * v9;
  // pto: %stage__ssa_v0_view
  int64_t v55 = v53 * v54;
  // pto: %stage__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v56 = pto::Shape<1, 1, 1, -1, -1>(v51, v52, v53, v8, v9);
  // pto: %stage__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v57 = pto::Stride<-1, -1, -1, -1, -1>(v52 * v55, v55, v54, v9, v10);
  // pto: %stage__ssa_v0_view
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v58 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v3, v56, v57);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  for (int64_t v59 = v11; v59 < v8; v59 += v10) {
    // pto: %tile__ssa_v0
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v60 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v0
    ;
    uint64_t v61 = (uint64_t) v7;
    TASSIGN(v60, v61);
    // pto: %0
    ;
    int64_t v62 = v59 < v11 ? v11 : v59;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v63 = 0;
    // pto: %inp__ssa_v0_pview
    ;
    __gm__ int8_t* v64 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v65 = 1;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v66 = 1;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v67 = 1;
    // pto: %inp__ssa_v0_pview
    ;
    int64_t v68 = v10 * v9;
    // pto: %inp__ssa_v0_pview
    ;
    int64_t v69 = v67 * v68;
    // pto: %inp__ssa_v0_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v70 = pto::Shape<1, 1, 1, 1, -1>(v65, v66, v67, v10, v12);
    // pto: %inp__ssa_v0_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v71 = pto::Stride<-1, -1, -1, -1, -1>(v66 * v69, v69, v68, v9, v10);
    // pto: %inp__ssa_v0_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v72 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v64 + (v63 + v62 * v9 + v11 * v10), v70, v71);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    TLOAD(v60, v72);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v73 = 0;
    // pto: %stage__iter_v1_pview
    ;
    __gm__ int8_t* v74 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v75 = 1;
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v76 = 1;
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v77 = 1;
    // pto: %stage__iter_v1_pview
    ;
    int64_t v78 = v10 * v9;
    // pto: %stage__iter_v1_pview
    ;
    int64_t v79 = v77 * v78;
    // pto: %stage__iter_v1_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v80 = pto::Shape<1, 1, 1, 1, -1>(v75, v76, v77, v10, v12);
    // pto: %stage__iter_v1_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v81 = pto::Stride<-1, -1, -1, -1, -1>(v76 * v79, v79, v78, v9, v10);
    // pto: %stage__iter_v1_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v82 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v74 + (v73 + v62 * v9 + v11 * v10), v80, v81);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v82, v60);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    // pto: %2
    ;
    pto::Shape<1, 1, 1, 4, 524288> v83 = pto::Shape<1, 1, 1, 4, 524288>();
    // pto: %2
    ;
    pto::Stride<2097152, 2097152, 2097152, 524288, 1> v84 = pto::Stride<2097152, 2097152, 2097152, 524288, 1>();
    // pto: %2
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 4, 524288>, pto::Stride<2097152, 2097152, 2097152, 524288, 1>, pto::Layout::ND> v85 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 4, 524288>, pto::Stride<2097152, 2097152, 2097152, 524288, 1>, pto::Layout::ND>((__gm__ int8_t*) v3, v83, v84);
    __gm__ int8_t* v86 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v86);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v1
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v87 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v1
    ;
    uint64_t v88 = (uint64_t) v7;
    TASSIGN(v87, v88);
    // pto: %4
    ;
    const int64_t v89 = 0;
    // pto: %4
    ;
    __gm__ int8_t* v90 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %4
    ;
    const int64_t v91 = 1;
    // pto: %4
    ;
    const int64_t v92 = 1;
    // pto: %4
    ;
    const int64_t v93 = 1;
    // pto: %4
    ;
    int64_t v94 = v10 * v9;
    // pto: %4
    ;
    int64_t v95 = v93 * v94;
    // pto: %4
    ;
    pto::Shape<1, 1, 1, 1, -1> v96 = pto::Shape<1, 1, 1, 1, -1>(v91, v92, v93, v10, v12);
    // pto: %4
    ;
    pto::Stride<-1, -1, -1, -1, -1> v97 = pto::Stride<-1, -1, -1, -1, -1>(v92 * v95, v95, v94, v9, v10);
    // pto: %4
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v98 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v90 + (v89 + v62 * v9 + v12 * v10), v96, v97);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v87, v98);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID1);
    // pto: %stage__ssa_v3_pview
    ;
    const int64_t v99 = 0;
    // pto: %stage__ssa_v3_pview
    ;
    __gm__ int8_t* v100 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v3_pview
    ;
    const int64_t v101 = 1;
    // pto: %stage__ssa_v3_pview
    ;
    const int64_t v102 = 1;
    // pto: %stage__ssa_v3_pview
    ;
    const int64_t v103 = 1;
    // pto: %stage__ssa_v3_pview
    ;
    int64_t v104 = v10 * v9;
    // pto: %stage__ssa_v3_pview
    ;
    int64_t v105 = v103 * v104;
    // pto: %stage__ssa_v3_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v106 = pto::Shape<1, 1, 1, 1, -1>(v101, v102, v103, v10, v12);
    // pto: %stage__ssa_v3_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v107 = pto::Stride<-1, -1, -1, -1, -1>(v102 * v105, v105, v104, v9, v10);
    // pto: %stage__ssa_v3_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v108 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v100 + (v99 + v62 * v9 + v12 * v10), v106, v107);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID1);
    TSTORE(v108, v87);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
    __gm__ int8_t* v109 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v109);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v2
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v110 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v2
    ;
    uint64_t v111 = (uint64_t) v7;
    TASSIGN(v110, v111);
    // pto: %8
    ;
    const int64_t v112 = 0;
    // pto: %8
    ;
    __gm__ int8_t* v113 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %8
    ;
    const int64_t v114 = 1;
    // pto: %8
    ;
    const int64_t v115 = 1;
    // pto: %8
    ;
    const int64_t v116 = 1;
    // pto: %8
    ;
    int64_t v117 = v10 * v9;
    // pto: %8
    ;
    int64_t v118 = v116 * v117;
    // pto: %8
    ;
    pto::Shape<1, 1, 1, 1, -1> v119 = pto::Shape<1, 1, 1, 1, -1>(v114, v115, v116, v10, v12);
    // pto: %8
    ;
    pto::Stride<-1, -1, -1, -1, -1> v120 = pto::Stride<-1, -1, -1, -1, -1>(v115 * v118, v118, v117, v9, v10);
    // pto: %8
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v121 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v113 + (v112 + v62 * v9 + v13 * v10), v119, v120);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
    TLOAD(v110, v121);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID2);
    // pto: %stage__ssa_v4_pview
    ;
    const int64_t v122 = 0;
    // pto: %stage__ssa_v4_pview
    ;
    __gm__ int8_t* v123 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v4_pview
    ;
    const int64_t v124 = 1;
    // pto: %stage__ssa_v4_pview
    ;
    const int64_t v125 = 1;
    // pto: %stage__ssa_v4_pview
    ;
    const int64_t v126 = 1;
    // pto: %stage__ssa_v4_pview
    ;
    int64_t v127 = v10 * v9;
    // pto: %stage__ssa_v4_pview
    ;
    int64_t v128 = v126 * v127;
    // pto: %stage__ssa_v4_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v129 = pto::Shape<1, 1, 1, 1, -1>(v124, v125, v126, v10, v12);
    // pto: %stage__ssa_v4_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v130 = pto::Stride<-1, -1, -1, -1, -1>(v125 * v128, v128, v127, v9, v10);
    // pto: %stage__ssa_v4_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v131 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v123 + (v122 + v62 * v9 + v13 * v10), v129, v130);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID2);
    TSTORE(v131, v110);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
    __gm__ int8_t* v132 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v132);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v3
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v133 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v3
    ;
    uint64_t v134 = (uint64_t) v7;
    TASSIGN(v133, v134);
    // pto: %12
    ;
    const int64_t v135 = 0;
    // pto: %12
    ;
    __gm__ int8_t* v136 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %12
    ;
    const int64_t v137 = 1;
    // pto: %12
    ;
    const int64_t v138 = 1;
    // pto: %12
    ;
    const int64_t v139 = 1;
    // pto: %12
    ;
    int64_t v140 = v10 * v9;
    // pto: %12
    ;
    int64_t v141 = v139 * v140;
    // pto: %12
    ;
    pto::Shape<1, 1, 1, 1, -1> v142 = pto::Shape<1, 1, 1, 1, -1>(v137, v138, v139, v10, v12);
    // pto: %12
    ;
    pto::Stride<-1, -1, -1, -1, -1> v143 = pto::Stride<-1, -1, -1, -1, -1>(v138 * v141, v141, v140, v9, v10);
    // pto: %12
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v144 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v136 + (v135 + v62 * v9 + v14 * v10), v142, v143);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
    TLOAD(v133, v144);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID3);
    // pto: %stage__ssa_v5_pview
    ;
    const int64_t v145 = 0;
    // pto: %stage__ssa_v5_pview
    ;
    __gm__ int8_t* v146 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v5_pview
    ;
    const int64_t v147 = 1;
    // pto: %stage__ssa_v5_pview
    ;
    const int64_t v148 = 1;
    // pto: %stage__ssa_v5_pview
    ;
    const int64_t v149 = 1;
    // pto: %stage__ssa_v5_pview
    ;
    int64_t v150 = v10 * v9;
    // pto: %stage__ssa_v5_pview
    ;
    int64_t v151 = v149 * v150;
    // pto: %stage__ssa_v5_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v152 = pto::Shape<1, 1, 1, 1, -1>(v147, v148, v149, v10, v12);
    // pto: %stage__ssa_v5_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v153 = pto::Stride<-1, -1, -1, -1, -1>(v148 * v151, v151, v150, v9, v10);
    // pto: %stage__ssa_v5_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v154 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v146 + (v145 + v62 * v9 + v14 * v10), v152, v153);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID3);
    TSTORE(v154, v133);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID4);
    __gm__ int8_t* v155 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v155);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v4
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v156 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v4
    ;
    uint64_t v157 = (uint64_t) v7;
    TASSIGN(v156, v157);
    // pto: %16
    ;
    const int64_t v158 = 0;
    // pto: %16
    ;
    __gm__ int8_t* v159 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %16
    ;
    const int64_t v160 = 1;
    // pto: %16
    ;
    const int64_t v161 = 1;
    // pto: %16
    ;
    const int64_t v162 = 1;
    // pto: %16
    ;
    int64_t v163 = v10 * v9;
    // pto: %16
    ;
    int64_t v164 = v162 * v163;
    // pto: %16
    ;
    pto::Shape<1, 1, 1, 1, -1> v165 = pto::Shape<1, 1, 1, 1, -1>(v160, v161, v162, v10, v12);
    // pto: %16
    ;
    pto::Stride<-1, -1, -1, -1, -1> v166 = pto::Stride<-1, -1, -1, -1, -1>(v161 * v164, v164, v163, v9, v10);
    // pto: %16
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v167 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v159 + (v158 + v62 * v9 + v15 * v10), v165, v166);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID4);
    TLOAD(v156, v167);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID4);
    // pto: %stage__ssa_v6_pview
    ;
    const int64_t v168 = 0;
    // pto: %stage__ssa_v6_pview
    ;
    __gm__ int8_t* v169 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v6_pview
    ;
    const int64_t v170 = 1;
    // pto: %stage__ssa_v6_pview
    ;
    const int64_t v171 = 1;
    // pto: %stage__ssa_v6_pview
    ;
    const int64_t v172 = 1;
    // pto: %stage__ssa_v6_pview
    ;
    int64_t v173 = v10 * v9;
    // pto: %stage__ssa_v6_pview
    ;
    int64_t v174 = v172 * v173;
    // pto: %stage__ssa_v6_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v175 = pto::Shape<1, 1, 1, 1, -1>(v170, v171, v172, v10, v12);
    // pto: %stage__ssa_v6_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v176 = pto::Stride<-1, -1, -1, -1, -1>(v171 * v174, v174, v173, v9, v10);
    // pto: %stage__ssa_v6_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v177 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v169 + (v168 + v62 * v9 + v15 * v10), v175, v176);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID4);
    TSTORE(v177, v156);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID5);
    __gm__ int8_t* v178 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v178);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v5
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v179 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v5
    ;
    uint64_t v180 = (uint64_t) v7;
    TASSIGN(v179, v180);
    // pto: %20
    ;
    const int64_t v181 = 0;
    // pto: %20
    ;
    __gm__ int8_t* v182 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %20
    ;
    const int64_t v183 = 1;
    // pto: %20
    ;
    const int64_t v184 = 1;
    // pto: %20
    ;
    const int64_t v185 = 1;
    // pto: %20
    ;
    int64_t v186 = v10 * v9;
    // pto: %20
    ;
    int64_t v187 = v185 * v186;
    // pto: %20
    ;
    pto::Shape<1, 1, 1, 1, -1> v188 = pto::Shape<1, 1, 1, 1, -1>(v183, v184, v185, v10, v12);
    // pto: %20
    ;
    pto::Stride<-1, -1, -1, -1, -1> v189 = pto::Stride<-1, -1, -1, -1, -1>(v184 * v187, v187, v186, v9, v10);
    // pto: %20
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v190 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v182 + (v181 + v62 * v9 + v16 * v10), v188, v189);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID5);
    TLOAD(v179, v190);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID5);
    // pto: %stage__ssa_v7_pview
    ;
    const int64_t v191 = 0;
    // pto: %stage__ssa_v7_pview
    ;
    __gm__ int8_t* v192 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v7_pview
    ;
    const int64_t v193 = 1;
    // pto: %stage__ssa_v7_pview
    ;
    const int64_t v194 = 1;
    // pto: %stage__ssa_v7_pview
    ;
    const int64_t v195 = 1;
    // pto: %stage__ssa_v7_pview
    ;
    int64_t v196 = v10 * v9;
    // pto: %stage__ssa_v7_pview
    ;
    int64_t v197 = v195 * v196;
    // pto: %stage__ssa_v7_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v198 = pto::Shape<1, 1, 1, 1, -1>(v193, v194, v195, v10, v12);
    // pto: %stage__ssa_v7_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v199 = pto::Stride<-1, -1, -1, -1, -1>(v194 * v197, v197, v196, v9, v10);
    // pto: %stage__ssa_v7_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v200 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v192 + (v191 + v62 * v9 + v16 * v10), v198, v199);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID5);
    TSTORE(v200, v179);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID6);
    __gm__ int8_t* v201 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v201);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v6
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v202 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v6
    ;
    uint64_t v203 = (uint64_t) v7;
    TASSIGN(v202, v203);
    // pto: %24
    ;
    const int64_t v204 = 0;
    // pto: %24
    ;
    __gm__ int8_t* v205 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %24
    ;
    const int64_t v206 = 1;
    // pto: %24
    ;
    const int64_t v207 = 1;
    // pto: %24
    ;
    const int64_t v208 = 1;
    // pto: %24
    ;
    int64_t v209 = v10 * v9;
    // pto: %24
    ;
    int64_t v210 = v208 * v209;
    // pto: %24
    ;
    pto::Shape<1, 1, 1, 1, -1> v211 = pto::Shape<1, 1, 1, 1, -1>(v206, v207, v208, v10, v12);
    // pto: %24
    ;
    pto::Stride<-1, -1, -1, -1, -1> v212 = pto::Stride<-1, -1, -1, -1, -1>(v207 * v210, v210, v209, v9, v10);
    // pto: %24
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v213 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v205 + (v204 + v62 * v9 + v17 * v10), v211, v212);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID6);
    TLOAD(v202, v213);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID6);
    // pto: %stage__ssa_v8_pview
    ;
    const int64_t v214 = 0;
    // pto: %stage__ssa_v8_pview
    ;
    __gm__ int8_t* v215 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v8_pview
    ;
    const int64_t v216 = 1;
    // pto: %stage__ssa_v8_pview
    ;
    const int64_t v217 = 1;
    // pto: %stage__ssa_v8_pview
    ;
    const int64_t v218 = 1;
    // pto: %stage__ssa_v8_pview
    ;
    int64_t v219 = v10 * v9;
    // pto: %stage__ssa_v8_pview
    ;
    int64_t v220 = v218 * v219;
    // pto: %stage__ssa_v8_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v221 = pto::Shape<1, 1, 1, 1, -1>(v216, v217, v218, v10, v12);
    // pto: %stage__ssa_v8_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v222 = pto::Stride<-1, -1, -1, -1, -1>(v217 * v220, v220, v219, v9, v10);
    // pto: %stage__ssa_v8_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v223 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v215 + (v214 + v62 * v9 + v17 * v10), v221, v222);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID6);
    TSTORE(v223, v202);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID7);
    __gm__ int8_t* v224 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v224);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v7
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v225 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v7
    ;
    uint64_t v226 = (uint64_t) v7;
    TASSIGN(v225, v226);
    // pto: %28
    ;
    const int64_t v227 = 0;
    // pto: %28
    ;
    __gm__ int8_t* v228 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %28
    ;
    const int64_t v229 = 1;
    // pto: %28
    ;
    const int64_t v230 = 1;
    // pto: %28
    ;
    const int64_t v231 = 1;
    // pto: %28
    ;
    int64_t v232 = v10 * v9;
    // pto: %28
    ;
    int64_t v233 = v231 * v232;
    // pto: %28
    ;
    pto::Shape<1, 1, 1, 1, -1> v234 = pto::Shape<1, 1, 1, 1, -1>(v229, v230, v231, v10, v12);
    // pto: %28
    ;
    pto::Stride<-1, -1, -1, -1, -1> v235 = pto::Stride<-1, -1, -1, -1, -1>(v230 * v233, v233, v232, v9, v10);
    // pto: %28
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v236 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v228 + (v227 + v62 * v9 + v18 * v10), v234, v235);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID7);
    TLOAD(v225, v236);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID7);
    // pto: %stage__ssa_v9_pview
    ;
    const int64_t v237 = 0;
    // pto: %stage__ssa_v9_pview
    ;
    __gm__ int8_t* v238 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v9_pview
    ;
    const int64_t v239 = 1;
    // pto: %stage__ssa_v9_pview
    ;
    const int64_t v240 = 1;
    // pto: %stage__ssa_v9_pview
    ;
    const int64_t v241 = 1;
    // pto: %stage__ssa_v9_pview
    ;
    int64_t v242 = v10 * v9;
    // pto: %stage__ssa_v9_pview
    ;
    int64_t v243 = v241 * v242;
    // pto: %stage__ssa_v9_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v244 = pto::Shape<1, 1, 1, 1, -1>(v239, v240, v241, v10, v12);
    // pto: %stage__ssa_v9_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v245 = pto::Stride<-1, -1, -1, -1, -1>(v240 * v243, v243, v242, v9, v10);
    // pto: %stage__ssa_v9_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v246 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v238 + (v237 + v62 * v9 + v18 * v10), v244, v245);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID7);
    TSTORE(v246, v225);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v247 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v247);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v8
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v248 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v8
    ;
    uint64_t v249 = (uint64_t) v7;
    TASSIGN(v248, v249);
    // pto: %32
    ;
    const int64_t v250 = 0;
    // pto: %32
    ;
    __gm__ int8_t* v251 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %32
    ;
    const int64_t v252 = 1;
    // pto: %32
    ;
    const int64_t v253 = 1;
    // pto: %32
    ;
    const int64_t v254 = 1;
    // pto: %32
    ;
    int64_t v255 = v10 * v9;
    // pto: %32
    ;
    int64_t v256 = v254 * v255;
    // pto: %32
    ;
    pto::Shape<1, 1, 1, 1, -1> v257 = pto::Shape<1, 1, 1, 1, -1>(v252, v253, v254, v10, v12);
    // pto: %32
    ;
    pto::Stride<-1, -1, -1, -1, -1> v258 = pto::Stride<-1, -1, -1, -1, -1>(v253 * v256, v256, v255, v9, v10);
    // pto: %32
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v259 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v251 + (v250 + v62 * v9 + v19 * v10), v257, v258);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v248, v259);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v10_pview
    ;
    const int64_t v260 = 0;
    // pto: %stage__ssa_v10_pview
    ;
    __gm__ int8_t* v261 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v10_pview
    ;
    const int64_t v262 = 1;
    // pto: %stage__ssa_v10_pview
    ;
    const int64_t v263 = 1;
    // pto: %stage__ssa_v10_pview
    ;
    const int64_t v264 = 1;
    // pto: %stage__ssa_v10_pview
    ;
    int64_t v265 = v10 * v9;
    // pto: %stage__ssa_v10_pview
    ;
    int64_t v266 = v264 * v265;
    // pto: %stage__ssa_v10_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v267 = pto::Shape<1, 1, 1, 1, -1>(v262, v263, v264, v10, v12);
    // pto: %stage__ssa_v10_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v268 = pto::Stride<-1, -1, -1, -1, -1>(v263 * v266, v266, v265, v9, v10);
    // pto: %stage__ssa_v10_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v269 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v261 + (v260 + v62 * v9 + v19 * v10), v267, v268);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v269, v248);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v270 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v270);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v9
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v271 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v9
    ;
    uint64_t v272 = (uint64_t) v7;
    TASSIGN(v271, v272);
    // pto: %36
    ;
    const int64_t v273 = 0;
    // pto: %36
    ;
    __gm__ int8_t* v274 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %36
    ;
    const int64_t v275 = 1;
    // pto: %36
    ;
    const int64_t v276 = 1;
    // pto: %36
    ;
    const int64_t v277 = 1;
    // pto: %36
    ;
    int64_t v278 = v10 * v9;
    // pto: %36
    ;
    int64_t v279 = v277 * v278;
    // pto: %36
    ;
    pto::Shape<1, 1, 1, 1, -1> v280 = pto::Shape<1, 1, 1, 1, -1>(v275, v276, v277, v10, v12);
    // pto: %36
    ;
    pto::Stride<-1, -1, -1, -1, -1> v281 = pto::Stride<-1, -1, -1, -1, -1>(v276 * v279, v279, v278, v9, v10);
    // pto: %36
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v282 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v274 + (v273 + v62 * v9 + v20 * v10), v280, v281);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v271, v282);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v11_pview
    ;
    const int64_t v283 = 0;
    // pto: %stage__ssa_v11_pview
    ;
    __gm__ int8_t* v284 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v11_pview
    ;
    const int64_t v285 = 1;
    // pto: %stage__ssa_v11_pview
    ;
    const int64_t v286 = 1;
    // pto: %stage__ssa_v11_pview
    ;
    const int64_t v287 = 1;
    // pto: %stage__ssa_v11_pview
    ;
    int64_t v288 = v10 * v9;
    // pto: %stage__ssa_v11_pview
    ;
    int64_t v289 = v287 * v288;
    // pto: %stage__ssa_v11_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v290 = pto::Shape<1, 1, 1, 1, -1>(v285, v286, v287, v10, v12);
    // pto: %stage__ssa_v11_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v291 = pto::Stride<-1, -1, -1, -1, -1>(v286 * v289, v289, v288, v9, v10);
    // pto: %stage__ssa_v11_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v292 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v284 + (v283 + v62 * v9 + v20 * v10), v290, v291);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v292, v271);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v293 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v293);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v10
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v294 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v10
    ;
    uint64_t v295 = (uint64_t) v7;
    TASSIGN(v294, v295);
    // pto: %40
    ;
    const int64_t v296 = 0;
    // pto: %40
    ;
    __gm__ int8_t* v297 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %40
    ;
    const int64_t v298 = 1;
    // pto: %40
    ;
    const int64_t v299 = 1;
    // pto: %40
    ;
    const int64_t v300 = 1;
    // pto: %40
    ;
    int64_t v301 = v10 * v9;
    // pto: %40
    ;
    int64_t v302 = v300 * v301;
    // pto: %40
    ;
    pto::Shape<1, 1, 1, 1, -1> v303 = pto::Shape<1, 1, 1, 1, -1>(v298, v299, v300, v10, v12);
    // pto: %40
    ;
    pto::Stride<-1, -1, -1, -1, -1> v304 = pto::Stride<-1, -1, -1, -1, -1>(v299 * v302, v302, v301, v9, v10);
    // pto: %40
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v305 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v297 + (v296 + v62 * v9 + v21 * v10), v303, v304);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v294, v305);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v12_pview
    ;
    const int64_t v306 = 0;
    // pto: %stage__ssa_v12_pview
    ;
    __gm__ int8_t* v307 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v12_pview
    ;
    const int64_t v308 = 1;
    // pto: %stage__ssa_v12_pview
    ;
    const int64_t v309 = 1;
    // pto: %stage__ssa_v12_pview
    ;
    const int64_t v310 = 1;
    // pto: %stage__ssa_v12_pview
    ;
    int64_t v311 = v10 * v9;
    // pto: %stage__ssa_v12_pview
    ;
    int64_t v312 = v310 * v311;
    // pto: %stage__ssa_v12_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v313 = pto::Shape<1, 1, 1, 1, -1>(v308, v309, v310, v10, v12);
    // pto: %stage__ssa_v12_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v314 = pto::Stride<-1, -1, -1, -1, -1>(v309 * v312, v312, v311, v9, v10);
    // pto: %stage__ssa_v12_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v315 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v307 + (v306 + v62 * v9 + v21 * v10), v313, v314);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v315, v294);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v316 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v316);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v11
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v317 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v11
    ;
    uint64_t v318 = (uint64_t) v7;
    TASSIGN(v317, v318);
    // pto: %44
    ;
    const int64_t v319 = 0;
    // pto: %44
    ;
    __gm__ int8_t* v320 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %44
    ;
    const int64_t v321 = 1;
    // pto: %44
    ;
    const int64_t v322 = 1;
    // pto: %44
    ;
    const int64_t v323 = 1;
    // pto: %44
    ;
    int64_t v324 = v10 * v9;
    // pto: %44
    ;
    int64_t v325 = v323 * v324;
    // pto: %44
    ;
    pto::Shape<1, 1, 1, 1, -1> v326 = pto::Shape<1, 1, 1, 1, -1>(v321, v322, v323, v10, v12);
    // pto: %44
    ;
    pto::Stride<-1, -1, -1, -1, -1> v327 = pto::Stride<-1, -1, -1, -1, -1>(v322 * v325, v325, v324, v9, v10);
    // pto: %44
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v328 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v320 + (v319 + v62 * v9 + v22 * v10), v326, v327);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v317, v328);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v13_pview
    ;
    const int64_t v329 = 0;
    // pto: %stage__ssa_v13_pview
    ;
    __gm__ int8_t* v330 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v13_pview
    ;
    const int64_t v331 = 1;
    // pto: %stage__ssa_v13_pview
    ;
    const int64_t v332 = 1;
    // pto: %stage__ssa_v13_pview
    ;
    const int64_t v333 = 1;
    // pto: %stage__ssa_v13_pview
    ;
    int64_t v334 = v10 * v9;
    // pto: %stage__ssa_v13_pview
    ;
    int64_t v335 = v333 * v334;
    // pto: %stage__ssa_v13_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v336 = pto::Shape<1, 1, 1, 1, -1>(v331, v332, v333, v10, v12);
    // pto: %stage__ssa_v13_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v337 = pto::Stride<-1, -1, -1, -1, -1>(v332 * v335, v335, v334, v9, v10);
    // pto: %stage__ssa_v13_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v338 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v330 + (v329 + v62 * v9 + v22 * v10), v336, v337);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v338, v317);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v339 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v339);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v12
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v340 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v12
    ;
    uint64_t v341 = (uint64_t) v7;
    TASSIGN(v340, v341);
    // pto: %48
    ;
    const int64_t v342 = 0;
    // pto: %48
    ;
    __gm__ int8_t* v343 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %48
    ;
    const int64_t v344 = 1;
    // pto: %48
    ;
    const int64_t v345 = 1;
    // pto: %48
    ;
    const int64_t v346 = 1;
    // pto: %48
    ;
    int64_t v347 = v10 * v9;
    // pto: %48
    ;
    int64_t v348 = v346 * v347;
    // pto: %48
    ;
    pto::Shape<1, 1, 1, 1, -1> v349 = pto::Shape<1, 1, 1, 1, -1>(v344, v345, v346, v10, v12);
    // pto: %48
    ;
    pto::Stride<-1, -1, -1, -1, -1> v350 = pto::Stride<-1, -1, -1, -1, -1>(v345 * v348, v348, v347, v9, v10);
    // pto: %48
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v351 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v343 + (v342 + v62 * v9 + v23 * v10), v349, v350);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v340, v351);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v14_pview
    ;
    const int64_t v352 = 0;
    // pto: %stage__ssa_v14_pview
    ;
    __gm__ int8_t* v353 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v14_pview
    ;
    const int64_t v354 = 1;
    // pto: %stage__ssa_v14_pview
    ;
    const int64_t v355 = 1;
    // pto: %stage__ssa_v14_pview
    ;
    const int64_t v356 = 1;
    // pto: %stage__ssa_v14_pview
    ;
    int64_t v357 = v10 * v9;
    // pto: %stage__ssa_v14_pview
    ;
    int64_t v358 = v356 * v357;
    // pto: %stage__ssa_v14_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v359 = pto::Shape<1, 1, 1, 1, -1>(v354, v355, v356, v10, v12);
    // pto: %stage__ssa_v14_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v360 = pto::Stride<-1, -1, -1, -1, -1>(v355 * v358, v358, v357, v9, v10);
    // pto: %stage__ssa_v14_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v361 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v353 + (v352 + v62 * v9 + v23 * v10), v359, v360);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v361, v340);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v362 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v362);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v13
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v363 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v13
    ;
    uint64_t v364 = (uint64_t) v7;
    TASSIGN(v363, v364);
    // pto: %52
    ;
    const int64_t v365 = 0;
    // pto: %52
    ;
    __gm__ int8_t* v366 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %52
    ;
    const int64_t v367 = 1;
    // pto: %52
    ;
    const int64_t v368 = 1;
    // pto: %52
    ;
    const int64_t v369 = 1;
    // pto: %52
    ;
    int64_t v370 = v10 * v9;
    // pto: %52
    ;
    int64_t v371 = v369 * v370;
    // pto: %52
    ;
    pto::Shape<1, 1, 1, 1, -1> v372 = pto::Shape<1, 1, 1, 1, -1>(v367, v368, v369, v10, v12);
    // pto: %52
    ;
    pto::Stride<-1, -1, -1, -1, -1> v373 = pto::Stride<-1, -1, -1, -1, -1>(v368 * v371, v371, v370, v9, v10);
    // pto: %52
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v374 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v366 + (v365 + v62 * v9 + v24 * v10), v372, v373);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v363, v374);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v15_pview
    ;
    const int64_t v375 = 0;
    // pto: %stage__ssa_v15_pview
    ;
    __gm__ int8_t* v376 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v15_pview
    ;
    const int64_t v377 = 1;
    // pto: %stage__ssa_v15_pview
    ;
    const int64_t v378 = 1;
    // pto: %stage__ssa_v15_pview
    ;
    const int64_t v379 = 1;
    // pto: %stage__ssa_v15_pview
    ;
    int64_t v380 = v10 * v9;
    // pto: %stage__ssa_v15_pview
    ;
    int64_t v381 = v379 * v380;
    // pto: %stage__ssa_v15_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v382 = pto::Shape<1, 1, 1, 1, -1>(v377, v378, v379, v10, v12);
    // pto: %stage__ssa_v15_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v383 = pto::Stride<-1, -1, -1, -1, -1>(v378 * v381, v381, v380, v9, v10);
    // pto: %stage__ssa_v15_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v384 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v376 + (v375 + v62 * v9 + v24 * v10), v382, v383);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v384, v363);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v385 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v385);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v14
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v386 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v14
    ;
    uint64_t v387 = (uint64_t) v7;
    TASSIGN(v386, v387);
    // pto: %56
    ;
    const int64_t v388 = 0;
    // pto: %56
    ;
    __gm__ int8_t* v389 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %56
    ;
    const int64_t v390 = 1;
    // pto: %56
    ;
    const int64_t v391 = 1;
    // pto: %56
    ;
    const int64_t v392 = 1;
    // pto: %56
    ;
    int64_t v393 = v10 * v9;
    // pto: %56
    ;
    int64_t v394 = v392 * v393;
    // pto: %56
    ;
    pto::Shape<1, 1, 1, 1, -1> v395 = pto::Shape<1, 1, 1, 1, -1>(v390, v391, v392, v10, v12);
    // pto: %56
    ;
    pto::Stride<-1, -1, -1, -1, -1> v396 = pto::Stride<-1, -1, -1, -1, -1>(v391 * v394, v394, v393, v9, v10);
    // pto: %56
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v397 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v389 + (v388 + v62 * v9 + v25 * v10), v395, v396);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v386, v397);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v16_pview
    ;
    const int64_t v398 = 0;
    // pto: %stage__ssa_v16_pview
    ;
    __gm__ int8_t* v399 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v16_pview
    ;
    const int64_t v400 = 1;
    // pto: %stage__ssa_v16_pview
    ;
    const int64_t v401 = 1;
    // pto: %stage__ssa_v16_pview
    ;
    const int64_t v402 = 1;
    // pto: %stage__ssa_v16_pview
    ;
    int64_t v403 = v10 * v9;
    // pto: %stage__ssa_v16_pview
    ;
    int64_t v404 = v402 * v403;
    // pto: %stage__ssa_v16_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v405 = pto::Shape<1, 1, 1, 1, -1>(v400, v401, v402, v10, v12);
    // pto: %stage__ssa_v16_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v406 = pto::Stride<-1, -1, -1, -1, -1>(v401 * v404, v404, v403, v9, v10);
    // pto: %stage__ssa_v16_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v407 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v399 + (v398 + v62 * v9 + v25 * v10), v405, v406);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v407, v386);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v408 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v408);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v15
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v409 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v15
    ;
    uint64_t v410 = (uint64_t) v7;
    TASSIGN(v409, v410);
    // pto: %60
    ;
    const int64_t v411 = 0;
    // pto: %60
    ;
    __gm__ int8_t* v412 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %60
    ;
    const int64_t v413 = 1;
    // pto: %60
    ;
    const int64_t v414 = 1;
    // pto: %60
    ;
    const int64_t v415 = 1;
    // pto: %60
    ;
    int64_t v416 = v10 * v9;
    // pto: %60
    ;
    int64_t v417 = v415 * v416;
    // pto: %60
    ;
    pto::Shape<1, 1, 1, 1, -1> v418 = pto::Shape<1, 1, 1, 1, -1>(v413, v414, v415, v10, v12);
    // pto: %60
    ;
    pto::Stride<-1, -1, -1, -1, -1> v419 = pto::Stride<-1, -1, -1, -1, -1>(v414 * v417, v417, v416, v9, v10);
    // pto: %60
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v420 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v412 + (v411 + v62 * v9 + v26 * v10), v418, v419);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v409, v420);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v17_pview
    ;
    const int64_t v421 = 0;
    // pto: %stage__ssa_v17_pview
    ;
    __gm__ int8_t* v422 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v17_pview
    ;
    const int64_t v423 = 1;
    // pto: %stage__ssa_v17_pview
    ;
    const int64_t v424 = 1;
    // pto: %stage__ssa_v17_pview
    ;
    const int64_t v425 = 1;
    // pto: %stage__ssa_v17_pview
    ;
    int64_t v426 = v10 * v9;
    // pto: %stage__ssa_v17_pview
    ;
    int64_t v427 = v425 * v426;
    // pto: %stage__ssa_v17_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v428 = pto::Shape<1, 1, 1, 1, -1>(v423, v424, v425, v10, v12);
    // pto: %stage__ssa_v17_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v429 = pto::Stride<-1, -1, -1, -1, -1>(v424 * v427, v427, v426, v9, v10);
    // pto: %stage__ssa_v17_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v430 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v422 + (v421 + v62 * v9 + v26 * v10), v428, v429);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v430, v409);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v431 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v431);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v16
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v432 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v16
    ;
    uint64_t v433 = (uint64_t) v7;
    TASSIGN(v432, v433);
    // pto: %64
    ;
    const int64_t v434 = 0;
    // pto: %64
    ;
    __gm__ int8_t* v435 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %64
    ;
    const int64_t v436 = 1;
    // pto: %64
    ;
    const int64_t v437 = 1;
    // pto: %64
    ;
    const int64_t v438 = 1;
    // pto: %64
    ;
    int64_t v439 = v10 * v9;
    // pto: %64
    ;
    int64_t v440 = v438 * v439;
    // pto: %64
    ;
    pto::Shape<1, 1, 1, 1, -1> v441 = pto::Shape<1, 1, 1, 1, -1>(v436, v437, v438, v10, v12);
    // pto: %64
    ;
    pto::Stride<-1, -1, -1, -1, -1> v442 = pto::Stride<-1, -1, -1, -1, -1>(v437 * v440, v440, v439, v9, v10);
    // pto: %64
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v443 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v435 + (v434 + v62 * v9 + v27 * v10), v441, v442);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v432, v443);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v18_pview
    ;
    const int64_t v444 = 0;
    // pto: %stage__ssa_v18_pview
    ;
    __gm__ int8_t* v445 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v18_pview
    ;
    const int64_t v446 = 1;
    // pto: %stage__ssa_v18_pview
    ;
    const int64_t v447 = 1;
    // pto: %stage__ssa_v18_pview
    ;
    const int64_t v448 = 1;
    // pto: %stage__ssa_v18_pview
    ;
    int64_t v449 = v10 * v9;
    // pto: %stage__ssa_v18_pview
    ;
    int64_t v450 = v448 * v449;
    // pto: %stage__ssa_v18_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v451 = pto::Shape<1, 1, 1, 1, -1>(v446, v447, v448, v10, v12);
    // pto: %stage__ssa_v18_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v452 = pto::Stride<-1, -1, -1, -1, -1>(v447 * v450, v450, v449, v9, v10);
    // pto: %stage__ssa_v18_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v453 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v445 + (v444 + v62 * v9 + v27 * v10), v451, v452);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v453, v432);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v454 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v454);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v17
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v455 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v17
    ;
    uint64_t v456 = (uint64_t) v7;
    TASSIGN(v455, v456);
    // pto: %68
    ;
    const int64_t v457 = 0;
    // pto: %68
    ;
    __gm__ int8_t* v458 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %68
    ;
    const int64_t v459 = 1;
    // pto: %68
    ;
    const int64_t v460 = 1;
    // pto: %68
    ;
    const int64_t v461 = 1;
    // pto: %68
    ;
    int64_t v462 = v10 * v9;
    // pto: %68
    ;
    int64_t v463 = v461 * v462;
    // pto: %68
    ;
    pto::Shape<1, 1, 1, 1, -1> v464 = pto::Shape<1, 1, 1, 1, -1>(v459, v460, v461, v10, v12);
    // pto: %68
    ;
    pto::Stride<-1, -1, -1, -1, -1> v465 = pto::Stride<-1, -1, -1, -1, -1>(v460 * v463, v463, v462, v9, v10);
    // pto: %68
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v466 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v458 + (v457 + v62 * v9 + v28 * v10), v464, v465);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v455, v466);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v19_pview
    ;
    const int64_t v467 = 0;
    // pto: %stage__ssa_v19_pview
    ;
    __gm__ int8_t* v468 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v19_pview
    ;
    const int64_t v469 = 1;
    // pto: %stage__ssa_v19_pview
    ;
    const int64_t v470 = 1;
    // pto: %stage__ssa_v19_pview
    ;
    const int64_t v471 = 1;
    // pto: %stage__ssa_v19_pview
    ;
    int64_t v472 = v10 * v9;
    // pto: %stage__ssa_v19_pview
    ;
    int64_t v473 = v471 * v472;
    // pto: %stage__ssa_v19_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v474 = pto::Shape<1, 1, 1, 1, -1>(v469, v470, v471, v10, v12);
    // pto: %stage__ssa_v19_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v475 = pto::Stride<-1, -1, -1, -1, -1>(v470 * v473, v473, v472, v9, v10);
    // pto: %stage__ssa_v19_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v476 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v468 + (v467 + v62 * v9 + v28 * v10), v474, v475);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v476, v455);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v477 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v477);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v18
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v478 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v18
    ;
    uint64_t v479 = (uint64_t) v7;
    TASSIGN(v478, v479);
    // pto: %72
    ;
    const int64_t v480 = 0;
    // pto: %72
    ;
    __gm__ int8_t* v481 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %72
    ;
    const int64_t v482 = 1;
    // pto: %72
    ;
    const int64_t v483 = 1;
    // pto: %72
    ;
    const int64_t v484 = 1;
    // pto: %72
    ;
    int64_t v485 = v10 * v9;
    // pto: %72
    ;
    int64_t v486 = v484 * v485;
    // pto: %72
    ;
    pto::Shape<1, 1, 1, 1, -1> v487 = pto::Shape<1, 1, 1, 1, -1>(v482, v483, v484, v10, v12);
    // pto: %72
    ;
    pto::Stride<-1, -1, -1, -1, -1> v488 = pto::Stride<-1, -1, -1, -1, -1>(v483 * v486, v486, v485, v9, v10);
    // pto: %72
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v489 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v481 + (v480 + v62 * v9 + v29 * v10), v487, v488);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v478, v489);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v20_pview
    ;
    const int64_t v490 = 0;
    // pto: %stage__ssa_v20_pview
    ;
    __gm__ int8_t* v491 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v20_pview
    ;
    const int64_t v492 = 1;
    // pto: %stage__ssa_v20_pview
    ;
    const int64_t v493 = 1;
    // pto: %stage__ssa_v20_pview
    ;
    const int64_t v494 = 1;
    // pto: %stage__ssa_v20_pview
    ;
    int64_t v495 = v10 * v9;
    // pto: %stage__ssa_v20_pview
    ;
    int64_t v496 = v494 * v495;
    // pto: %stage__ssa_v20_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v497 = pto::Shape<1, 1, 1, 1, -1>(v492, v493, v494, v10, v12);
    // pto: %stage__ssa_v20_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v498 = pto::Stride<-1, -1, -1, -1, -1>(v493 * v496, v496, v495, v9, v10);
    // pto: %stage__ssa_v20_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v499 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v491 + (v490 + v62 * v9 + v29 * v10), v497, v498);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v499, v478);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v500 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v500);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v19
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v501 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v19
    ;
    uint64_t v502 = (uint64_t) v7;
    TASSIGN(v501, v502);
    // pto: %76
    ;
    const int64_t v503 = 0;
    // pto: %76
    ;
    __gm__ int8_t* v504 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %76
    ;
    const int64_t v505 = 1;
    // pto: %76
    ;
    const int64_t v506 = 1;
    // pto: %76
    ;
    const int64_t v507 = 1;
    // pto: %76
    ;
    int64_t v508 = v10 * v9;
    // pto: %76
    ;
    int64_t v509 = v507 * v508;
    // pto: %76
    ;
    pto::Shape<1, 1, 1, 1, -1> v510 = pto::Shape<1, 1, 1, 1, -1>(v505, v506, v507, v10, v12);
    // pto: %76
    ;
    pto::Stride<-1, -1, -1, -1, -1> v511 = pto::Stride<-1, -1, -1, -1, -1>(v506 * v509, v509, v508, v9, v10);
    // pto: %76
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v512 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v504 + (v503 + v62 * v9 + v30 * v10), v510, v511);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v501, v512);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v21_pview
    ;
    const int64_t v513 = 0;
    // pto: %stage__ssa_v21_pview
    ;
    __gm__ int8_t* v514 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v21_pview
    ;
    const int64_t v515 = 1;
    // pto: %stage__ssa_v21_pview
    ;
    const int64_t v516 = 1;
    // pto: %stage__ssa_v21_pview
    ;
    const int64_t v517 = 1;
    // pto: %stage__ssa_v21_pview
    ;
    int64_t v518 = v10 * v9;
    // pto: %stage__ssa_v21_pview
    ;
    int64_t v519 = v517 * v518;
    // pto: %stage__ssa_v21_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v520 = pto::Shape<1, 1, 1, 1, -1>(v515, v516, v517, v10, v12);
    // pto: %stage__ssa_v21_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v521 = pto::Stride<-1, -1, -1, -1, -1>(v516 * v519, v519, v518, v9, v10);
    // pto: %stage__ssa_v21_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v522 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v514 + (v513 + v62 * v9 + v30 * v10), v520, v521);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v522, v501);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v523 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v523);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v20
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v524 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v20
    ;
    uint64_t v525 = (uint64_t) v7;
    TASSIGN(v524, v525);
    // pto: %80
    ;
    const int64_t v526 = 0;
    // pto: %80
    ;
    __gm__ int8_t* v527 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %80
    ;
    const int64_t v528 = 1;
    // pto: %80
    ;
    const int64_t v529 = 1;
    // pto: %80
    ;
    const int64_t v530 = 1;
    // pto: %80
    ;
    int64_t v531 = v10 * v9;
    // pto: %80
    ;
    int64_t v532 = v530 * v531;
    // pto: %80
    ;
    pto::Shape<1, 1, 1, 1, -1> v533 = pto::Shape<1, 1, 1, 1, -1>(v528, v529, v530, v10, v12);
    // pto: %80
    ;
    pto::Stride<-1, -1, -1, -1, -1> v534 = pto::Stride<-1, -1, -1, -1, -1>(v529 * v532, v532, v531, v9, v10);
    // pto: %80
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v535 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v527 + (v526 + v62 * v9 + v31 * v10), v533, v534);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v524, v535);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v22_pview
    ;
    const int64_t v536 = 0;
    // pto: %stage__ssa_v22_pview
    ;
    __gm__ int8_t* v537 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v22_pview
    ;
    const int64_t v538 = 1;
    // pto: %stage__ssa_v22_pview
    ;
    const int64_t v539 = 1;
    // pto: %stage__ssa_v22_pview
    ;
    const int64_t v540 = 1;
    // pto: %stage__ssa_v22_pview
    ;
    int64_t v541 = v10 * v9;
    // pto: %stage__ssa_v22_pview
    ;
    int64_t v542 = v540 * v541;
    // pto: %stage__ssa_v22_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v543 = pto::Shape<1, 1, 1, 1, -1>(v538, v539, v540, v10, v12);
    // pto: %stage__ssa_v22_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v544 = pto::Stride<-1, -1, -1, -1, -1>(v539 * v542, v542, v541, v9, v10);
    // pto: %stage__ssa_v22_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v545 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v537 + (v536 + v62 * v9 + v31 * v10), v543, v544);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v545, v524);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v546 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v546);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v21
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v547 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v21
    ;
    uint64_t v548 = (uint64_t) v7;
    TASSIGN(v547, v548);
    // pto: %84
    ;
    const int64_t v549 = 0;
    // pto: %84
    ;
    __gm__ int8_t* v550 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %84
    ;
    const int64_t v551 = 1;
    // pto: %84
    ;
    const int64_t v552 = 1;
    // pto: %84
    ;
    const int64_t v553 = 1;
    // pto: %84
    ;
    int64_t v554 = v10 * v9;
    // pto: %84
    ;
    int64_t v555 = v553 * v554;
    // pto: %84
    ;
    pto::Shape<1, 1, 1, 1, -1> v556 = pto::Shape<1, 1, 1, 1, -1>(v551, v552, v553, v10, v12);
    // pto: %84
    ;
    pto::Stride<-1, -1, -1, -1, -1> v557 = pto::Stride<-1, -1, -1, -1, -1>(v552 * v555, v555, v554, v9, v10);
    // pto: %84
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v558 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v550 + (v549 + v62 * v9 + v32 * v10), v556, v557);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v547, v558);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v23_pview
    ;
    const int64_t v559 = 0;
    // pto: %stage__ssa_v23_pview
    ;
    __gm__ int8_t* v560 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v23_pview
    ;
    const int64_t v561 = 1;
    // pto: %stage__ssa_v23_pview
    ;
    const int64_t v562 = 1;
    // pto: %stage__ssa_v23_pview
    ;
    const int64_t v563 = 1;
    // pto: %stage__ssa_v23_pview
    ;
    int64_t v564 = v10 * v9;
    // pto: %stage__ssa_v23_pview
    ;
    int64_t v565 = v563 * v564;
    // pto: %stage__ssa_v23_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v566 = pto::Shape<1, 1, 1, 1, -1>(v561, v562, v563, v10, v12);
    // pto: %stage__ssa_v23_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v567 = pto::Stride<-1, -1, -1, -1, -1>(v562 * v565, v565, v564, v9, v10);
    // pto: %stage__ssa_v23_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v568 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v560 + (v559 + v62 * v9 + v32 * v10), v566, v567);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v568, v547);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v569 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v569);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v22
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v570 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v22
    ;
    uint64_t v571 = (uint64_t) v7;
    TASSIGN(v570, v571);
    // pto: %88
    ;
    const int64_t v572 = 0;
    // pto: %88
    ;
    __gm__ int8_t* v573 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %88
    ;
    const int64_t v574 = 1;
    // pto: %88
    ;
    const int64_t v575 = 1;
    // pto: %88
    ;
    const int64_t v576 = 1;
    // pto: %88
    ;
    int64_t v577 = v10 * v9;
    // pto: %88
    ;
    int64_t v578 = v576 * v577;
    // pto: %88
    ;
    pto::Shape<1, 1, 1, 1, -1> v579 = pto::Shape<1, 1, 1, 1, -1>(v574, v575, v576, v10, v12);
    // pto: %88
    ;
    pto::Stride<-1, -1, -1, -1, -1> v580 = pto::Stride<-1, -1, -1, -1, -1>(v575 * v578, v578, v577, v9, v10);
    // pto: %88
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v581 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v573 + (v572 + v62 * v9 + v33 * v10), v579, v580);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v570, v581);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v24_pview
    ;
    const int64_t v582 = 0;
    // pto: %stage__ssa_v24_pview
    ;
    __gm__ int8_t* v583 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v24_pview
    ;
    const int64_t v584 = 1;
    // pto: %stage__ssa_v24_pview
    ;
    const int64_t v585 = 1;
    // pto: %stage__ssa_v24_pview
    ;
    const int64_t v586 = 1;
    // pto: %stage__ssa_v24_pview
    ;
    int64_t v587 = v10 * v9;
    // pto: %stage__ssa_v24_pview
    ;
    int64_t v588 = v586 * v587;
    // pto: %stage__ssa_v24_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v589 = pto::Shape<1, 1, 1, 1, -1>(v584, v585, v586, v10, v12);
    // pto: %stage__ssa_v24_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v590 = pto::Stride<-1, -1, -1, -1, -1>(v585 * v588, v588, v587, v9, v10);
    // pto: %stage__ssa_v24_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v591 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v583 + (v582 + v62 * v9 + v33 * v10), v589, v590);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v591, v570);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v592 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v592);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v23
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v593 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v23
    ;
    uint64_t v594 = (uint64_t) v7;
    TASSIGN(v593, v594);
    // pto: %92
    ;
    const int64_t v595 = 0;
    // pto: %92
    ;
    __gm__ int8_t* v596 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %92
    ;
    const int64_t v597 = 1;
    // pto: %92
    ;
    const int64_t v598 = 1;
    // pto: %92
    ;
    const int64_t v599 = 1;
    // pto: %92
    ;
    int64_t v600 = v10 * v9;
    // pto: %92
    ;
    int64_t v601 = v599 * v600;
    // pto: %92
    ;
    pto::Shape<1, 1, 1, 1, -1> v602 = pto::Shape<1, 1, 1, 1, -1>(v597, v598, v599, v10, v12);
    // pto: %92
    ;
    pto::Stride<-1, -1, -1, -1, -1> v603 = pto::Stride<-1, -1, -1, -1, -1>(v598 * v601, v601, v600, v9, v10);
    // pto: %92
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v604 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v596 + (v595 + v62 * v9 + v34 * v10), v602, v603);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v593, v604);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v25_pview
    ;
    const int64_t v605 = 0;
    // pto: %stage__ssa_v25_pview
    ;
    __gm__ int8_t* v606 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v25_pview
    ;
    const int64_t v607 = 1;
    // pto: %stage__ssa_v25_pview
    ;
    const int64_t v608 = 1;
    // pto: %stage__ssa_v25_pview
    ;
    const int64_t v609 = 1;
    // pto: %stage__ssa_v25_pview
    ;
    int64_t v610 = v10 * v9;
    // pto: %stage__ssa_v25_pview
    ;
    int64_t v611 = v609 * v610;
    // pto: %stage__ssa_v25_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v612 = pto::Shape<1, 1, 1, 1, -1>(v607, v608, v609, v10, v12);
    // pto: %stage__ssa_v25_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v613 = pto::Stride<-1, -1, -1, -1, -1>(v608 * v611, v611, v610, v9, v10);
    // pto: %stage__ssa_v25_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v614 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v606 + (v605 + v62 * v9 + v34 * v10), v612, v613);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v614, v593);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v615 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v615);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v24
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v616 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v24
    ;
    uint64_t v617 = (uint64_t) v7;
    TASSIGN(v616, v617);
    // pto: %96
    ;
    const int64_t v618 = 0;
    // pto: %96
    ;
    __gm__ int8_t* v619 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %96
    ;
    const int64_t v620 = 1;
    // pto: %96
    ;
    const int64_t v621 = 1;
    // pto: %96
    ;
    const int64_t v622 = 1;
    // pto: %96
    ;
    int64_t v623 = v10 * v9;
    // pto: %96
    ;
    int64_t v624 = v622 * v623;
    // pto: %96
    ;
    pto::Shape<1, 1, 1, 1, -1> v625 = pto::Shape<1, 1, 1, 1, -1>(v620, v621, v622, v10, v12);
    // pto: %96
    ;
    pto::Stride<-1, -1, -1, -1, -1> v626 = pto::Stride<-1, -1, -1, -1, -1>(v621 * v624, v624, v623, v9, v10);
    // pto: %96
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v627 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v619 + (v618 + v62 * v9 + v35 * v10), v625, v626);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v616, v627);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v26_pview
    ;
    const int64_t v628 = 0;
    // pto: %stage__ssa_v26_pview
    ;
    __gm__ int8_t* v629 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v26_pview
    ;
    const int64_t v630 = 1;
    // pto: %stage__ssa_v26_pview
    ;
    const int64_t v631 = 1;
    // pto: %stage__ssa_v26_pview
    ;
    const int64_t v632 = 1;
    // pto: %stage__ssa_v26_pview
    ;
    int64_t v633 = v10 * v9;
    // pto: %stage__ssa_v26_pview
    ;
    int64_t v634 = v632 * v633;
    // pto: %stage__ssa_v26_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v635 = pto::Shape<1, 1, 1, 1, -1>(v630, v631, v632, v10, v12);
    // pto: %stage__ssa_v26_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v636 = pto::Stride<-1, -1, -1, -1, -1>(v631 * v634, v634, v633, v9, v10);
    // pto: %stage__ssa_v26_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v637 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v629 + (v628 + v62 * v9 + v35 * v10), v635, v636);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v637, v616);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v638 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v638);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v25
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v639 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v25
    ;
    uint64_t v640 = (uint64_t) v7;
    TASSIGN(v639, v640);
    // pto: %100
    ;
    const int64_t v641 = 0;
    // pto: %100
    ;
    __gm__ int8_t* v642 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %100
    ;
    const int64_t v643 = 1;
    // pto: %100
    ;
    const int64_t v644 = 1;
    // pto: %100
    ;
    const int64_t v645 = 1;
    // pto: %100
    ;
    int64_t v646 = v10 * v9;
    // pto: %100
    ;
    int64_t v647 = v645 * v646;
    // pto: %100
    ;
    pto::Shape<1, 1, 1, 1, -1> v648 = pto::Shape<1, 1, 1, 1, -1>(v643, v644, v645, v10, v12);
    // pto: %100
    ;
    pto::Stride<-1, -1, -1, -1, -1> v649 = pto::Stride<-1, -1, -1, -1, -1>(v644 * v647, v647, v646, v9, v10);
    // pto: %100
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v650 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v642 + (v641 + v62 * v9 + v36 * v10), v648, v649);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v639, v650);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v27_pview
    ;
    const int64_t v651 = 0;
    // pto: %stage__ssa_v27_pview
    ;
    __gm__ int8_t* v652 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v27_pview
    ;
    const int64_t v653 = 1;
    // pto: %stage__ssa_v27_pview
    ;
    const int64_t v654 = 1;
    // pto: %stage__ssa_v27_pview
    ;
    const int64_t v655 = 1;
    // pto: %stage__ssa_v27_pview
    ;
    int64_t v656 = v10 * v9;
    // pto: %stage__ssa_v27_pview
    ;
    int64_t v657 = v655 * v656;
    // pto: %stage__ssa_v27_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v658 = pto::Shape<1, 1, 1, 1, -1>(v653, v654, v655, v10, v12);
    // pto: %stage__ssa_v27_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v659 = pto::Stride<-1, -1, -1, -1, -1>(v654 * v657, v657, v656, v9, v10);
    // pto: %stage__ssa_v27_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v660 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v652 + (v651 + v62 * v9 + v36 * v10), v658, v659);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v660, v639);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v661 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v661);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v26
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v662 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v26
    ;
    uint64_t v663 = (uint64_t) v7;
    TASSIGN(v662, v663);
    // pto: %104
    ;
    const int64_t v664 = 0;
    // pto: %104
    ;
    __gm__ int8_t* v665 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %104
    ;
    const int64_t v666 = 1;
    // pto: %104
    ;
    const int64_t v667 = 1;
    // pto: %104
    ;
    const int64_t v668 = 1;
    // pto: %104
    ;
    int64_t v669 = v10 * v9;
    // pto: %104
    ;
    int64_t v670 = v668 * v669;
    // pto: %104
    ;
    pto::Shape<1, 1, 1, 1, -1> v671 = pto::Shape<1, 1, 1, 1, -1>(v666, v667, v668, v10, v12);
    // pto: %104
    ;
    pto::Stride<-1, -1, -1, -1, -1> v672 = pto::Stride<-1, -1, -1, -1, -1>(v667 * v670, v670, v669, v9, v10);
    // pto: %104
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v673 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v665 + (v664 + v62 * v9 + v37 * v10), v671, v672);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v662, v673);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v28_pview
    ;
    const int64_t v674 = 0;
    // pto: %stage__ssa_v28_pview
    ;
    __gm__ int8_t* v675 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v28_pview
    ;
    const int64_t v676 = 1;
    // pto: %stage__ssa_v28_pview
    ;
    const int64_t v677 = 1;
    // pto: %stage__ssa_v28_pview
    ;
    const int64_t v678 = 1;
    // pto: %stage__ssa_v28_pview
    ;
    int64_t v679 = v10 * v9;
    // pto: %stage__ssa_v28_pview
    ;
    int64_t v680 = v678 * v679;
    // pto: %stage__ssa_v28_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v681 = pto::Shape<1, 1, 1, 1, -1>(v676, v677, v678, v10, v12);
    // pto: %stage__ssa_v28_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v682 = pto::Stride<-1, -1, -1, -1, -1>(v677 * v680, v680, v679, v9, v10);
    // pto: %stage__ssa_v28_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v683 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v675 + (v674 + v62 * v9 + v37 * v10), v681, v682);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v683, v662);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v684 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v684);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v27
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v685 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v27
    ;
    uint64_t v686 = (uint64_t) v7;
    TASSIGN(v685, v686);
    // pto: %108
    ;
    const int64_t v687 = 0;
    // pto: %108
    ;
    __gm__ int8_t* v688 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %108
    ;
    const int64_t v689 = 1;
    // pto: %108
    ;
    const int64_t v690 = 1;
    // pto: %108
    ;
    const int64_t v691 = 1;
    // pto: %108
    ;
    int64_t v692 = v10 * v9;
    // pto: %108
    ;
    int64_t v693 = v691 * v692;
    // pto: %108
    ;
    pto::Shape<1, 1, 1, 1, -1> v694 = pto::Shape<1, 1, 1, 1, -1>(v689, v690, v691, v10, v12);
    // pto: %108
    ;
    pto::Stride<-1, -1, -1, -1, -1> v695 = pto::Stride<-1, -1, -1, -1, -1>(v690 * v693, v693, v692, v9, v10);
    // pto: %108
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v696 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v688 + (v687 + v62 * v9 + v38 * v10), v694, v695);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v685, v696);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v29_pview
    ;
    const int64_t v697 = 0;
    // pto: %stage__ssa_v29_pview
    ;
    __gm__ int8_t* v698 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v29_pview
    ;
    const int64_t v699 = 1;
    // pto: %stage__ssa_v29_pview
    ;
    const int64_t v700 = 1;
    // pto: %stage__ssa_v29_pview
    ;
    const int64_t v701 = 1;
    // pto: %stage__ssa_v29_pview
    ;
    int64_t v702 = v10 * v9;
    // pto: %stage__ssa_v29_pview
    ;
    int64_t v703 = v701 * v702;
    // pto: %stage__ssa_v29_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v704 = pto::Shape<1, 1, 1, 1, -1>(v699, v700, v701, v10, v12);
    // pto: %stage__ssa_v29_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v705 = pto::Stride<-1, -1, -1, -1, -1>(v700 * v703, v703, v702, v9, v10);
    // pto: %stage__ssa_v29_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v706 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v698 + (v697 + v62 * v9 + v38 * v10), v704, v705);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v706, v685);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v707 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v707);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v28
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v708 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v28
    ;
    uint64_t v709 = (uint64_t) v7;
    TASSIGN(v708, v709);
    // pto: %112
    ;
    const int64_t v710 = 0;
    // pto: %112
    ;
    __gm__ int8_t* v711 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %112
    ;
    const int64_t v712 = 1;
    // pto: %112
    ;
    const int64_t v713 = 1;
    // pto: %112
    ;
    const int64_t v714 = 1;
    // pto: %112
    ;
    int64_t v715 = v10 * v9;
    // pto: %112
    ;
    int64_t v716 = v714 * v715;
    // pto: %112
    ;
    pto::Shape<1, 1, 1, 1, -1> v717 = pto::Shape<1, 1, 1, 1, -1>(v712, v713, v714, v10, v12);
    // pto: %112
    ;
    pto::Stride<-1, -1, -1, -1, -1> v718 = pto::Stride<-1, -1, -1, -1, -1>(v713 * v716, v716, v715, v9, v10);
    // pto: %112
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v719 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v711 + (v710 + v62 * v9 + v39 * v10), v717, v718);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v708, v719);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v30_pview
    ;
    const int64_t v720 = 0;
    // pto: %stage__ssa_v30_pview
    ;
    __gm__ int8_t* v721 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v30_pview
    ;
    const int64_t v722 = 1;
    // pto: %stage__ssa_v30_pview
    ;
    const int64_t v723 = 1;
    // pto: %stage__ssa_v30_pview
    ;
    const int64_t v724 = 1;
    // pto: %stage__ssa_v30_pview
    ;
    int64_t v725 = v10 * v9;
    // pto: %stage__ssa_v30_pview
    ;
    int64_t v726 = v724 * v725;
    // pto: %stage__ssa_v30_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v727 = pto::Shape<1, 1, 1, 1, -1>(v722, v723, v724, v10, v12);
    // pto: %stage__ssa_v30_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v728 = pto::Stride<-1, -1, -1, -1, -1>(v723 * v726, v726, v725, v9, v10);
    // pto: %stage__ssa_v30_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v729 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v721 + (v720 + v62 * v9 + v39 * v10), v727, v728);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v729, v708);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v730 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v730);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v29
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v731 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v29
    ;
    uint64_t v732 = (uint64_t) v7;
    TASSIGN(v731, v732);
    // pto: %116
    ;
    const int64_t v733 = 0;
    // pto: %116
    ;
    __gm__ int8_t* v734 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %116
    ;
    const int64_t v735 = 1;
    // pto: %116
    ;
    const int64_t v736 = 1;
    // pto: %116
    ;
    const int64_t v737 = 1;
    // pto: %116
    ;
    int64_t v738 = v10 * v9;
    // pto: %116
    ;
    int64_t v739 = v737 * v738;
    // pto: %116
    ;
    pto::Shape<1, 1, 1, 1, -1> v740 = pto::Shape<1, 1, 1, 1, -1>(v735, v736, v737, v10, v12);
    // pto: %116
    ;
    pto::Stride<-1, -1, -1, -1, -1> v741 = pto::Stride<-1, -1, -1, -1, -1>(v736 * v739, v739, v738, v9, v10);
    // pto: %116
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v742 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v734 + (v733 + v62 * v9 + v40 * v10), v740, v741);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v731, v742);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v31_pview
    ;
    const int64_t v743 = 0;
    // pto: %stage__ssa_v31_pview
    ;
    __gm__ int8_t* v744 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v31_pview
    ;
    const int64_t v745 = 1;
    // pto: %stage__ssa_v31_pview
    ;
    const int64_t v746 = 1;
    // pto: %stage__ssa_v31_pview
    ;
    const int64_t v747 = 1;
    // pto: %stage__ssa_v31_pview
    ;
    int64_t v748 = v10 * v9;
    // pto: %stage__ssa_v31_pview
    ;
    int64_t v749 = v747 * v748;
    // pto: %stage__ssa_v31_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v750 = pto::Shape<1, 1, 1, 1, -1>(v745, v746, v747, v10, v12);
    // pto: %stage__ssa_v31_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v751 = pto::Stride<-1, -1, -1, -1, -1>(v746 * v749, v749, v748, v9, v10);
    // pto: %stage__ssa_v31_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v752 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v744 + (v743 + v62 * v9 + v40 * v10), v750, v751);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v752, v731);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v753 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v753);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v30
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v754 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v30
    ;
    uint64_t v755 = (uint64_t) v7;
    TASSIGN(v754, v755);
    // pto: %120
    ;
    const int64_t v756 = 0;
    // pto: %120
    ;
    __gm__ int8_t* v757 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %120
    ;
    const int64_t v758 = 1;
    // pto: %120
    ;
    const int64_t v759 = 1;
    // pto: %120
    ;
    const int64_t v760 = 1;
    // pto: %120
    ;
    int64_t v761 = v10 * v9;
    // pto: %120
    ;
    int64_t v762 = v760 * v761;
    // pto: %120
    ;
    pto::Shape<1, 1, 1, 1, -1> v763 = pto::Shape<1, 1, 1, 1, -1>(v758, v759, v760, v10, v12);
    // pto: %120
    ;
    pto::Stride<-1, -1, -1, -1, -1> v764 = pto::Stride<-1, -1, -1, -1, -1>(v759 * v762, v762, v761, v9, v10);
    // pto: %120
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v765 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v757 + (v756 + v62 * v9 + v41 * v10), v763, v764);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v754, v765);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v32_pview
    ;
    const int64_t v766 = 0;
    // pto: %stage__ssa_v32_pview
    ;
    __gm__ int8_t* v767 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v32_pview
    ;
    const int64_t v768 = 1;
    // pto: %stage__ssa_v32_pview
    ;
    const int64_t v769 = 1;
    // pto: %stage__ssa_v32_pview
    ;
    const int64_t v770 = 1;
    // pto: %stage__ssa_v32_pview
    ;
    int64_t v771 = v10 * v9;
    // pto: %stage__ssa_v32_pview
    ;
    int64_t v772 = v770 * v771;
    // pto: %stage__ssa_v32_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v773 = pto::Shape<1, 1, 1, 1, -1>(v768, v769, v770, v10, v12);
    // pto: %stage__ssa_v32_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v774 = pto::Stride<-1, -1, -1, -1, -1>(v769 * v772, v772, v771, v9, v10);
    // pto: %stage__ssa_v32_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v775 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v767 + (v766 + v62 * v9 + v41 * v10), v773, v774);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v775, v754);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v776 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v776);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v31
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v777 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    // pto: %tile__ssa_v31
    ;
    uint64_t v778 = (uint64_t) v7;
    TASSIGN(v777, v778);
    // pto: %124
    ;
    const int64_t v779 = 0;
    // pto: %124
    ;
    __gm__ int8_t* v780 = PTOAS__GLOBAL_TENSOR_DATA(v50);
    // pto: %124
    ;
    const int64_t v781 = 1;
    // pto: %124
    ;
    const int64_t v782 = 1;
    // pto: %124
    ;
    const int64_t v783 = 1;
    // pto: %124
    ;
    int64_t v784 = v10 * v9;
    // pto: %124
    ;
    int64_t v785 = v783 * v784;
    // pto: %124
    ;
    pto::Shape<1, 1, 1, 1, -1> v786 = pto::Shape<1, 1, 1, 1, -1>(v781, v782, v783, v10, v12);
    // pto: %124
    ;
    pto::Stride<-1, -1, -1, -1, -1> v787 = pto::Stride<-1, -1, -1, -1, -1>(v782 * v785, v785, v784, v9, v10);
    // pto: %124
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v788 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v780 + (v779 + v62 * v9 + v42 * v10), v786, v787);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v777, v788);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v33_pview
    ;
    const int64_t v789 = 0;
    // pto: %stage__ssa_v33_pview
    ;
    __gm__ int8_t* v790 = PTOAS__GLOBAL_TENSOR_DATA(v58);
    // pto: %stage__ssa_v33_pview
    ;
    const int64_t v791 = 1;
    // pto: %stage__ssa_v33_pview
    ;
    const int64_t v792 = 1;
    // pto: %stage__ssa_v33_pview
    ;
    const int64_t v793 = 1;
    // pto: %stage__ssa_v33_pview
    ;
    int64_t v794 = v10 * v9;
    // pto: %stage__ssa_v33_pview
    ;
    int64_t v795 = v793 * v794;
    // pto: %stage__ssa_v33_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v796 = pto::Shape<1, 1, 1, 1, -1>(v791, v792, v793, v10, v12);
    // pto: %stage__ssa_v33_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v797 = pto::Stride<-1, -1, -1, -1, -1>(v792 * v795, v795, v794, v9, v10);
    // pto: %stage__ssa_v33_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v798 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v790 + (v789 + v62 * v9 + v42 * v10), v796, v797);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v798, v777);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    __gm__ int8_t* v799 = PTOAS__GLOBAL_TENSOR_DATA(v85);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v799);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
  }
  for (int64_t v800 = v11; v800 < v8; v800 += v10) {
    // pto: %v__tile
    ;
    int32_t v801 = (v2)[v800];
    (v4)[v800] = v801;
    // pto: %counts__ssa_v0_pview
    ;
    pto::Shape<1, 1, 1, 4, 1> v802 = pto::Shape<1, 1, 1, 4, 1>();
    // pto: %counts__ssa_v0_pview
    ;
    pto::Stride<4, 4, 4, 1, 4> v803 = pto::Stride<4, 4, 4, 1, 4>();
    // pto: %counts__ssa_v0_pview
    ;
    GlobalTensor<int32_t, pto::Shape<1, 1, 1, 4, 1>, pto::Stride<4, 4, 4, 1, 4>, pto::Layout::DN> v804 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 4, 1>, pto::Stride<4, 4, 4, 1, 4>, pto::Layout::DN>((__gm__ int32_t*) v4, v802, v803);
    __gm__ int32_t* v805 = PTOAS__GLOBAL_TENSOR_DATA(v804);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v805);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
  }
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  pipe_barrier(PIPE_ALL);
  dcci((__gm__ void*)0, cache_line_t::ENTIRE_DATA_CACHE);
  dsb((mem_dsb_t)0);
  #endif // __DAV_VEC__

  pipe_barrier(PIPE_ALL);
  dcci((__gm__ void*)0, cache_line_t::ENTIRE_DATA_CACHE);
  dsb((mem_dsb_t)0);
  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM) && !defined(__COSTMODEL)
    // Reset AI Core atomic mode inherited from a prior kernel.
    set_atomic_none();
#endif

    // Unpack tensor: inp__ssa_v0
    __gm__ Tensor* inp__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ int8_t* inp__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(inp__ssa_v0_tensor->buffer.addr) + inp__ssa_v0_tensor->start_offset;

    // Unpack tensor: counts_row__ssa_v0
    __gm__ Tensor* counts_row__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int32_t* counts_row__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(counts_row__ssa_v0_tensor->buffer.addr) + counts_row__ssa_v0_tensor->start_offset;

    // Unpack tensor: stage__ssa_v0
    __gm__ Tensor* stage__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ int8_t* stage__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(stage__ssa_v0_tensor->buffer.addr) + stage__ssa_v0_tensor->start_offset;

    // Unpack tensor: counts__ssa_v0
    __gm__ Tensor* counts__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ int32_t* counts__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(counts__ssa_v0_tensor->buffer.addr) + counts__ssa_v0_tensor->start_offset;

    // Unpack CommContext: stage_ctx
    __gm__ int64_t* stage_ctx = reinterpret_cast<__gm__ int64_t*>(args[4]);

    // Unpack CommContext: counts_ctx
    __gm__ int64_t* counts_ctx = reinterpret_cast<__gm__ int64_t*>(args[5]);

    // Forward to ptoas-generated function
    stage_step(inp__ssa_v0, counts_row__ssa_v0, stage__ssa_v0, counts__ssa_v0, stage_ctx, counts_ctx);
}
