// Kernel Function: stage_step
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"



using namespace pto;


// --- ptoas-generated code ---

template <typename Tensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(Tensor &tensor)
    -> decltype(tensor.data()) {
  return tensor.data();
}


enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void stage_step(__gm__ int8_t* v1, __gm__ int8_t* v2, __gm__ int64_t* v3) {
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  // pto: %c0_i64
  const int64_t v4 = 0;
  // pto: %c8_index
  const int64_t v5 = 8;
  // pto: %c32768_index
  const int64_t v6 = 32768;
  // pto: %c1_index
  const int64_t v7 = 1;
  // pto: %c0_index
  const int64_t v8 = 0;
  // pto: %c16384_index
  const int64_t v9 = 16384;
  // pto: %inp__ssa_v0_view
  const int64_t v10 = 1;
  // pto: %inp__ssa_v0_view
  const int64_t v11 = 1;
  // pto: %inp__ssa_v0_view
  const int64_t v12 = 1;
  // pto: %inp__ssa_v0_view
  int64_t v13 = v5 * v6;
  // pto: %inp__ssa_v0_view
  int64_t v14 = v12 * v13;
  // pto: %inp__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v15 = pto::Shape<1, 1, 1, -1, -1>(v10, v11, v12, v5, v6);
  // pto: %inp__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v16 = pto::Stride<-1, -1, -1, -1, -1>(v11 * v14, v14, v13, v6, v7);
  // pto: %inp__ssa_v0_view
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v17 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v1, v15, v16);
  // pto: %stage__ssa_v0_view
  const int64_t v18 = 1;
  // pto: %stage__ssa_v0_view
  const int64_t v19 = 1;
  // pto: %stage__ssa_v0_view
  const int64_t v20 = 1;
  // pto: %stage__ssa_v0_view
  int64_t v21 = v5 * v6;
  // pto: %stage__ssa_v0_view
  int64_t v22 = v20 * v21;
  // pto: %stage__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v23 = pto::Shape<1, 1, 1, -1, -1>(v18, v19, v20, v5, v6);
  // pto: %stage__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v24 = pto::Stride<-1, -1, -1, -1, -1>(v19 * v22, v22, v21, v6, v7);
  // pto: %stage__ssa_v0_view
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v25 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v2, v23, v24);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  for (int64_t v26 = v8; v26 < v5; v26 += v7) {
    // pto: %tile__ssa_v0
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v27 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v0
    ;
    uint64_t v28 = (uint64_t) v4;
    TASSIGN(v27, v28);
    // pto: %0
    ;
    int64_t v29 = v26 < v8 ? v8 : v26;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v30 = 0;
    // pto: %inp__ssa_v0_pview
    ;
    __gm__ int8_t* v31 = PTOAS__GLOBAL_TENSOR_DATA(v17);
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v32 = 1;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v33 = 1;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v34 = 1;
    // pto: %inp__ssa_v0_pview
    ;
    int64_t v35 = v7 * v6;
    // pto: %inp__ssa_v0_pview
    ;
    int64_t v36 = v34 * v35;
    // pto: %inp__ssa_v0_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v37 = pto::Shape<1, 1, 1, 1, -1>(v32, v33, v34, v7, v9);
    // pto: %inp__ssa_v0_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v38 = pto::Stride<-1, -1, -1, -1, -1>(v33 * v36, v36, v35, v6, v7);
    // pto: %inp__ssa_v0_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v39 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v31 + (v30 + v29 * v6 + v8 * v7), v37, v38);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    TLOAD(v27, v39);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v40 = 0;
    // pto: %stage__iter_v1_pview
    ;
    __gm__ int8_t* v41 = PTOAS__GLOBAL_TENSOR_DATA(v25);
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v42 = 1;
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v43 = 1;
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v44 = 1;
    // pto: %stage__iter_v1_pview
    ;
    int64_t v45 = v7 * v6;
    // pto: %stage__iter_v1_pview
    ;
    int64_t v46 = v44 * v45;
    // pto: %stage__iter_v1_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v47 = pto::Shape<1, 1, 1, 1, -1>(v42, v43, v44, v7, v9);
    // pto: %stage__iter_v1_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v48 = pto::Stride<-1, -1, -1, -1, -1>(v43 * v46, v46, v45, v6, v7);
    // pto: %stage__iter_v1_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v49 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v41 + (v40 + v29 * v6 + v8 * v7), v47, v48);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v49, v27);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    // pto: %2
    ;
    pto::Shape<1, 1, 1, 8, 32768> v50 = pto::Shape<1, 1, 1, 8, 32768>();
    // pto: %2
    ;
    pto::Stride<262144, 262144, 262144, 32768, 1> v51 = pto::Stride<262144, 262144, 262144, 32768, 1>();
    // pto: %2
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 8, 32768>, pto::Stride<262144, 262144, 262144, 32768, 1>, pto::Layout::ND> v52 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 8, 32768>, pto::Stride<262144, 262144, 262144, 32768, 1>, pto::Layout::ND>((__gm__ int8_t*) v2, v50, v51);
    __gm__ int8_t* v53 = PTOAS__GLOBAL_TENSOR_DATA(v52);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v53);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v1
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v54 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v1
    ;
    uint64_t v55 = (uint64_t) v4;
    TASSIGN(v54, v55);
    // pto: %4
    ;
    const int64_t v56 = 0;
    // pto: %4
    ;
    __gm__ int8_t* v57 = PTOAS__GLOBAL_TENSOR_DATA(v17);
    // pto: %4
    ;
    const int64_t v58 = 1;
    // pto: %4
    ;
    const int64_t v59 = 1;
    // pto: %4
    ;
    const int64_t v60 = 1;
    // pto: %4
    ;
    int64_t v61 = v7 * v6;
    // pto: %4
    ;
    int64_t v62 = v60 * v61;
    // pto: %4
    ;
    pto::Shape<1, 1, 1, 1, -1> v63 = pto::Shape<1, 1, 1, 1, -1>(v58, v59, v60, v7, v9);
    // pto: %4
    ;
    pto::Stride<-1, -1, -1, -1, -1> v64 = pto::Stride<-1, -1, -1, -1, -1>(v59 * v62, v62, v61, v6, v7);
    // pto: %4
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v65 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v57 + (v56 + v29 * v6 + v9 * v7), v63, v64);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v54, v65);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID1);
    // pto: %stage__ssa_v3_pview
    ;
    const int64_t v66 = 0;
    // pto: %stage__ssa_v3_pview
    ;
    __gm__ int8_t* v67 = PTOAS__GLOBAL_TENSOR_DATA(v25);
    // pto: %stage__ssa_v3_pview
    ;
    const int64_t v68 = 1;
    // pto: %stage__ssa_v3_pview
    ;
    const int64_t v69 = 1;
    // pto: %stage__ssa_v3_pview
    ;
    const int64_t v70 = 1;
    // pto: %stage__ssa_v3_pview
    ;
    int64_t v71 = v7 * v6;
    // pto: %stage__ssa_v3_pview
    ;
    int64_t v72 = v70 * v71;
    // pto: %stage__ssa_v3_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v73 = pto::Shape<1, 1, 1, 1, -1>(v68, v69, v70, v7, v9);
    // pto: %stage__ssa_v3_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v74 = pto::Stride<-1, -1, -1, -1, -1>(v69 * v72, v72, v71, v6, v7);
    // pto: %stage__ssa_v3_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v75 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v67 + (v66 + v29 * v6 + v9 * v7), v73, v74);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID1);
    TSTORE(v75, v54);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    __gm__ int8_t* v76 = PTOAS__GLOBAL_TENSOR_DATA(v52);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v76);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
  }
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM) && !defined(__COSTMODEL)
    // Reset AI Core atomic mode inherited from a prior kernel.
    set_atomic_none();
#endif

    // Unpack tensor: inp__ssa_v0
    __gm__ Tensor* inp__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ int8_t* inp__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(inp__ssa_v0_tensor->buffer.addr) + inp__ssa_v0_tensor->start_offset;

    // Unpack tensor: stage__ssa_v0
    __gm__ Tensor* stage__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int8_t* stage__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(stage__ssa_v0_tensor->buffer.addr) + stage__ssa_v0_tensor->start_offset;

    // Unpack CommContext: stage_ctx
    __gm__ int64_t* stage_ctx = reinterpret_cast<__gm__ int64_t*>(args[2]);

    // Forward to ptoas-generated function
    stage_step(inp__ssa_v0, stage__ssa_v0, stage_ctx);
}
