// Kernel Function: stage_step
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"



using namespace pto;


// --- ptoas-generated code ---

template <typename Tensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(Tensor &tensor)
    -> decltype(tensor.data()) {
  return tensor.data();
}


enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void stage_step(__gm__ int8_t* v1, __gm__ int8_t* v2, __gm__ int64_t* v3) {
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  // pto: %c0_i64
  const int64_t v4 = 0;
  // pto: %c2_index
  const int64_t v5 = 2;
  // pto: %c524288_index
  const int64_t v6 = 524288;
  // pto: %c1_index
  const int64_t v7 = 1;
  // pto: %c0_index
  const int64_t v8 = 0;
  // pto: %c16384_index
  const int64_t v9 = 16384;
  // pto: %c32768_index
  const int64_t v10 = 32768;
  // pto: %c49152_index
  const int64_t v11 = 49152;
  // pto: %c65536_index
  const int64_t v12 = 65536;
  // pto: %c81920_index
  const int64_t v13 = 81920;
  // pto: %c98304_index
  const int64_t v14 = 98304;
  // pto: %c114688_index
  const int64_t v15 = 114688;
  // pto: %c131072_index
  const int64_t v16 = 131072;
  // pto: %c147456_index
  const int64_t v17 = 147456;
  // pto: %c163840_index
  const int64_t v18 = 163840;
  // pto: %c180224_index
  const int64_t v19 = 180224;
  // pto: %c196608_index
  const int64_t v20 = 196608;
  // pto: %c212992_index
  const int64_t v21 = 212992;
  // pto: %c229376_index
  const int64_t v22 = 229376;
  // pto: %c245760_index
  const int64_t v23 = 245760;
  // pto: %c262144_index
  const int64_t v24 = 262144;
  // pto: %c278528_index
  const int64_t v25 = 278528;
  // pto: %c294912_index
  const int64_t v26 = 294912;
  // pto: %c311296_index
  const int64_t v27 = 311296;
  // pto: %c327680_index
  const int64_t v28 = 327680;
  // pto: %c344064_index
  const int64_t v29 = 344064;
  // pto: %c360448_index
  const int64_t v30 = 360448;
  // pto: %c376832_index
  const int64_t v31 = 376832;
  // pto: %c393216_index
  const int64_t v32 = 393216;
  // pto: %c409600_index
  const int64_t v33 = 409600;
  // pto: %c425984_index
  const int64_t v34 = 425984;
  // pto: %c442368_index
  const int64_t v35 = 442368;
  // pto: %c458752_index
  const int64_t v36 = 458752;
  // pto: %c475136_index
  const int64_t v37 = 475136;
  // pto: %c491520_index
  const int64_t v38 = 491520;
  // pto: %c507904_index
  const int64_t v39 = 507904;
  // pto: %inp__ssa_v0_view
  const int64_t v40 = 1;
  // pto: %inp__ssa_v0_view
  const int64_t v41 = 1;
  // pto: %inp__ssa_v0_view
  const int64_t v42 = 1;
  // pto: %inp__ssa_v0_view
  int64_t v43 = v5 * v6;
  // pto: %inp__ssa_v0_view
  int64_t v44 = v42 * v43;
  // pto: %inp__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v45 = pto::Shape<1, 1, 1, -1, -1>(v40, v41, v42, v5, v6);
  // pto: %inp__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v46 = pto::Stride<-1, -1, -1, -1, -1>(v41 * v44, v44, v43, v6, v7);
  // pto: %inp__ssa_v0_view
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v47 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v1, v45, v46);
  // pto: %stage__ssa_v0_view
  const int64_t v48 = 1;
  // pto: %stage__ssa_v0_view
  const int64_t v49 = 1;
  // pto: %stage__ssa_v0_view
  const int64_t v50 = 1;
  // pto: %stage__ssa_v0_view
  int64_t v51 = v5 * v6;
  // pto: %stage__ssa_v0_view
  int64_t v52 = v50 * v51;
  // pto: %stage__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v53 = pto::Shape<1, 1, 1, -1, -1>(v48, v49, v50, v5, v6);
  // pto: %stage__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v54 = pto::Stride<-1, -1, -1, -1, -1>(v49 * v52, v52, v51, v6, v7);
  // pto: %stage__ssa_v0_view
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v55 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v2, v53, v54);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  for (int64_t v56 = v8; v56 < v5; v56 += v7) {
    // pto: %tile__ssa_v0
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v57 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v0
    ;
    uint64_t v58 = (uint64_t) v4;
    TASSIGN(v57, v58);
    // pto: %0
    ;
    int64_t v59 = v56 < v8 ? v8 : v56;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v60 = 0;
    // pto: %inp__ssa_v0_pview
    ;
    __gm__ int8_t* v61 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v62 = 1;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v63 = 1;
    // pto: %inp__ssa_v0_pview
    ;
    const int64_t v64 = 1;
    // pto: %inp__ssa_v0_pview
    ;
    int64_t v65 = v7 * v6;
    // pto: %inp__ssa_v0_pview
    ;
    int64_t v66 = v64 * v65;
    // pto: %inp__ssa_v0_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v67 = pto::Shape<1, 1, 1, 1, -1>(v62, v63, v64, v7, v9);
    // pto: %inp__ssa_v0_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v68 = pto::Stride<-1, -1, -1, -1, -1>(v63 * v66, v66, v65, v6, v7);
    // pto: %inp__ssa_v0_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v69 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v61 + (v60 + v59 * v6 + v8 * v7), v67, v68);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    TLOAD(v57, v69);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v70 = 0;
    // pto: %stage__iter_v1_pview
    ;
    __gm__ int8_t* v71 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v72 = 1;
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v73 = 1;
    // pto: %stage__iter_v1_pview
    ;
    const int64_t v74 = 1;
    // pto: %stage__iter_v1_pview
    ;
    int64_t v75 = v7 * v6;
    // pto: %stage__iter_v1_pview
    ;
    int64_t v76 = v74 * v75;
    // pto: %stage__iter_v1_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v77 = pto::Shape<1, 1, 1, 1, -1>(v72, v73, v74, v7, v9);
    // pto: %stage__iter_v1_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v78 = pto::Stride<-1, -1, -1, -1, -1>(v73 * v76, v76, v75, v6, v7);
    // pto: %stage__iter_v1_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v79 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v71 + (v70 + v59 * v6 + v8 * v7), v77, v78);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v79, v57);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    // pto: %2
    ;
    pto::Shape<1, 1, 1, 2, 524288> v80 = pto::Shape<1, 1, 1, 2, 524288>();
    // pto: %2
    ;
    pto::Stride<1048576, 1048576, 1048576, 524288, 1> v81 = pto::Stride<1048576, 1048576, 1048576, 524288, 1>();
    // pto: %2
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 2, 524288>, pto::Stride<1048576, 1048576, 1048576, 524288, 1>, pto::Layout::ND> v82 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 2, 524288>, pto::Stride<1048576, 1048576, 1048576, 524288, 1>, pto::Layout::ND>((__gm__ int8_t*) v2, v80, v81);
    __gm__ int8_t* v83 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v83);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v1
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v84 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v1
    ;
    uint64_t v85 = (uint64_t) v4;
    TASSIGN(v84, v85);
    // pto: %4
    ;
    const int64_t v86 = 0;
    // pto: %4
    ;
    __gm__ int8_t* v87 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %4
    ;
    const int64_t v88 = 1;
    // pto: %4
    ;
    const int64_t v89 = 1;
    // pto: %4
    ;
    const int64_t v90 = 1;
    // pto: %4
    ;
    int64_t v91 = v7 * v6;
    // pto: %4
    ;
    int64_t v92 = v90 * v91;
    // pto: %4
    ;
    pto::Shape<1, 1, 1, 1, -1> v93 = pto::Shape<1, 1, 1, 1, -1>(v88, v89, v90, v7, v9);
    // pto: %4
    ;
    pto::Stride<-1, -1, -1, -1, -1> v94 = pto::Stride<-1, -1, -1, -1, -1>(v89 * v92, v92, v91, v6, v7);
    // pto: %4
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v95 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v87 + (v86 + v59 * v6 + v9 * v7), v93, v94);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v84, v95);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID1);
    // pto: %stage__ssa_v3_pview
    ;
    const int64_t v96 = 0;
    // pto: %stage__ssa_v3_pview
    ;
    __gm__ int8_t* v97 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v3_pview
    ;
    const int64_t v98 = 1;
    // pto: %stage__ssa_v3_pview
    ;
    const int64_t v99 = 1;
    // pto: %stage__ssa_v3_pview
    ;
    const int64_t v100 = 1;
    // pto: %stage__ssa_v3_pview
    ;
    int64_t v101 = v7 * v6;
    // pto: %stage__ssa_v3_pview
    ;
    int64_t v102 = v100 * v101;
    // pto: %stage__ssa_v3_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v103 = pto::Shape<1, 1, 1, 1, -1>(v98, v99, v100, v7, v9);
    // pto: %stage__ssa_v3_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v104 = pto::Stride<-1, -1, -1, -1, -1>(v99 * v102, v102, v101, v6, v7);
    // pto: %stage__ssa_v3_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v105 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v97 + (v96 + v59 * v6 + v9 * v7), v103, v104);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID1);
    TSTORE(v105, v84);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
    __gm__ int8_t* v106 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v106);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v2
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v107 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v2
    ;
    uint64_t v108 = (uint64_t) v4;
    TASSIGN(v107, v108);
    // pto: %8
    ;
    const int64_t v109 = 0;
    // pto: %8
    ;
    __gm__ int8_t* v110 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %8
    ;
    const int64_t v111 = 1;
    // pto: %8
    ;
    const int64_t v112 = 1;
    // pto: %8
    ;
    const int64_t v113 = 1;
    // pto: %8
    ;
    int64_t v114 = v7 * v6;
    // pto: %8
    ;
    int64_t v115 = v113 * v114;
    // pto: %8
    ;
    pto::Shape<1, 1, 1, 1, -1> v116 = pto::Shape<1, 1, 1, 1, -1>(v111, v112, v113, v7, v9);
    // pto: %8
    ;
    pto::Stride<-1, -1, -1, -1, -1> v117 = pto::Stride<-1, -1, -1, -1, -1>(v112 * v115, v115, v114, v6, v7);
    // pto: %8
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v118 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v110 + (v109 + v59 * v6 + v10 * v7), v116, v117);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
    TLOAD(v107, v118);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID2);
    // pto: %stage__ssa_v4_pview
    ;
    const int64_t v119 = 0;
    // pto: %stage__ssa_v4_pview
    ;
    __gm__ int8_t* v120 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v4_pview
    ;
    const int64_t v121 = 1;
    // pto: %stage__ssa_v4_pview
    ;
    const int64_t v122 = 1;
    // pto: %stage__ssa_v4_pview
    ;
    const int64_t v123 = 1;
    // pto: %stage__ssa_v4_pview
    ;
    int64_t v124 = v7 * v6;
    // pto: %stage__ssa_v4_pview
    ;
    int64_t v125 = v123 * v124;
    // pto: %stage__ssa_v4_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v126 = pto::Shape<1, 1, 1, 1, -1>(v121, v122, v123, v7, v9);
    // pto: %stage__ssa_v4_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v127 = pto::Stride<-1, -1, -1, -1, -1>(v122 * v125, v125, v124, v6, v7);
    // pto: %stage__ssa_v4_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v128 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v120 + (v119 + v59 * v6 + v10 * v7), v126, v127);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID2);
    TSTORE(v128, v107);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
    __gm__ int8_t* v129 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v129);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v3
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v130 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v3
    ;
    uint64_t v131 = (uint64_t) v4;
    TASSIGN(v130, v131);
    // pto: %12
    ;
    const int64_t v132 = 0;
    // pto: %12
    ;
    __gm__ int8_t* v133 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %12
    ;
    const int64_t v134 = 1;
    // pto: %12
    ;
    const int64_t v135 = 1;
    // pto: %12
    ;
    const int64_t v136 = 1;
    // pto: %12
    ;
    int64_t v137 = v7 * v6;
    // pto: %12
    ;
    int64_t v138 = v136 * v137;
    // pto: %12
    ;
    pto::Shape<1, 1, 1, 1, -1> v139 = pto::Shape<1, 1, 1, 1, -1>(v134, v135, v136, v7, v9);
    // pto: %12
    ;
    pto::Stride<-1, -1, -1, -1, -1> v140 = pto::Stride<-1, -1, -1, -1, -1>(v135 * v138, v138, v137, v6, v7);
    // pto: %12
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v141 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v133 + (v132 + v59 * v6 + v11 * v7), v139, v140);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
    TLOAD(v130, v141);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID3);
    // pto: %stage__ssa_v5_pview
    ;
    const int64_t v142 = 0;
    // pto: %stage__ssa_v5_pview
    ;
    __gm__ int8_t* v143 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v5_pview
    ;
    const int64_t v144 = 1;
    // pto: %stage__ssa_v5_pview
    ;
    const int64_t v145 = 1;
    // pto: %stage__ssa_v5_pview
    ;
    const int64_t v146 = 1;
    // pto: %stage__ssa_v5_pview
    ;
    int64_t v147 = v7 * v6;
    // pto: %stage__ssa_v5_pview
    ;
    int64_t v148 = v146 * v147;
    // pto: %stage__ssa_v5_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v149 = pto::Shape<1, 1, 1, 1, -1>(v144, v145, v146, v7, v9);
    // pto: %stage__ssa_v5_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v150 = pto::Stride<-1, -1, -1, -1, -1>(v145 * v148, v148, v147, v6, v7);
    // pto: %stage__ssa_v5_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v151 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v143 + (v142 + v59 * v6 + v11 * v7), v149, v150);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID3);
    TSTORE(v151, v130);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID4);
    __gm__ int8_t* v152 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v152);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v4
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v153 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v4
    ;
    uint64_t v154 = (uint64_t) v4;
    TASSIGN(v153, v154);
    // pto: %16
    ;
    const int64_t v155 = 0;
    // pto: %16
    ;
    __gm__ int8_t* v156 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %16
    ;
    const int64_t v157 = 1;
    // pto: %16
    ;
    const int64_t v158 = 1;
    // pto: %16
    ;
    const int64_t v159 = 1;
    // pto: %16
    ;
    int64_t v160 = v7 * v6;
    // pto: %16
    ;
    int64_t v161 = v159 * v160;
    // pto: %16
    ;
    pto::Shape<1, 1, 1, 1, -1> v162 = pto::Shape<1, 1, 1, 1, -1>(v157, v158, v159, v7, v9);
    // pto: %16
    ;
    pto::Stride<-1, -1, -1, -1, -1> v163 = pto::Stride<-1, -1, -1, -1, -1>(v158 * v161, v161, v160, v6, v7);
    // pto: %16
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v164 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v156 + (v155 + v59 * v6 + v12 * v7), v162, v163);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID4);
    TLOAD(v153, v164);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID4);
    // pto: %stage__ssa_v6_pview
    ;
    const int64_t v165 = 0;
    // pto: %stage__ssa_v6_pview
    ;
    __gm__ int8_t* v166 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v6_pview
    ;
    const int64_t v167 = 1;
    // pto: %stage__ssa_v6_pview
    ;
    const int64_t v168 = 1;
    // pto: %stage__ssa_v6_pview
    ;
    const int64_t v169 = 1;
    // pto: %stage__ssa_v6_pview
    ;
    int64_t v170 = v7 * v6;
    // pto: %stage__ssa_v6_pview
    ;
    int64_t v171 = v169 * v170;
    // pto: %stage__ssa_v6_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v172 = pto::Shape<1, 1, 1, 1, -1>(v167, v168, v169, v7, v9);
    // pto: %stage__ssa_v6_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v173 = pto::Stride<-1, -1, -1, -1, -1>(v168 * v171, v171, v170, v6, v7);
    // pto: %stage__ssa_v6_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v174 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v166 + (v165 + v59 * v6 + v12 * v7), v172, v173);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID4);
    TSTORE(v174, v153);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID5);
    __gm__ int8_t* v175 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v175);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v5
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v176 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v5
    ;
    uint64_t v177 = (uint64_t) v4;
    TASSIGN(v176, v177);
    // pto: %20
    ;
    const int64_t v178 = 0;
    // pto: %20
    ;
    __gm__ int8_t* v179 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %20
    ;
    const int64_t v180 = 1;
    // pto: %20
    ;
    const int64_t v181 = 1;
    // pto: %20
    ;
    const int64_t v182 = 1;
    // pto: %20
    ;
    int64_t v183 = v7 * v6;
    // pto: %20
    ;
    int64_t v184 = v182 * v183;
    // pto: %20
    ;
    pto::Shape<1, 1, 1, 1, -1> v185 = pto::Shape<1, 1, 1, 1, -1>(v180, v181, v182, v7, v9);
    // pto: %20
    ;
    pto::Stride<-1, -1, -1, -1, -1> v186 = pto::Stride<-1, -1, -1, -1, -1>(v181 * v184, v184, v183, v6, v7);
    // pto: %20
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v187 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v179 + (v178 + v59 * v6 + v13 * v7), v185, v186);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID5);
    TLOAD(v176, v187);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID5);
    // pto: %stage__ssa_v7_pview
    ;
    const int64_t v188 = 0;
    // pto: %stage__ssa_v7_pview
    ;
    __gm__ int8_t* v189 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v7_pview
    ;
    const int64_t v190 = 1;
    // pto: %stage__ssa_v7_pview
    ;
    const int64_t v191 = 1;
    // pto: %stage__ssa_v7_pview
    ;
    const int64_t v192 = 1;
    // pto: %stage__ssa_v7_pview
    ;
    int64_t v193 = v7 * v6;
    // pto: %stage__ssa_v7_pview
    ;
    int64_t v194 = v192 * v193;
    // pto: %stage__ssa_v7_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v195 = pto::Shape<1, 1, 1, 1, -1>(v190, v191, v192, v7, v9);
    // pto: %stage__ssa_v7_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v196 = pto::Stride<-1, -1, -1, -1, -1>(v191 * v194, v194, v193, v6, v7);
    // pto: %stage__ssa_v7_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v197 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v189 + (v188 + v59 * v6 + v13 * v7), v195, v196);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID5);
    TSTORE(v197, v176);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID6);
    __gm__ int8_t* v198 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v198);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v6
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v199 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v6
    ;
    uint64_t v200 = (uint64_t) v4;
    TASSIGN(v199, v200);
    // pto: %24
    ;
    const int64_t v201 = 0;
    // pto: %24
    ;
    __gm__ int8_t* v202 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %24
    ;
    const int64_t v203 = 1;
    // pto: %24
    ;
    const int64_t v204 = 1;
    // pto: %24
    ;
    const int64_t v205 = 1;
    // pto: %24
    ;
    int64_t v206 = v7 * v6;
    // pto: %24
    ;
    int64_t v207 = v205 * v206;
    // pto: %24
    ;
    pto::Shape<1, 1, 1, 1, -1> v208 = pto::Shape<1, 1, 1, 1, -1>(v203, v204, v205, v7, v9);
    // pto: %24
    ;
    pto::Stride<-1, -1, -1, -1, -1> v209 = pto::Stride<-1, -1, -1, -1, -1>(v204 * v207, v207, v206, v6, v7);
    // pto: %24
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v210 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v202 + (v201 + v59 * v6 + v14 * v7), v208, v209);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID6);
    TLOAD(v199, v210);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID6);
    // pto: %stage__ssa_v8_pview
    ;
    const int64_t v211 = 0;
    // pto: %stage__ssa_v8_pview
    ;
    __gm__ int8_t* v212 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v8_pview
    ;
    const int64_t v213 = 1;
    // pto: %stage__ssa_v8_pview
    ;
    const int64_t v214 = 1;
    // pto: %stage__ssa_v8_pview
    ;
    const int64_t v215 = 1;
    // pto: %stage__ssa_v8_pview
    ;
    int64_t v216 = v7 * v6;
    // pto: %stage__ssa_v8_pview
    ;
    int64_t v217 = v215 * v216;
    // pto: %stage__ssa_v8_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v218 = pto::Shape<1, 1, 1, 1, -1>(v213, v214, v215, v7, v9);
    // pto: %stage__ssa_v8_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v219 = pto::Stride<-1, -1, -1, -1, -1>(v214 * v217, v217, v216, v6, v7);
    // pto: %stage__ssa_v8_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v220 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v212 + (v211 + v59 * v6 + v14 * v7), v218, v219);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID6);
    TSTORE(v220, v199);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID7);
    __gm__ int8_t* v221 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v221);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v7
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v222 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v7
    ;
    uint64_t v223 = (uint64_t) v4;
    TASSIGN(v222, v223);
    // pto: %28
    ;
    const int64_t v224 = 0;
    // pto: %28
    ;
    __gm__ int8_t* v225 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %28
    ;
    const int64_t v226 = 1;
    // pto: %28
    ;
    const int64_t v227 = 1;
    // pto: %28
    ;
    const int64_t v228 = 1;
    // pto: %28
    ;
    int64_t v229 = v7 * v6;
    // pto: %28
    ;
    int64_t v230 = v228 * v229;
    // pto: %28
    ;
    pto::Shape<1, 1, 1, 1, -1> v231 = pto::Shape<1, 1, 1, 1, -1>(v226, v227, v228, v7, v9);
    // pto: %28
    ;
    pto::Stride<-1, -1, -1, -1, -1> v232 = pto::Stride<-1, -1, -1, -1, -1>(v227 * v230, v230, v229, v6, v7);
    // pto: %28
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v233 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v225 + (v224 + v59 * v6 + v15 * v7), v231, v232);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID7);
    TLOAD(v222, v233);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID7);
    // pto: %stage__ssa_v9_pview
    ;
    const int64_t v234 = 0;
    // pto: %stage__ssa_v9_pview
    ;
    __gm__ int8_t* v235 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v9_pview
    ;
    const int64_t v236 = 1;
    // pto: %stage__ssa_v9_pview
    ;
    const int64_t v237 = 1;
    // pto: %stage__ssa_v9_pview
    ;
    const int64_t v238 = 1;
    // pto: %stage__ssa_v9_pview
    ;
    int64_t v239 = v7 * v6;
    // pto: %stage__ssa_v9_pview
    ;
    int64_t v240 = v238 * v239;
    // pto: %stage__ssa_v9_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v241 = pto::Shape<1, 1, 1, 1, -1>(v236, v237, v238, v7, v9);
    // pto: %stage__ssa_v9_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v242 = pto::Stride<-1, -1, -1, -1, -1>(v237 * v240, v240, v239, v6, v7);
    // pto: %stage__ssa_v9_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v243 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v235 + (v234 + v59 * v6 + v15 * v7), v241, v242);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID7);
    TSTORE(v243, v222);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v244 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v244);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v8
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v245 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v8
    ;
    uint64_t v246 = (uint64_t) v4;
    TASSIGN(v245, v246);
    // pto: %32
    ;
    const int64_t v247 = 0;
    // pto: %32
    ;
    __gm__ int8_t* v248 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %32
    ;
    const int64_t v249 = 1;
    // pto: %32
    ;
    const int64_t v250 = 1;
    // pto: %32
    ;
    const int64_t v251 = 1;
    // pto: %32
    ;
    int64_t v252 = v7 * v6;
    // pto: %32
    ;
    int64_t v253 = v251 * v252;
    // pto: %32
    ;
    pto::Shape<1, 1, 1, 1, -1> v254 = pto::Shape<1, 1, 1, 1, -1>(v249, v250, v251, v7, v9);
    // pto: %32
    ;
    pto::Stride<-1, -1, -1, -1, -1> v255 = pto::Stride<-1, -1, -1, -1, -1>(v250 * v253, v253, v252, v6, v7);
    // pto: %32
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v256 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v248 + (v247 + v59 * v6 + v16 * v7), v254, v255);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v245, v256);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v10_pview
    ;
    const int64_t v257 = 0;
    // pto: %stage__ssa_v10_pview
    ;
    __gm__ int8_t* v258 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v10_pview
    ;
    const int64_t v259 = 1;
    // pto: %stage__ssa_v10_pview
    ;
    const int64_t v260 = 1;
    // pto: %stage__ssa_v10_pview
    ;
    const int64_t v261 = 1;
    // pto: %stage__ssa_v10_pview
    ;
    int64_t v262 = v7 * v6;
    // pto: %stage__ssa_v10_pview
    ;
    int64_t v263 = v261 * v262;
    // pto: %stage__ssa_v10_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v264 = pto::Shape<1, 1, 1, 1, -1>(v259, v260, v261, v7, v9);
    // pto: %stage__ssa_v10_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v265 = pto::Stride<-1, -1, -1, -1, -1>(v260 * v263, v263, v262, v6, v7);
    // pto: %stage__ssa_v10_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v266 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v258 + (v257 + v59 * v6 + v16 * v7), v264, v265);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v266, v245);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v267 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v267);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v9
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v268 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v9
    ;
    uint64_t v269 = (uint64_t) v4;
    TASSIGN(v268, v269);
    // pto: %36
    ;
    const int64_t v270 = 0;
    // pto: %36
    ;
    __gm__ int8_t* v271 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %36
    ;
    const int64_t v272 = 1;
    // pto: %36
    ;
    const int64_t v273 = 1;
    // pto: %36
    ;
    const int64_t v274 = 1;
    // pto: %36
    ;
    int64_t v275 = v7 * v6;
    // pto: %36
    ;
    int64_t v276 = v274 * v275;
    // pto: %36
    ;
    pto::Shape<1, 1, 1, 1, -1> v277 = pto::Shape<1, 1, 1, 1, -1>(v272, v273, v274, v7, v9);
    // pto: %36
    ;
    pto::Stride<-1, -1, -1, -1, -1> v278 = pto::Stride<-1, -1, -1, -1, -1>(v273 * v276, v276, v275, v6, v7);
    // pto: %36
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v279 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v271 + (v270 + v59 * v6 + v17 * v7), v277, v278);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v268, v279);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v11_pview
    ;
    const int64_t v280 = 0;
    // pto: %stage__ssa_v11_pview
    ;
    __gm__ int8_t* v281 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v11_pview
    ;
    const int64_t v282 = 1;
    // pto: %stage__ssa_v11_pview
    ;
    const int64_t v283 = 1;
    // pto: %stage__ssa_v11_pview
    ;
    const int64_t v284 = 1;
    // pto: %stage__ssa_v11_pview
    ;
    int64_t v285 = v7 * v6;
    // pto: %stage__ssa_v11_pview
    ;
    int64_t v286 = v284 * v285;
    // pto: %stage__ssa_v11_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v287 = pto::Shape<1, 1, 1, 1, -1>(v282, v283, v284, v7, v9);
    // pto: %stage__ssa_v11_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v288 = pto::Stride<-1, -1, -1, -1, -1>(v283 * v286, v286, v285, v6, v7);
    // pto: %stage__ssa_v11_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v289 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v281 + (v280 + v59 * v6 + v17 * v7), v287, v288);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v289, v268);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v290 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v290);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v10
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v291 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v10
    ;
    uint64_t v292 = (uint64_t) v4;
    TASSIGN(v291, v292);
    // pto: %40
    ;
    const int64_t v293 = 0;
    // pto: %40
    ;
    __gm__ int8_t* v294 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %40
    ;
    const int64_t v295 = 1;
    // pto: %40
    ;
    const int64_t v296 = 1;
    // pto: %40
    ;
    const int64_t v297 = 1;
    // pto: %40
    ;
    int64_t v298 = v7 * v6;
    // pto: %40
    ;
    int64_t v299 = v297 * v298;
    // pto: %40
    ;
    pto::Shape<1, 1, 1, 1, -1> v300 = pto::Shape<1, 1, 1, 1, -1>(v295, v296, v297, v7, v9);
    // pto: %40
    ;
    pto::Stride<-1, -1, -1, -1, -1> v301 = pto::Stride<-1, -1, -1, -1, -1>(v296 * v299, v299, v298, v6, v7);
    // pto: %40
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v302 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v294 + (v293 + v59 * v6 + v18 * v7), v300, v301);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v291, v302);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v12_pview
    ;
    const int64_t v303 = 0;
    // pto: %stage__ssa_v12_pview
    ;
    __gm__ int8_t* v304 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v12_pview
    ;
    const int64_t v305 = 1;
    // pto: %stage__ssa_v12_pview
    ;
    const int64_t v306 = 1;
    // pto: %stage__ssa_v12_pview
    ;
    const int64_t v307 = 1;
    // pto: %stage__ssa_v12_pview
    ;
    int64_t v308 = v7 * v6;
    // pto: %stage__ssa_v12_pview
    ;
    int64_t v309 = v307 * v308;
    // pto: %stage__ssa_v12_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v310 = pto::Shape<1, 1, 1, 1, -1>(v305, v306, v307, v7, v9);
    // pto: %stage__ssa_v12_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v311 = pto::Stride<-1, -1, -1, -1, -1>(v306 * v309, v309, v308, v6, v7);
    // pto: %stage__ssa_v12_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v312 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v304 + (v303 + v59 * v6 + v18 * v7), v310, v311);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v312, v291);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v313 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v313);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v11
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v314 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v11
    ;
    uint64_t v315 = (uint64_t) v4;
    TASSIGN(v314, v315);
    // pto: %44
    ;
    const int64_t v316 = 0;
    // pto: %44
    ;
    __gm__ int8_t* v317 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %44
    ;
    const int64_t v318 = 1;
    // pto: %44
    ;
    const int64_t v319 = 1;
    // pto: %44
    ;
    const int64_t v320 = 1;
    // pto: %44
    ;
    int64_t v321 = v7 * v6;
    // pto: %44
    ;
    int64_t v322 = v320 * v321;
    // pto: %44
    ;
    pto::Shape<1, 1, 1, 1, -1> v323 = pto::Shape<1, 1, 1, 1, -1>(v318, v319, v320, v7, v9);
    // pto: %44
    ;
    pto::Stride<-1, -1, -1, -1, -1> v324 = pto::Stride<-1, -1, -1, -1, -1>(v319 * v322, v322, v321, v6, v7);
    // pto: %44
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v325 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v317 + (v316 + v59 * v6 + v19 * v7), v323, v324);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v314, v325);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v13_pview
    ;
    const int64_t v326 = 0;
    // pto: %stage__ssa_v13_pview
    ;
    __gm__ int8_t* v327 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v13_pview
    ;
    const int64_t v328 = 1;
    // pto: %stage__ssa_v13_pview
    ;
    const int64_t v329 = 1;
    // pto: %stage__ssa_v13_pview
    ;
    const int64_t v330 = 1;
    // pto: %stage__ssa_v13_pview
    ;
    int64_t v331 = v7 * v6;
    // pto: %stage__ssa_v13_pview
    ;
    int64_t v332 = v330 * v331;
    // pto: %stage__ssa_v13_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v333 = pto::Shape<1, 1, 1, 1, -1>(v328, v329, v330, v7, v9);
    // pto: %stage__ssa_v13_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v334 = pto::Stride<-1, -1, -1, -1, -1>(v329 * v332, v332, v331, v6, v7);
    // pto: %stage__ssa_v13_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v335 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v327 + (v326 + v59 * v6 + v19 * v7), v333, v334);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v335, v314);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v336 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v336);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v12
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v337 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v12
    ;
    uint64_t v338 = (uint64_t) v4;
    TASSIGN(v337, v338);
    // pto: %48
    ;
    const int64_t v339 = 0;
    // pto: %48
    ;
    __gm__ int8_t* v340 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %48
    ;
    const int64_t v341 = 1;
    // pto: %48
    ;
    const int64_t v342 = 1;
    // pto: %48
    ;
    const int64_t v343 = 1;
    // pto: %48
    ;
    int64_t v344 = v7 * v6;
    // pto: %48
    ;
    int64_t v345 = v343 * v344;
    // pto: %48
    ;
    pto::Shape<1, 1, 1, 1, -1> v346 = pto::Shape<1, 1, 1, 1, -1>(v341, v342, v343, v7, v9);
    // pto: %48
    ;
    pto::Stride<-1, -1, -1, -1, -1> v347 = pto::Stride<-1, -1, -1, -1, -1>(v342 * v345, v345, v344, v6, v7);
    // pto: %48
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v348 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v340 + (v339 + v59 * v6 + v20 * v7), v346, v347);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v337, v348);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v14_pview
    ;
    const int64_t v349 = 0;
    // pto: %stage__ssa_v14_pview
    ;
    __gm__ int8_t* v350 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v14_pview
    ;
    const int64_t v351 = 1;
    // pto: %stage__ssa_v14_pview
    ;
    const int64_t v352 = 1;
    // pto: %stage__ssa_v14_pview
    ;
    const int64_t v353 = 1;
    // pto: %stage__ssa_v14_pview
    ;
    int64_t v354 = v7 * v6;
    // pto: %stage__ssa_v14_pview
    ;
    int64_t v355 = v353 * v354;
    // pto: %stage__ssa_v14_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v356 = pto::Shape<1, 1, 1, 1, -1>(v351, v352, v353, v7, v9);
    // pto: %stage__ssa_v14_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v357 = pto::Stride<-1, -1, -1, -1, -1>(v352 * v355, v355, v354, v6, v7);
    // pto: %stage__ssa_v14_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v358 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v350 + (v349 + v59 * v6 + v20 * v7), v356, v357);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v358, v337);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v359 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v359);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v13
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v360 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v13
    ;
    uint64_t v361 = (uint64_t) v4;
    TASSIGN(v360, v361);
    // pto: %52
    ;
    const int64_t v362 = 0;
    // pto: %52
    ;
    __gm__ int8_t* v363 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %52
    ;
    const int64_t v364 = 1;
    // pto: %52
    ;
    const int64_t v365 = 1;
    // pto: %52
    ;
    const int64_t v366 = 1;
    // pto: %52
    ;
    int64_t v367 = v7 * v6;
    // pto: %52
    ;
    int64_t v368 = v366 * v367;
    // pto: %52
    ;
    pto::Shape<1, 1, 1, 1, -1> v369 = pto::Shape<1, 1, 1, 1, -1>(v364, v365, v366, v7, v9);
    // pto: %52
    ;
    pto::Stride<-1, -1, -1, -1, -1> v370 = pto::Stride<-1, -1, -1, -1, -1>(v365 * v368, v368, v367, v6, v7);
    // pto: %52
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v371 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v363 + (v362 + v59 * v6 + v21 * v7), v369, v370);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v360, v371);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v15_pview
    ;
    const int64_t v372 = 0;
    // pto: %stage__ssa_v15_pview
    ;
    __gm__ int8_t* v373 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v15_pview
    ;
    const int64_t v374 = 1;
    // pto: %stage__ssa_v15_pview
    ;
    const int64_t v375 = 1;
    // pto: %stage__ssa_v15_pview
    ;
    const int64_t v376 = 1;
    // pto: %stage__ssa_v15_pview
    ;
    int64_t v377 = v7 * v6;
    // pto: %stage__ssa_v15_pview
    ;
    int64_t v378 = v376 * v377;
    // pto: %stage__ssa_v15_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v379 = pto::Shape<1, 1, 1, 1, -1>(v374, v375, v376, v7, v9);
    // pto: %stage__ssa_v15_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v380 = pto::Stride<-1, -1, -1, -1, -1>(v375 * v378, v378, v377, v6, v7);
    // pto: %stage__ssa_v15_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v381 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v373 + (v372 + v59 * v6 + v21 * v7), v379, v380);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v381, v360);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v382 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v382);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v14
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v383 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v14
    ;
    uint64_t v384 = (uint64_t) v4;
    TASSIGN(v383, v384);
    // pto: %56
    ;
    const int64_t v385 = 0;
    // pto: %56
    ;
    __gm__ int8_t* v386 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %56
    ;
    const int64_t v387 = 1;
    // pto: %56
    ;
    const int64_t v388 = 1;
    // pto: %56
    ;
    const int64_t v389 = 1;
    // pto: %56
    ;
    int64_t v390 = v7 * v6;
    // pto: %56
    ;
    int64_t v391 = v389 * v390;
    // pto: %56
    ;
    pto::Shape<1, 1, 1, 1, -1> v392 = pto::Shape<1, 1, 1, 1, -1>(v387, v388, v389, v7, v9);
    // pto: %56
    ;
    pto::Stride<-1, -1, -1, -1, -1> v393 = pto::Stride<-1, -1, -1, -1, -1>(v388 * v391, v391, v390, v6, v7);
    // pto: %56
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v394 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v386 + (v385 + v59 * v6 + v22 * v7), v392, v393);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v383, v394);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v16_pview
    ;
    const int64_t v395 = 0;
    // pto: %stage__ssa_v16_pview
    ;
    __gm__ int8_t* v396 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v16_pview
    ;
    const int64_t v397 = 1;
    // pto: %stage__ssa_v16_pview
    ;
    const int64_t v398 = 1;
    // pto: %stage__ssa_v16_pview
    ;
    const int64_t v399 = 1;
    // pto: %stage__ssa_v16_pview
    ;
    int64_t v400 = v7 * v6;
    // pto: %stage__ssa_v16_pview
    ;
    int64_t v401 = v399 * v400;
    // pto: %stage__ssa_v16_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v402 = pto::Shape<1, 1, 1, 1, -1>(v397, v398, v399, v7, v9);
    // pto: %stage__ssa_v16_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v403 = pto::Stride<-1, -1, -1, -1, -1>(v398 * v401, v401, v400, v6, v7);
    // pto: %stage__ssa_v16_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v404 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v396 + (v395 + v59 * v6 + v22 * v7), v402, v403);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v404, v383);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v405 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v405);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v15
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v406 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v15
    ;
    uint64_t v407 = (uint64_t) v4;
    TASSIGN(v406, v407);
    // pto: %60
    ;
    const int64_t v408 = 0;
    // pto: %60
    ;
    __gm__ int8_t* v409 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %60
    ;
    const int64_t v410 = 1;
    // pto: %60
    ;
    const int64_t v411 = 1;
    // pto: %60
    ;
    const int64_t v412 = 1;
    // pto: %60
    ;
    int64_t v413 = v7 * v6;
    // pto: %60
    ;
    int64_t v414 = v412 * v413;
    // pto: %60
    ;
    pto::Shape<1, 1, 1, 1, -1> v415 = pto::Shape<1, 1, 1, 1, -1>(v410, v411, v412, v7, v9);
    // pto: %60
    ;
    pto::Stride<-1, -1, -1, -1, -1> v416 = pto::Stride<-1, -1, -1, -1, -1>(v411 * v414, v414, v413, v6, v7);
    // pto: %60
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v417 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v409 + (v408 + v59 * v6 + v23 * v7), v415, v416);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v406, v417);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v17_pview
    ;
    const int64_t v418 = 0;
    // pto: %stage__ssa_v17_pview
    ;
    __gm__ int8_t* v419 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v17_pview
    ;
    const int64_t v420 = 1;
    // pto: %stage__ssa_v17_pview
    ;
    const int64_t v421 = 1;
    // pto: %stage__ssa_v17_pview
    ;
    const int64_t v422 = 1;
    // pto: %stage__ssa_v17_pview
    ;
    int64_t v423 = v7 * v6;
    // pto: %stage__ssa_v17_pview
    ;
    int64_t v424 = v422 * v423;
    // pto: %stage__ssa_v17_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v425 = pto::Shape<1, 1, 1, 1, -1>(v420, v421, v422, v7, v9);
    // pto: %stage__ssa_v17_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v426 = pto::Stride<-1, -1, -1, -1, -1>(v421 * v424, v424, v423, v6, v7);
    // pto: %stage__ssa_v17_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v427 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v419 + (v418 + v59 * v6 + v23 * v7), v425, v426);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v427, v406);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v428 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v428);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v16
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v429 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v16
    ;
    uint64_t v430 = (uint64_t) v4;
    TASSIGN(v429, v430);
    // pto: %64
    ;
    const int64_t v431 = 0;
    // pto: %64
    ;
    __gm__ int8_t* v432 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %64
    ;
    const int64_t v433 = 1;
    // pto: %64
    ;
    const int64_t v434 = 1;
    // pto: %64
    ;
    const int64_t v435 = 1;
    // pto: %64
    ;
    int64_t v436 = v7 * v6;
    // pto: %64
    ;
    int64_t v437 = v435 * v436;
    // pto: %64
    ;
    pto::Shape<1, 1, 1, 1, -1> v438 = pto::Shape<1, 1, 1, 1, -1>(v433, v434, v435, v7, v9);
    // pto: %64
    ;
    pto::Stride<-1, -1, -1, -1, -1> v439 = pto::Stride<-1, -1, -1, -1, -1>(v434 * v437, v437, v436, v6, v7);
    // pto: %64
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v440 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v432 + (v431 + v59 * v6 + v24 * v7), v438, v439);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v429, v440);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v18_pview
    ;
    const int64_t v441 = 0;
    // pto: %stage__ssa_v18_pview
    ;
    __gm__ int8_t* v442 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v18_pview
    ;
    const int64_t v443 = 1;
    // pto: %stage__ssa_v18_pview
    ;
    const int64_t v444 = 1;
    // pto: %stage__ssa_v18_pview
    ;
    const int64_t v445 = 1;
    // pto: %stage__ssa_v18_pview
    ;
    int64_t v446 = v7 * v6;
    // pto: %stage__ssa_v18_pview
    ;
    int64_t v447 = v445 * v446;
    // pto: %stage__ssa_v18_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v448 = pto::Shape<1, 1, 1, 1, -1>(v443, v444, v445, v7, v9);
    // pto: %stage__ssa_v18_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v449 = pto::Stride<-1, -1, -1, -1, -1>(v444 * v447, v447, v446, v6, v7);
    // pto: %stage__ssa_v18_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v450 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v442 + (v441 + v59 * v6 + v24 * v7), v448, v449);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v450, v429);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v451 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v451);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v17
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v452 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v17
    ;
    uint64_t v453 = (uint64_t) v4;
    TASSIGN(v452, v453);
    // pto: %68
    ;
    const int64_t v454 = 0;
    // pto: %68
    ;
    __gm__ int8_t* v455 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %68
    ;
    const int64_t v456 = 1;
    // pto: %68
    ;
    const int64_t v457 = 1;
    // pto: %68
    ;
    const int64_t v458 = 1;
    // pto: %68
    ;
    int64_t v459 = v7 * v6;
    // pto: %68
    ;
    int64_t v460 = v458 * v459;
    // pto: %68
    ;
    pto::Shape<1, 1, 1, 1, -1> v461 = pto::Shape<1, 1, 1, 1, -1>(v456, v457, v458, v7, v9);
    // pto: %68
    ;
    pto::Stride<-1, -1, -1, -1, -1> v462 = pto::Stride<-1, -1, -1, -1, -1>(v457 * v460, v460, v459, v6, v7);
    // pto: %68
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v463 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v455 + (v454 + v59 * v6 + v25 * v7), v461, v462);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v452, v463);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v19_pview
    ;
    const int64_t v464 = 0;
    // pto: %stage__ssa_v19_pview
    ;
    __gm__ int8_t* v465 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v19_pview
    ;
    const int64_t v466 = 1;
    // pto: %stage__ssa_v19_pview
    ;
    const int64_t v467 = 1;
    // pto: %stage__ssa_v19_pview
    ;
    const int64_t v468 = 1;
    // pto: %stage__ssa_v19_pview
    ;
    int64_t v469 = v7 * v6;
    // pto: %stage__ssa_v19_pview
    ;
    int64_t v470 = v468 * v469;
    // pto: %stage__ssa_v19_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v471 = pto::Shape<1, 1, 1, 1, -1>(v466, v467, v468, v7, v9);
    // pto: %stage__ssa_v19_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v472 = pto::Stride<-1, -1, -1, -1, -1>(v467 * v470, v470, v469, v6, v7);
    // pto: %stage__ssa_v19_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v473 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v465 + (v464 + v59 * v6 + v25 * v7), v471, v472);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v473, v452);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v474 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v474);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v18
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v475 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v18
    ;
    uint64_t v476 = (uint64_t) v4;
    TASSIGN(v475, v476);
    // pto: %72
    ;
    const int64_t v477 = 0;
    // pto: %72
    ;
    __gm__ int8_t* v478 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %72
    ;
    const int64_t v479 = 1;
    // pto: %72
    ;
    const int64_t v480 = 1;
    // pto: %72
    ;
    const int64_t v481 = 1;
    // pto: %72
    ;
    int64_t v482 = v7 * v6;
    // pto: %72
    ;
    int64_t v483 = v481 * v482;
    // pto: %72
    ;
    pto::Shape<1, 1, 1, 1, -1> v484 = pto::Shape<1, 1, 1, 1, -1>(v479, v480, v481, v7, v9);
    // pto: %72
    ;
    pto::Stride<-1, -1, -1, -1, -1> v485 = pto::Stride<-1, -1, -1, -1, -1>(v480 * v483, v483, v482, v6, v7);
    // pto: %72
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v486 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v478 + (v477 + v59 * v6 + v26 * v7), v484, v485);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v475, v486);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v20_pview
    ;
    const int64_t v487 = 0;
    // pto: %stage__ssa_v20_pview
    ;
    __gm__ int8_t* v488 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v20_pview
    ;
    const int64_t v489 = 1;
    // pto: %stage__ssa_v20_pview
    ;
    const int64_t v490 = 1;
    // pto: %stage__ssa_v20_pview
    ;
    const int64_t v491 = 1;
    // pto: %stage__ssa_v20_pview
    ;
    int64_t v492 = v7 * v6;
    // pto: %stage__ssa_v20_pview
    ;
    int64_t v493 = v491 * v492;
    // pto: %stage__ssa_v20_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v494 = pto::Shape<1, 1, 1, 1, -1>(v489, v490, v491, v7, v9);
    // pto: %stage__ssa_v20_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v495 = pto::Stride<-1, -1, -1, -1, -1>(v490 * v493, v493, v492, v6, v7);
    // pto: %stage__ssa_v20_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v496 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v488 + (v487 + v59 * v6 + v26 * v7), v494, v495);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v496, v475);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v497 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v497);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v19
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v498 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v19
    ;
    uint64_t v499 = (uint64_t) v4;
    TASSIGN(v498, v499);
    // pto: %76
    ;
    const int64_t v500 = 0;
    // pto: %76
    ;
    __gm__ int8_t* v501 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %76
    ;
    const int64_t v502 = 1;
    // pto: %76
    ;
    const int64_t v503 = 1;
    // pto: %76
    ;
    const int64_t v504 = 1;
    // pto: %76
    ;
    int64_t v505 = v7 * v6;
    // pto: %76
    ;
    int64_t v506 = v504 * v505;
    // pto: %76
    ;
    pto::Shape<1, 1, 1, 1, -1> v507 = pto::Shape<1, 1, 1, 1, -1>(v502, v503, v504, v7, v9);
    // pto: %76
    ;
    pto::Stride<-1, -1, -1, -1, -1> v508 = pto::Stride<-1, -1, -1, -1, -1>(v503 * v506, v506, v505, v6, v7);
    // pto: %76
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v509 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v501 + (v500 + v59 * v6 + v27 * v7), v507, v508);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v498, v509);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v21_pview
    ;
    const int64_t v510 = 0;
    // pto: %stage__ssa_v21_pview
    ;
    __gm__ int8_t* v511 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v21_pview
    ;
    const int64_t v512 = 1;
    // pto: %stage__ssa_v21_pview
    ;
    const int64_t v513 = 1;
    // pto: %stage__ssa_v21_pview
    ;
    const int64_t v514 = 1;
    // pto: %stage__ssa_v21_pview
    ;
    int64_t v515 = v7 * v6;
    // pto: %stage__ssa_v21_pview
    ;
    int64_t v516 = v514 * v515;
    // pto: %stage__ssa_v21_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v517 = pto::Shape<1, 1, 1, 1, -1>(v512, v513, v514, v7, v9);
    // pto: %stage__ssa_v21_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v518 = pto::Stride<-1, -1, -1, -1, -1>(v513 * v516, v516, v515, v6, v7);
    // pto: %stage__ssa_v21_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v519 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v511 + (v510 + v59 * v6 + v27 * v7), v517, v518);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v519, v498);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v520 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v520);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v20
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v521 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v20
    ;
    uint64_t v522 = (uint64_t) v4;
    TASSIGN(v521, v522);
    // pto: %80
    ;
    const int64_t v523 = 0;
    // pto: %80
    ;
    __gm__ int8_t* v524 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %80
    ;
    const int64_t v525 = 1;
    // pto: %80
    ;
    const int64_t v526 = 1;
    // pto: %80
    ;
    const int64_t v527 = 1;
    // pto: %80
    ;
    int64_t v528 = v7 * v6;
    // pto: %80
    ;
    int64_t v529 = v527 * v528;
    // pto: %80
    ;
    pto::Shape<1, 1, 1, 1, -1> v530 = pto::Shape<1, 1, 1, 1, -1>(v525, v526, v527, v7, v9);
    // pto: %80
    ;
    pto::Stride<-1, -1, -1, -1, -1> v531 = pto::Stride<-1, -1, -1, -1, -1>(v526 * v529, v529, v528, v6, v7);
    // pto: %80
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v532 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v524 + (v523 + v59 * v6 + v28 * v7), v530, v531);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v521, v532);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v22_pview
    ;
    const int64_t v533 = 0;
    // pto: %stage__ssa_v22_pview
    ;
    __gm__ int8_t* v534 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v22_pview
    ;
    const int64_t v535 = 1;
    // pto: %stage__ssa_v22_pview
    ;
    const int64_t v536 = 1;
    // pto: %stage__ssa_v22_pview
    ;
    const int64_t v537 = 1;
    // pto: %stage__ssa_v22_pview
    ;
    int64_t v538 = v7 * v6;
    // pto: %stage__ssa_v22_pview
    ;
    int64_t v539 = v537 * v538;
    // pto: %stage__ssa_v22_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v540 = pto::Shape<1, 1, 1, 1, -1>(v535, v536, v537, v7, v9);
    // pto: %stage__ssa_v22_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v541 = pto::Stride<-1, -1, -1, -1, -1>(v536 * v539, v539, v538, v6, v7);
    // pto: %stage__ssa_v22_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v542 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v534 + (v533 + v59 * v6 + v28 * v7), v540, v541);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v542, v521);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v543 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v543);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v21
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v544 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v21
    ;
    uint64_t v545 = (uint64_t) v4;
    TASSIGN(v544, v545);
    // pto: %84
    ;
    const int64_t v546 = 0;
    // pto: %84
    ;
    __gm__ int8_t* v547 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %84
    ;
    const int64_t v548 = 1;
    // pto: %84
    ;
    const int64_t v549 = 1;
    // pto: %84
    ;
    const int64_t v550 = 1;
    // pto: %84
    ;
    int64_t v551 = v7 * v6;
    // pto: %84
    ;
    int64_t v552 = v550 * v551;
    // pto: %84
    ;
    pto::Shape<1, 1, 1, 1, -1> v553 = pto::Shape<1, 1, 1, 1, -1>(v548, v549, v550, v7, v9);
    // pto: %84
    ;
    pto::Stride<-1, -1, -1, -1, -1> v554 = pto::Stride<-1, -1, -1, -1, -1>(v549 * v552, v552, v551, v6, v7);
    // pto: %84
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v555 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v547 + (v546 + v59 * v6 + v29 * v7), v553, v554);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v544, v555);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v23_pview
    ;
    const int64_t v556 = 0;
    // pto: %stage__ssa_v23_pview
    ;
    __gm__ int8_t* v557 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v23_pview
    ;
    const int64_t v558 = 1;
    // pto: %stage__ssa_v23_pview
    ;
    const int64_t v559 = 1;
    // pto: %stage__ssa_v23_pview
    ;
    const int64_t v560 = 1;
    // pto: %stage__ssa_v23_pview
    ;
    int64_t v561 = v7 * v6;
    // pto: %stage__ssa_v23_pview
    ;
    int64_t v562 = v560 * v561;
    // pto: %stage__ssa_v23_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v563 = pto::Shape<1, 1, 1, 1, -1>(v558, v559, v560, v7, v9);
    // pto: %stage__ssa_v23_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v564 = pto::Stride<-1, -1, -1, -1, -1>(v559 * v562, v562, v561, v6, v7);
    // pto: %stage__ssa_v23_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v565 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v557 + (v556 + v59 * v6 + v29 * v7), v563, v564);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v565, v544);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v566 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v566);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v22
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v567 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v22
    ;
    uint64_t v568 = (uint64_t) v4;
    TASSIGN(v567, v568);
    // pto: %88
    ;
    const int64_t v569 = 0;
    // pto: %88
    ;
    __gm__ int8_t* v570 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %88
    ;
    const int64_t v571 = 1;
    // pto: %88
    ;
    const int64_t v572 = 1;
    // pto: %88
    ;
    const int64_t v573 = 1;
    // pto: %88
    ;
    int64_t v574 = v7 * v6;
    // pto: %88
    ;
    int64_t v575 = v573 * v574;
    // pto: %88
    ;
    pto::Shape<1, 1, 1, 1, -1> v576 = pto::Shape<1, 1, 1, 1, -1>(v571, v572, v573, v7, v9);
    // pto: %88
    ;
    pto::Stride<-1, -1, -1, -1, -1> v577 = pto::Stride<-1, -1, -1, -1, -1>(v572 * v575, v575, v574, v6, v7);
    // pto: %88
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v578 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v570 + (v569 + v59 * v6 + v30 * v7), v576, v577);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v567, v578);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v24_pview
    ;
    const int64_t v579 = 0;
    // pto: %stage__ssa_v24_pview
    ;
    __gm__ int8_t* v580 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v24_pview
    ;
    const int64_t v581 = 1;
    // pto: %stage__ssa_v24_pview
    ;
    const int64_t v582 = 1;
    // pto: %stage__ssa_v24_pview
    ;
    const int64_t v583 = 1;
    // pto: %stage__ssa_v24_pview
    ;
    int64_t v584 = v7 * v6;
    // pto: %stage__ssa_v24_pview
    ;
    int64_t v585 = v583 * v584;
    // pto: %stage__ssa_v24_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v586 = pto::Shape<1, 1, 1, 1, -1>(v581, v582, v583, v7, v9);
    // pto: %stage__ssa_v24_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v587 = pto::Stride<-1, -1, -1, -1, -1>(v582 * v585, v585, v584, v6, v7);
    // pto: %stage__ssa_v24_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v588 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v580 + (v579 + v59 * v6 + v30 * v7), v586, v587);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v588, v567);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v589 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v589);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v23
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v590 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v23
    ;
    uint64_t v591 = (uint64_t) v4;
    TASSIGN(v590, v591);
    // pto: %92
    ;
    const int64_t v592 = 0;
    // pto: %92
    ;
    __gm__ int8_t* v593 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %92
    ;
    const int64_t v594 = 1;
    // pto: %92
    ;
    const int64_t v595 = 1;
    // pto: %92
    ;
    const int64_t v596 = 1;
    // pto: %92
    ;
    int64_t v597 = v7 * v6;
    // pto: %92
    ;
    int64_t v598 = v596 * v597;
    // pto: %92
    ;
    pto::Shape<1, 1, 1, 1, -1> v599 = pto::Shape<1, 1, 1, 1, -1>(v594, v595, v596, v7, v9);
    // pto: %92
    ;
    pto::Stride<-1, -1, -1, -1, -1> v600 = pto::Stride<-1, -1, -1, -1, -1>(v595 * v598, v598, v597, v6, v7);
    // pto: %92
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v601 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v593 + (v592 + v59 * v6 + v31 * v7), v599, v600);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v590, v601);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v25_pview
    ;
    const int64_t v602 = 0;
    // pto: %stage__ssa_v25_pview
    ;
    __gm__ int8_t* v603 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v25_pview
    ;
    const int64_t v604 = 1;
    // pto: %stage__ssa_v25_pview
    ;
    const int64_t v605 = 1;
    // pto: %stage__ssa_v25_pview
    ;
    const int64_t v606 = 1;
    // pto: %stage__ssa_v25_pview
    ;
    int64_t v607 = v7 * v6;
    // pto: %stage__ssa_v25_pview
    ;
    int64_t v608 = v606 * v607;
    // pto: %stage__ssa_v25_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v609 = pto::Shape<1, 1, 1, 1, -1>(v604, v605, v606, v7, v9);
    // pto: %stage__ssa_v25_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v610 = pto::Stride<-1, -1, -1, -1, -1>(v605 * v608, v608, v607, v6, v7);
    // pto: %stage__ssa_v25_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v611 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v603 + (v602 + v59 * v6 + v31 * v7), v609, v610);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v611, v590);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v612 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v612);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v24
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v613 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v24
    ;
    uint64_t v614 = (uint64_t) v4;
    TASSIGN(v613, v614);
    // pto: %96
    ;
    const int64_t v615 = 0;
    // pto: %96
    ;
    __gm__ int8_t* v616 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %96
    ;
    const int64_t v617 = 1;
    // pto: %96
    ;
    const int64_t v618 = 1;
    // pto: %96
    ;
    const int64_t v619 = 1;
    // pto: %96
    ;
    int64_t v620 = v7 * v6;
    // pto: %96
    ;
    int64_t v621 = v619 * v620;
    // pto: %96
    ;
    pto::Shape<1, 1, 1, 1, -1> v622 = pto::Shape<1, 1, 1, 1, -1>(v617, v618, v619, v7, v9);
    // pto: %96
    ;
    pto::Stride<-1, -1, -1, -1, -1> v623 = pto::Stride<-1, -1, -1, -1, -1>(v618 * v621, v621, v620, v6, v7);
    // pto: %96
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v624 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v616 + (v615 + v59 * v6 + v32 * v7), v622, v623);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v613, v624);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v26_pview
    ;
    const int64_t v625 = 0;
    // pto: %stage__ssa_v26_pview
    ;
    __gm__ int8_t* v626 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v26_pview
    ;
    const int64_t v627 = 1;
    // pto: %stage__ssa_v26_pview
    ;
    const int64_t v628 = 1;
    // pto: %stage__ssa_v26_pview
    ;
    const int64_t v629 = 1;
    // pto: %stage__ssa_v26_pview
    ;
    int64_t v630 = v7 * v6;
    // pto: %stage__ssa_v26_pview
    ;
    int64_t v631 = v629 * v630;
    // pto: %stage__ssa_v26_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v632 = pto::Shape<1, 1, 1, 1, -1>(v627, v628, v629, v7, v9);
    // pto: %stage__ssa_v26_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v633 = pto::Stride<-1, -1, -1, -1, -1>(v628 * v631, v631, v630, v6, v7);
    // pto: %stage__ssa_v26_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v634 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v626 + (v625 + v59 * v6 + v32 * v7), v632, v633);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v634, v613);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v635 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v635);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v25
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v636 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v25
    ;
    uint64_t v637 = (uint64_t) v4;
    TASSIGN(v636, v637);
    // pto: %100
    ;
    const int64_t v638 = 0;
    // pto: %100
    ;
    __gm__ int8_t* v639 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %100
    ;
    const int64_t v640 = 1;
    // pto: %100
    ;
    const int64_t v641 = 1;
    // pto: %100
    ;
    const int64_t v642 = 1;
    // pto: %100
    ;
    int64_t v643 = v7 * v6;
    // pto: %100
    ;
    int64_t v644 = v642 * v643;
    // pto: %100
    ;
    pto::Shape<1, 1, 1, 1, -1> v645 = pto::Shape<1, 1, 1, 1, -1>(v640, v641, v642, v7, v9);
    // pto: %100
    ;
    pto::Stride<-1, -1, -1, -1, -1> v646 = pto::Stride<-1, -1, -1, -1, -1>(v641 * v644, v644, v643, v6, v7);
    // pto: %100
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v647 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v639 + (v638 + v59 * v6 + v33 * v7), v645, v646);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v636, v647);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v27_pview
    ;
    const int64_t v648 = 0;
    // pto: %stage__ssa_v27_pview
    ;
    __gm__ int8_t* v649 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v27_pview
    ;
    const int64_t v650 = 1;
    // pto: %stage__ssa_v27_pview
    ;
    const int64_t v651 = 1;
    // pto: %stage__ssa_v27_pview
    ;
    const int64_t v652 = 1;
    // pto: %stage__ssa_v27_pview
    ;
    int64_t v653 = v7 * v6;
    // pto: %stage__ssa_v27_pview
    ;
    int64_t v654 = v652 * v653;
    // pto: %stage__ssa_v27_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v655 = pto::Shape<1, 1, 1, 1, -1>(v650, v651, v652, v7, v9);
    // pto: %stage__ssa_v27_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v656 = pto::Stride<-1, -1, -1, -1, -1>(v651 * v654, v654, v653, v6, v7);
    // pto: %stage__ssa_v27_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v657 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v649 + (v648 + v59 * v6 + v33 * v7), v655, v656);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v657, v636);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v658 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v658);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v26
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v659 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v26
    ;
    uint64_t v660 = (uint64_t) v4;
    TASSIGN(v659, v660);
    // pto: %104
    ;
    const int64_t v661 = 0;
    // pto: %104
    ;
    __gm__ int8_t* v662 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %104
    ;
    const int64_t v663 = 1;
    // pto: %104
    ;
    const int64_t v664 = 1;
    // pto: %104
    ;
    const int64_t v665 = 1;
    // pto: %104
    ;
    int64_t v666 = v7 * v6;
    // pto: %104
    ;
    int64_t v667 = v665 * v666;
    // pto: %104
    ;
    pto::Shape<1, 1, 1, 1, -1> v668 = pto::Shape<1, 1, 1, 1, -1>(v663, v664, v665, v7, v9);
    // pto: %104
    ;
    pto::Stride<-1, -1, -1, -1, -1> v669 = pto::Stride<-1, -1, -1, -1, -1>(v664 * v667, v667, v666, v6, v7);
    // pto: %104
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v670 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v662 + (v661 + v59 * v6 + v34 * v7), v668, v669);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v659, v670);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v28_pview
    ;
    const int64_t v671 = 0;
    // pto: %stage__ssa_v28_pview
    ;
    __gm__ int8_t* v672 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v28_pview
    ;
    const int64_t v673 = 1;
    // pto: %stage__ssa_v28_pview
    ;
    const int64_t v674 = 1;
    // pto: %stage__ssa_v28_pview
    ;
    const int64_t v675 = 1;
    // pto: %stage__ssa_v28_pview
    ;
    int64_t v676 = v7 * v6;
    // pto: %stage__ssa_v28_pview
    ;
    int64_t v677 = v675 * v676;
    // pto: %stage__ssa_v28_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v678 = pto::Shape<1, 1, 1, 1, -1>(v673, v674, v675, v7, v9);
    // pto: %stage__ssa_v28_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v679 = pto::Stride<-1, -1, -1, -1, -1>(v674 * v677, v677, v676, v6, v7);
    // pto: %stage__ssa_v28_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v680 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v672 + (v671 + v59 * v6 + v34 * v7), v678, v679);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v680, v659);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v681 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v681);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v27
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v682 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v27
    ;
    uint64_t v683 = (uint64_t) v4;
    TASSIGN(v682, v683);
    // pto: %108
    ;
    const int64_t v684 = 0;
    // pto: %108
    ;
    __gm__ int8_t* v685 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %108
    ;
    const int64_t v686 = 1;
    // pto: %108
    ;
    const int64_t v687 = 1;
    // pto: %108
    ;
    const int64_t v688 = 1;
    // pto: %108
    ;
    int64_t v689 = v7 * v6;
    // pto: %108
    ;
    int64_t v690 = v688 * v689;
    // pto: %108
    ;
    pto::Shape<1, 1, 1, 1, -1> v691 = pto::Shape<1, 1, 1, 1, -1>(v686, v687, v688, v7, v9);
    // pto: %108
    ;
    pto::Stride<-1, -1, -1, -1, -1> v692 = pto::Stride<-1, -1, -1, -1, -1>(v687 * v690, v690, v689, v6, v7);
    // pto: %108
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v693 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v685 + (v684 + v59 * v6 + v35 * v7), v691, v692);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v682, v693);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v29_pview
    ;
    const int64_t v694 = 0;
    // pto: %stage__ssa_v29_pview
    ;
    __gm__ int8_t* v695 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v29_pview
    ;
    const int64_t v696 = 1;
    // pto: %stage__ssa_v29_pview
    ;
    const int64_t v697 = 1;
    // pto: %stage__ssa_v29_pview
    ;
    const int64_t v698 = 1;
    // pto: %stage__ssa_v29_pview
    ;
    int64_t v699 = v7 * v6;
    // pto: %stage__ssa_v29_pview
    ;
    int64_t v700 = v698 * v699;
    // pto: %stage__ssa_v29_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v701 = pto::Shape<1, 1, 1, 1, -1>(v696, v697, v698, v7, v9);
    // pto: %stage__ssa_v29_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v702 = pto::Stride<-1, -1, -1, -1, -1>(v697 * v700, v700, v699, v6, v7);
    // pto: %stage__ssa_v29_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v703 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v695 + (v694 + v59 * v6 + v35 * v7), v701, v702);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v703, v682);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v704 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v704);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v28
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v705 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v28
    ;
    uint64_t v706 = (uint64_t) v4;
    TASSIGN(v705, v706);
    // pto: %112
    ;
    const int64_t v707 = 0;
    // pto: %112
    ;
    __gm__ int8_t* v708 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %112
    ;
    const int64_t v709 = 1;
    // pto: %112
    ;
    const int64_t v710 = 1;
    // pto: %112
    ;
    const int64_t v711 = 1;
    // pto: %112
    ;
    int64_t v712 = v7 * v6;
    // pto: %112
    ;
    int64_t v713 = v711 * v712;
    // pto: %112
    ;
    pto::Shape<1, 1, 1, 1, -1> v714 = pto::Shape<1, 1, 1, 1, -1>(v709, v710, v711, v7, v9);
    // pto: %112
    ;
    pto::Stride<-1, -1, -1, -1, -1> v715 = pto::Stride<-1, -1, -1, -1, -1>(v710 * v713, v713, v712, v6, v7);
    // pto: %112
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v716 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v708 + (v707 + v59 * v6 + v36 * v7), v714, v715);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v705, v716);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v30_pview
    ;
    const int64_t v717 = 0;
    // pto: %stage__ssa_v30_pview
    ;
    __gm__ int8_t* v718 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v30_pview
    ;
    const int64_t v719 = 1;
    // pto: %stage__ssa_v30_pview
    ;
    const int64_t v720 = 1;
    // pto: %stage__ssa_v30_pview
    ;
    const int64_t v721 = 1;
    // pto: %stage__ssa_v30_pview
    ;
    int64_t v722 = v7 * v6;
    // pto: %stage__ssa_v30_pview
    ;
    int64_t v723 = v721 * v722;
    // pto: %stage__ssa_v30_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v724 = pto::Shape<1, 1, 1, 1, -1>(v719, v720, v721, v7, v9);
    // pto: %stage__ssa_v30_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v725 = pto::Stride<-1, -1, -1, -1, -1>(v720 * v723, v723, v722, v6, v7);
    // pto: %stage__ssa_v30_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v726 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v718 + (v717 + v59 * v6 + v36 * v7), v724, v725);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v726, v705);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v727 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v727);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v29
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v728 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v29
    ;
    uint64_t v729 = (uint64_t) v4;
    TASSIGN(v728, v729);
    // pto: %116
    ;
    const int64_t v730 = 0;
    // pto: %116
    ;
    __gm__ int8_t* v731 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %116
    ;
    const int64_t v732 = 1;
    // pto: %116
    ;
    const int64_t v733 = 1;
    // pto: %116
    ;
    const int64_t v734 = 1;
    // pto: %116
    ;
    int64_t v735 = v7 * v6;
    // pto: %116
    ;
    int64_t v736 = v734 * v735;
    // pto: %116
    ;
    pto::Shape<1, 1, 1, 1, -1> v737 = pto::Shape<1, 1, 1, 1, -1>(v732, v733, v734, v7, v9);
    // pto: %116
    ;
    pto::Stride<-1, -1, -1, -1, -1> v738 = pto::Stride<-1, -1, -1, -1, -1>(v733 * v736, v736, v735, v6, v7);
    // pto: %116
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v739 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v731 + (v730 + v59 * v6 + v37 * v7), v737, v738);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v728, v739);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v31_pview
    ;
    const int64_t v740 = 0;
    // pto: %stage__ssa_v31_pview
    ;
    __gm__ int8_t* v741 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v31_pview
    ;
    const int64_t v742 = 1;
    // pto: %stage__ssa_v31_pview
    ;
    const int64_t v743 = 1;
    // pto: %stage__ssa_v31_pview
    ;
    const int64_t v744 = 1;
    // pto: %stage__ssa_v31_pview
    ;
    int64_t v745 = v7 * v6;
    // pto: %stage__ssa_v31_pview
    ;
    int64_t v746 = v744 * v745;
    // pto: %stage__ssa_v31_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v747 = pto::Shape<1, 1, 1, 1, -1>(v742, v743, v744, v7, v9);
    // pto: %stage__ssa_v31_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v748 = pto::Stride<-1, -1, -1, -1, -1>(v743 * v746, v746, v745, v6, v7);
    // pto: %stage__ssa_v31_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v749 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v741 + (v740 + v59 * v6 + v37 * v7), v747, v748);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v749, v728);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v750 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v750);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v30
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v751 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v30
    ;
    uint64_t v752 = (uint64_t) v4;
    TASSIGN(v751, v752);
    // pto: %120
    ;
    const int64_t v753 = 0;
    // pto: %120
    ;
    __gm__ int8_t* v754 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %120
    ;
    const int64_t v755 = 1;
    // pto: %120
    ;
    const int64_t v756 = 1;
    // pto: %120
    ;
    const int64_t v757 = 1;
    // pto: %120
    ;
    int64_t v758 = v7 * v6;
    // pto: %120
    ;
    int64_t v759 = v757 * v758;
    // pto: %120
    ;
    pto::Shape<1, 1, 1, 1, -1> v760 = pto::Shape<1, 1, 1, 1, -1>(v755, v756, v757, v7, v9);
    // pto: %120
    ;
    pto::Stride<-1, -1, -1, -1, -1> v761 = pto::Stride<-1, -1, -1, -1, -1>(v756 * v759, v759, v758, v6, v7);
    // pto: %120
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v762 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v754 + (v753 + v59 * v6 + v38 * v7), v760, v761);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v751, v762);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v32_pview
    ;
    const int64_t v763 = 0;
    // pto: %stage__ssa_v32_pview
    ;
    __gm__ int8_t* v764 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v32_pview
    ;
    const int64_t v765 = 1;
    // pto: %stage__ssa_v32_pview
    ;
    const int64_t v766 = 1;
    // pto: %stage__ssa_v32_pview
    ;
    const int64_t v767 = 1;
    // pto: %stage__ssa_v32_pview
    ;
    int64_t v768 = v7 * v6;
    // pto: %stage__ssa_v32_pview
    ;
    int64_t v769 = v767 * v768;
    // pto: %stage__ssa_v32_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v770 = pto::Shape<1, 1, 1, 1, -1>(v765, v766, v767, v7, v9);
    // pto: %stage__ssa_v32_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v771 = pto::Stride<-1, -1, -1, -1, -1>(v766 * v769, v769, v768, v6, v7);
    // pto: %stage__ssa_v32_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v772 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v764 + (v763 + v59 * v6 + v38 * v7), v770, v771);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v772, v751);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    __gm__ int8_t* v773 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v773);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
    // pto: %tile__ssa_v31
    ;
    Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v774 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
    // pto: %tile__ssa_v31
    ;
    uint64_t v775 = (uint64_t) v4;
    TASSIGN(v774, v775);
    // pto: %124
    ;
    const int64_t v776 = 0;
    // pto: %124
    ;
    __gm__ int8_t* v777 = PTOAS__GLOBAL_TENSOR_DATA(v47);
    // pto: %124
    ;
    const int64_t v778 = 1;
    // pto: %124
    ;
    const int64_t v779 = 1;
    // pto: %124
    ;
    const int64_t v780 = 1;
    // pto: %124
    ;
    int64_t v781 = v7 * v6;
    // pto: %124
    ;
    int64_t v782 = v780 * v781;
    // pto: %124
    ;
    pto::Shape<1, 1, 1, 1, -1> v783 = pto::Shape<1, 1, 1, 1, -1>(v778, v779, v780, v7, v9);
    // pto: %124
    ;
    pto::Stride<-1, -1, -1, -1, -1> v784 = pto::Stride<-1, -1, -1, -1, -1>(v779 * v782, v782, v781, v6, v7);
    // pto: %124
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v785 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v777 + (v776 + v59 * v6 + v39 * v7), v783, v784);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v774, v785);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %stage__ssa_v33_pview
    ;
    const int64_t v786 = 0;
    // pto: %stage__ssa_v33_pview
    ;
    __gm__ int8_t* v787 = PTOAS__GLOBAL_TENSOR_DATA(v55);
    // pto: %stage__ssa_v33_pview
    ;
    const int64_t v788 = 1;
    // pto: %stage__ssa_v33_pview
    ;
    const int64_t v789 = 1;
    // pto: %stage__ssa_v33_pview
    ;
    const int64_t v790 = 1;
    // pto: %stage__ssa_v33_pview
    ;
    int64_t v791 = v7 * v6;
    // pto: %stage__ssa_v33_pview
    ;
    int64_t v792 = v790 * v791;
    // pto: %stage__ssa_v33_pview
    ;
    pto::Shape<1, 1, 1, 1, -1> v793 = pto::Shape<1, 1, 1, 1, -1>(v788, v789, v790, v7, v9);
    // pto: %stage__ssa_v33_pview
    ;
    pto::Stride<-1, -1, -1, -1, -1> v794 = pto::Stride<-1, -1, -1, -1, -1>(v789 * v792, v792, v791, v6, v7);
    // pto: %stage__ssa_v33_pview
    ;
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v795 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v787 + (v786 + v59 * v6 + v39 * v7), v793, v794);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v795, v774);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    __gm__ int8_t* v796 = PTOAS__GLOBAL_TENSOR_DATA(v82);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v796);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
  }
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM) && !defined(__COSTMODEL)
    // Reset AI Core atomic mode inherited from a prior kernel.
    set_atomic_none();
#endif

    // Unpack tensor: inp__ssa_v0
    __gm__ Tensor* inp__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ int8_t* inp__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(inp__ssa_v0_tensor->buffer.addr) + inp__ssa_v0_tensor->start_offset;

    // Unpack tensor: stage__ssa_v0
    __gm__ Tensor* stage__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int8_t* stage__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(stage__ssa_v0_tensor->buffer.addr) + stage__ssa_v0_tensor->start_offset;

    // Unpack CommContext: stage_ctx
    __gm__ int64_t* stage_ctx = reinterpret_cast<__gm__ int64_t*>(args[2]);

    // Forward to ptoas-generated function
    stage_step(inp__ssa_v0, stage__ssa_v0, stage_ctx);
}
