// Kernel Function: fill_counts_step
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"



using namespace pto;


// --- ptoas-generated code ---

template <typename Tensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(Tensor &tensor)
    -> decltype(tensor.data()) {
  return tensor.data();
}


enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void fill_counts_step(__gm__ int32_t* v1, __gm__ int32_t* v2, __gm__ int64_t* v3) {
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  // pto: %c4_index
  const int64_t v4 = 4;
  // pto: %c1_index
  const int64_t v5 = 1;
  // pto: %c0_index
  const int64_t v6 = 0;
  for (int64_t v7 = v6; v7 < v4; v7 += v5) {
    // pto: %v__tile
    ;
    int32_t v8 = (v1)[v7];
    (v2)[v7] = v8;
    // pto: %counts__ssa_v0_pview
    ;
    pto::Shape<1, 1, 1, 4, 1> v9 = pto::Shape<1, 1, 1, 4, 1>();
    // pto: %counts__ssa_v0_pview
    ;
    pto::Stride<4, 4, 4, 1, 4> v10 = pto::Stride<4, 4, 4, 1, 4>();
    // pto: %counts__ssa_v0_pview
    ;
    GlobalTensor<int32_t, pto::Shape<1, 1, 1, 4, 1>, pto::Stride<4, 4, 4, 1, 4>, pto::Layout::DN> v11 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 4, 1>, pto::Stride<4, 4, 4, 1, 4>, pto::Layout::DN>((__gm__ int32_t*) v2, v9, v10);
    __gm__ int32_t* v12 = PTOAS__GLOBAL_TENSOR_DATA(v11);
    PTOAS__DCCI_SINGLE_CACHE_LINE(v12);
    pipe_barrier(PIPE_ALL);
    dsb(DSB_DDR);
  }
  pipe_barrier(PIPE_ALL);
  dcci((__gm__ void*)0, cache_line_t::ENTIRE_DATA_CACHE);
  dsb((mem_dsb_t)0);
  #endif // __DAV_VEC__

  pipe_barrier(PIPE_ALL);
  dcci((__gm__ void*)0, cache_line_t::ENTIRE_DATA_CACHE);
  dsb((mem_dsb_t)0);
  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM) && !defined(__COSTMODEL)
    // Reset AI Core atomic mode inherited from a prior kernel.
    set_atomic_none();
#endif

    // Unpack tensor: counts_row__ssa_v0
    __gm__ Tensor* counts_row__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ int32_t* counts_row__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(counts_row__ssa_v0_tensor->buffer.addr) + counts_row__ssa_v0_tensor->start_offset;

    // Unpack tensor: counts__ssa_v0
    __gm__ Tensor* counts__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int32_t* counts__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(counts__ssa_v0_tensor->buffer.addr) + counts__ssa_v0_tensor->start_offset;

    // Unpack CommContext: counts_ctx
    __gm__ int64_t* counts_ctx = reinterpret_cast<__gm__ int64_t*>(args[2]);

    // Forward to ptoas-generated function
    fill_counts_step(counts_row__ssa_v0, counts__ssa_v0, counts_ctx);
}
