// Orchestration Function: chip_pipeline
// Generated by PyPTO IR Compiler

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "orchestration_api.h"
#include "tensor.h"

extern "C" {

__attribute__((visibility("default")))
OrchestrationConfig aicpu_orchestration_config(const ChipTaskArgs& orch_args) {
    (void)orch_args;
    return OrchestrationConfig{
        .expected_arg_count = 14,
    };
}

__attribute__((visibility("default")))
void aicpu_orchestration_entry(const ChipTaskArgs& orch_args) {
    // External tensors
    const Tensor& ext_inp = orch_args.tensor(0).ref();
    const Tensor& ext_counts_row = orch_args.tensor(1).ref();
    const Tensor& ext_out = orch_args.tensor(2).ref();
    const Tensor& ext_recv_out = orch_args.tensor(3).ref();
    const Tensor& ext_stage = orch_args.tensor(4).ref();
    const Tensor& ext_data = orch_args.tensor(5).ref();
    const Tensor& ext_signal = orch_args.tensor(6).ref();
    const Tensor& ext_counts = orch_args.tensor(7).ref();
    const Tensor& ext_recv = orch_args.tensor(8).ref();

    // Scalar params
    uint64_t stage_ctx = orch_args.scalar(0);
    uint64_t data_ctx = orch_args.scalar(1);
    uint64_t signal_ctx = orch_args.scalar(2);
    uint64_t counts_ctx = orch_args.scalar(3);
    uint64_t recv_ctx = orch_args.scalar(4);

    SIMPLER_SCOPE() {

        // Task 0: stage_step
        CoreTaskArgs params_t0;
        params_t0.add_input(ext_inp);
        params_t0.add_input(ext_counts_row);
        params_t0.add_inout(ext_stage);
        params_t0.add_inout(ext_counts);
        params_t0.add_scalar(stage_ctx);
        params_t0.add_scalar(counts_ctx);
        rt_submit_aiv_task(0, params_t0);

        // Task 1: __builtin_all_to_all_v__int8
        CoreTaskArgs params_t1;
        params_t1.add_input(ext_stage);
        params_t1.add_inout(ext_data);
        params_t1.add_inout(ext_signal);
        params_t1.add_input(ext_counts);
        params_t1.add_inout(ext_recv);
        params_t1.add_scalar(data_ctx);
        params_t1.add_scalar(signal_ctx);
        params_t1.add_scalar(recv_ctx);
        rt_submit_aiv_task(1, params_t1);

        // Task 2: consume_step
        CoreTaskArgs params_t2;
        params_t2.add_input(ext_data);
        params_t2.add_input(ext_recv);
        params_t2.add_output(ext_out);
        params_t2.add_output(ext_recv_out);
        params_t2.add_scalar(data_ctx);
        params_t2.add_scalar(recv_ctx);
        rt_submit_aiv_task(2, params_t2);
    }
}

}  // extern "C"
