// Kernel Function: consume_step
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"



using namespace pto;


// --- ptoas-generated code ---

template <typename Tensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(Tensor &tensor)
    -> decltype(tensor.data()) {
  return tensor.data();
}


enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void consume_step(__gm__ int8_t* v1, __gm__ int32_t* v2, __gm__ int8_t* v3, __gm__ int32_t* v4, __gm__ int64_t* v5, __gm__ int64_t* v6) {
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  // pto: %c0_i64
  const int64_t v7 = 0;
  // pto: %c2_index
  const int64_t v8 = 2;
  // pto: %c32768_index
  const int64_t v9 = 32768;
  // pto: %c1_index
  const int64_t v10 = 1;
  // pto: %c0_index
  const int64_t v11 = 0;
  // pto: %c16384_index
  const int64_t v12 = 16384;
  // pto: %data__ssa_v0_view
  const int64_t v13 = 1;
  // pto: %data__ssa_v0_view
  const int64_t v14 = 1;
  // pto: %data__ssa_v0_view
  const int64_t v15 = 1;
  // pto: %data__ssa_v0_view
  int64_t v16 = v8 * v9;
  // pto: %data__ssa_v0_view
  int64_t v17 = v15 * v16;
  // pto: %data__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v18 = pto::Shape<1, 1, 1, -1, -1>(v13, v14, v15, v8, v9);
  // pto: %data__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v19 = pto::Stride<-1, -1, -1, -1, -1>(v14 * v17, v17, v16, v9, v10);
  // pto: %data__ssa_v0_view
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v20 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v1, v18, v19);
  // pto: %out__ssa_v0_view
  const int64_t v21 = 1;
  // pto: %out__ssa_v0_view
  const int64_t v22 = 1;
  // pto: %out__ssa_v0_view
  const int64_t v23 = 1;
  // pto: %out__ssa_v0_view
  int64_t v24 = v8 * v9;
  // pto: %out__ssa_v0_view
  int64_t v25 = v23 * v24;
  // pto: %out__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v26 = pto::Shape<1, 1, 1, -1, -1>(v21, v22, v23, v8, v9);
  // pto: %out__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v27 = pto::Stride<-1, -1, -1, -1, -1>(v22 * v25, v25, v24, v9, v10);
  // pto: %out__ssa_v0_view
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v28 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v3, v26, v27);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID4);
  for (int64_t v29 = v11; v29 < v8; v29 += v10) {
    // pto: %n_rows_i32__tile
    ;
    int32_t v30 = (v2)[v29];
    (v4)[v29] = v30;
    // pto: %2
    ;
    int64_t v31 = (int64_t) v30;
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    for (int64_t v32 = v11; v32 < v31; v32 += v10) {
      // pto: %3
      ;
      int64_t v33 = (int64_t) ((uint64_t) v29 + (uint64_t) v32);
      // pto: %tile__ssa_v0
      ;
      Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v34 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
      // pto: %tile__ssa_v0
      ;
      uint64_t v35 = (uint64_t) v7;
      TASSIGN(v34, v35);
      // pto: %4
      ;
      int64_t v36 = v33 < v11 ? v11 : v33;
      // pto: %data__ssa_v0_pview
      ;
      const int64_t v37 = 0;
      // pto: %data__ssa_v0_pview
      ;
      __gm__ int8_t* v38 = PTOAS__GLOBAL_TENSOR_DATA(v20);
      // pto: %data__ssa_v0_pview
      ;
      const int64_t v39 = 1;
      // pto: %data__ssa_v0_pview
      ;
      const int64_t v40 = 1;
      // pto: %data__ssa_v0_pview
      ;
      const int64_t v41 = 1;
      // pto: %data__ssa_v0_pview
      ;
      int64_t v42 = v10 * v9;
      // pto: %data__ssa_v0_pview
      ;
      int64_t v43 = v41 * v42;
      // pto: %data__ssa_v0_pview
      ;
      pto::Shape<1, 1, 1, 1, -1> v44 = pto::Shape<1, 1, 1, 1, -1>(v39, v40, v41, v10, v12);
      // pto: %data__ssa_v0_pview
      ;
      pto::Stride<-1, -1, -1, -1, -1> v45 = pto::Stride<-1, -1, -1, -1, -1>(v40 * v43, v43, v42, v9, v10);
      // pto: %data__ssa_v0_pview
      ;
      GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v46 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v38 + (v37 + v36 * v9 + v11 * v10), v44, v45);
      wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
      TLOAD(v34, v46);
      set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
      // pto: %out__iter_v3_pview
      ;
      const int64_t v47 = 0;
      // pto: %out__iter_v3_pview
      ;
      __gm__ int8_t* v48 = PTOAS__GLOBAL_TENSOR_DATA(v28);
      // pto: %out__iter_v3_pview
      ;
      const int64_t v49 = 1;
      // pto: %out__iter_v3_pview
      ;
      const int64_t v50 = 1;
      // pto: %out__iter_v3_pview
      ;
      const int64_t v51 = 1;
      // pto: %out__iter_v3_pview
      ;
      int64_t v52 = v10 * v9;
      // pto: %out__iter_v3_pview
      ;
      int64_t v53 = v51 * v52;
      // pto: %out__iter_v3_pview
      ;
      pto::Shape<1, 1, 1, 1, -1> v54 = pto::Shape<1, 1, 1, 1, -1>(v49, v50, v51, v10, v12);
      // pto: %out__iter_v3_pview
      ;
      pto::Stride<-1, -1, -1, -1, -1> v55 = pto::Stride<-1, -1, -1, -1, -1>(v50 * v53, v53, v52, v9, v10);
      // pto: %out__iter_v3_pview
      ;
      GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v56 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v48 + (v47 + v36 * v9 + v11 * v10), v54, v55);
      wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
      TSTORE(v56, v34);
      set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
      // pto: %tile__ssa_v1
      ;
      Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v57 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
      // pto: %tile__ssa_v1
      ;
      uint64_t v58 = (uint64_t) v7;
      TASSIGN(v57, v58);
      // pto: %7
      ;
      const int64_t v59 = 0;
      // pto: %7
      ;
      __gm__ int8_t* v60 = PTOAS__GLOBAL_TENSOR_DATA(v20);
      // pto: %7
      ;
      const int64_t v61 = 1;
      // pto: %7
      ;
      const int64_t v62 = 1;
      // pto: %7
      ;
      const int64_t v63 = 1;
      // pto: %7
      ;
      int64_t v64 = v10 * v9;
      // pto: %7
      ;
      int64_t v65 = v63 * v64;
      // pto: %7
      ;
      pto::Shape<1, 1, 1, 1, -1> v66 = pto::Shape<1, 1, 1, 1, -1>(v61, v62, v63, v10, v12);
      // pto: %7
      ;
      pto::Stride<-1, -1, -1, -1, -1> v67 = pto::Stride<-1, -1, -1, -1, -1>(v62 * v65, v65, v64, v9, v10);
      // pto: %7
      ;
      GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v68 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v60 + (v59 + v36 * v9 + v12 * v10), v66, v67);
      wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
      TLOAD(v57, v68);
      set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID1);
      // pto: %out__ssa_v5_pview
      ;
      const int64_t v69 = 0;
      // pto: %out__ssa_v5_pview
      ;
      __gm__ int8_t* v70 = PTOAS__GLOBAL_TENSOR_DATA(v28);
      // pto: %out__ssa_v5_pview
      ;
      const int64_t v71 = 1;
      // pto: %out__ssa_v5_pview
      ;
      const int64_t v72 = 1;
      // pto: %out__ssa_v5_pview
      ;
      const int64_t v73 = 1;
      // pto: %out__ssa_v5_pview
      ;
      int64_t v74 = v10 * v9;
      // pto: %out__ssa_v5_pview
      ;
      int64_t v75 = v73 * v74;
      // pto: %out__ssa_v5_pview
      ;
      pto::Shape<1, 1, 1, 1, -1> v76 = pto::Shape<1, 1, 1, 1, -1>(v71, v72, v73, v10, v12);
      // pto: %out__ssa_v5_pview
      ;
      pto::Stride<-1, -1, -1, -1, -1> v77 = pto::Stride<-1, -1, -1, -1, -1>(v72 * v75, v75, v74, v9, v10);
      // pto: %out__ssa_v5_pview
      ;
      GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v78 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v70 + (v69 + v36 * v9 + v12 * v10), v76, v77);
      wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID1);
      TSTORE(v78, v57);
      set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    };
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
    for (int64_t v79 = v31; v79 < v10; v79 += v10) {
      // pto: %10
      ;
      int64_t v80 = (int64_t) ((uint64_t) v29 + (uint64_t) v79);
      // pto: %tile__ssa_v2
      ;
      Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v81 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
      // pto: %tile__ssa_v2
      ;
      uint64_t v82 = (uint64_t) v7;
      TASSIGN(v81, v82);
      // pto: %11
      ;
      int64_t v83 = v80 < v11 ? v11 : v80;
      // pto: %12
      ;
      const int64_t v84 = 0;
      // pto: %12
      ;
      __gm__ int8_t* v85 = PTOAS__GLOBAL_TENSOR_DATA(v20);
      // pto: %12
      ;
      const int64_t v86 = 1;
      // pto: %12
      ;
      const int64_t v87 = 1;
      // pto: %12
      ;
      const int64_t v88 = 1;
      // pto: %12
      ;
      int64_t v89 = v10 * v9;
      // pto: %12
      ;
      int64_t v90 = v88 * v89;
      // pto: %12
      ;
      pto::Shape<1, 1, 1, 1, -1> v91 = pto::Shape<1, 1, 1, 1, -1>(v86, v87, v88, v10, v12);
      // pto: %12
      ;
      pto::Stride<-1, -1, -1, -1, -1> v92 = pto::Stride<-1, -1, -1, -1, -1>(v87 * v90, v90, v89, v9, v10);
      // pto: %12
      ;
      GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v93 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v85 + (v84 + v83 * v9 + v11 * v10), v91, v92);
      wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID4);
      TLOAD(v81, v93);
      set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID2);
      // pto: %out__iter_v7_pview
      ;
      const int64_t v94 = 0;
      // pto: %out__iter_v7_pview
      ;
      __gm__ int8_t* v95 = PTOAS__GLOBAL_TENSOR_DATA(v28);
      // pto: %out__iter_v7_pview
      ;
      const int64_t v96 = 1;
      // pto: %out__iter_v7_pview
      ;
      const int64_t v97 = 1;
      // pto: %out__iter_v7_pview
      ;
      const int64_t v98 = 1;
      // pto: %out__iter_v7_pview
      ;
      int64_t v99 = v10 * v9;
      // pto: %out__iter_v7_pview
      ;
      int64_t v100 = v98 * v99;
      // pto: %out__iter_v7_pview
      ;
      pto::Shape<1, 1, 1, 1, -1> v101 = pto::Shape<1, 1, 1, 1, -1>(v96, v97, v98, v10, v12);
      // pto: %out__iter_v7_pview
      ;
      pto::Stride<-1, -1, -1, -1, -1> v102 = pto::Stride<-1, -1, -1, -1, -1>(v97 * v100, v100, v99, v9, v10);
      // pto: %out__iter_v7_pview
      ;
      GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v103 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v95 + (v94 + v83 * v9 + v11 * v10), v101, v102);
      wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID2);
      TSTORE(v103, v81);
      set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID5);
      // pto: %tile__ssa_v3
      ;
      Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v104 = Tile<TileType::Vec, int8_t, 1, 16384, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
      // pto: %tile__ssa_v3
      ;
      uint64_t v105 = (uint64_t) v7;
      TASSIGN(v104, v105);
      // pto: %15
      ;
      const int64_t v106 = 0;
      // pto: %15
      ;
      __gm__ int8_t* v107 = PTOAS__GLOBAL_TENSOR_DATA(v20);
      // pto: %15
      ;
      const int64_t v108 = 1;
      // pto: %15
      ;
      const int64_t v109 = 1;
      // pto: %15
      ;
      const int64_t v110 = 1;
      // pto: %15
      ;
      int64_t v111 = v10 * v9;
      // pto: %15
      ;
      int64_t v112 = v110 * v111;
      // pto: %15
      ;
      pto::Shape<1, 1, 1, 1, -1> v113 = pto::Shape<1, 1, 1, 1, -1>(v108, v109, v110, v10, v12);
      // pto: %15
      ;
      pto::Stride<-1, -1, -1, -1, -1> v114 = pto::Stride<-1, -1, -1, -1, -1>(v109 * v112, v112, v111, v9, v10);
      // pto: %15
      ;
      GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v115 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v107 + (v106 + v83 * v9 + v12 * v10), v113, v114);
      wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID5);
      TLOAD(v104, v115);
      set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID3);
      // pto: %out__ssa_v9_pview
      ;
      const int64_t v116 = 0;
      // pto: %out__ssa_v9_pview
      ;
      __gm__ int8_t* v117 = PTOAS__GLOBAL_TENSOR_DATA(v28);
      // pto: %out__ssa_v9_pview
      ;
      const int64_t v118 = 1;
      // pto: %out__ssa_v9_pview
      ;
      const int64_t v119 = 1;
      // pto: %out__ssa_v9_pview
      ;
      const int64_t v120 = 1;
      // pto: %out__ssa_v9_pview
      ;
      int64_t v121 = v10 * v9;
      // pto: %out__ssa_v9_pview
      ;
      int64_t v122 = v120 * v121;
      // pto: %out__ssa_v9_pview
      ;
      pto::Shape<1, 1, 1, 1, -1> v123 = pto::Shape<1, 1, 1, 1, -1>(v118, v119, v120, v10, v12);
      // pto: %out__ssa_v9_pview
      ;
      pto::Stride<-1, -1, -1, -1, -1> v124 = pto::Stride<-1, -1, -1, -1, -1>(v119 * v122, v122, v121, v9, v10);
      // pto: %out__ssa_v9_pview
      ;
      GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v125 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v117 + (v116 + v83 * v9 + v12 * v10), v123, v124);
      wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID3);
      TSTORE(v125, v104);
      set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID4);
    };
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  }
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID4);
  pipe_barrier(PIPE_ALL);
  dcci((__gm__ void*)0, cache_line_t::ENTIRE_DATA_CACHE);
  dsb((mem_dsb_t)0);
  #endif // __DAV_VEC__

  pipe_barrier(PIPE_ALL);
  dcci((__gm__ void*)0, cache_line_t::ENTIRE_DATA_CACHE);
  dsb((mem_dsb_t)0);
  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM) && !defined(__COSTMODEL)
    // Reset AI Core atomic mode inherited from a prior kernel.
    set_atomic_none();
#endif

    // Unpack tensor: data__ssa_v0
    __gm__ Tensor* data__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ int8_t* data__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(data__ssa_v0_tensor->buffer.addr) + data__ssa_v0_tensor->start_offset;

    // Unpack tensor: recv_counts__ssa_v0
    __gm__ Tensor* recv_counts__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int32_t* recv_counts__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(recv_counts__ssa_v0_tensor->buffer.addr) + recv_counts__ssa_v0_tensor->start_offset;

    // Unpack tensor: out__ssa_v0
    __gm__ Tensor* out__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ int8_t* out__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(out__ssa_v0_tensor->buffer.addr) + out__ssa_v0_tensor->start_offset;

    // Unpack tensor: recv_out__ssa_v0
    __gm__ Tensor* recv_out__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ int32_t* recv_out__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(recv_out__ssa_v0_tensor->buffer.addr) + recv_out__ssa_v0_tensor->start_offset;

    // Unpack CommContext: data_ctx
    __gm__ int64_t* data_ctx = reinterpret_cast<__gm__ int64_t*>(args[4]);

    // Unpack CommContext: recv_counts_ctx
    __gm__ int64_t* recv_counts_ctx = reinterpret_cast<__gm__ int64_t*>(args[5]);

    // Forward to ptoas-generated function
    consume_step(data__ssa_v0, recv_counts__ssa_v0, out__ssa_v0, recv_out__ssa_v0, data_ctx, recv_counts_ctx);
}
